
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `closing_exam_contents` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model closing_exam_contents
 * Stores timed unit closing assessment tests to measure overall comprehension.
 * Tests are chronometer-based evaluations given at the end of learning units.
 */
export type closing_exam_contentsModel = runtime.Types.Result.DefaultSelection<Prisma.$closing_exam_contentsPayload>

export type AggregateClosing_exam_contents = {
  _count: Closing_exam_contentsCountAggregateOutputType | null
  _avg: Closing_exam_contentsAvgAggregateOutputType | null
  _sum: Closing_exam_contentsSumAggregateOutputType | null
  _min: Closing_exam_contentsMinAggregateOutputType | null
  _max: Closing_exam_contentsMaxAggregateOutputType | null
}

export type Closing_exam_contentsAvgAggregateOutputType = {
  id: number | null
  lesson_id: number | null
  time_limit: number | null
  passing_score: number | null
  question_order: number | null
  points_value: number | null
}

export type Closing_exam_contentsSumAggregateOutputType = {
  id: number | null
  lesson_id: number | null
  time_limit: number | null
  passing_score: number | null
  question_order: number | null
  points_value: number | null
}

export type Closing_exam_contentsMinAggregateOutputType = {
  id: number | null
  lesson_id: number | null
  title: string | null
  description: string | null
  time_limit: number | null
  question: string | null
  correct_answer: string | null
  option_b: string | null
  option_c: string | null
  option_d: string | null
  passing_score: number | null
  difficulty_level: string | null
  question_order: number | null
  points_value: number | null
  feedback_correct: string | null
  feedback_incorrect: string | null
}

export type Closing_exam_contentsMaxAggregateOutputType = {
  id: number | null
  lesson_id: number | null
  title: string | null
  description: string | null
  time_limit: number | null
  question: string | null
  correct_answer: string | null
  option_b: string | null
  option_c: string | null
  option_d: string | null
  passing_score: number | null
  difficulty_level: string | null
  question_order: number | null
  points_value: number | null
  feedback_correct: string | null
  feedback_incorrect: string | null
}

export type Closing_exam_contentsCountAggregateOutputType = {
  id: number
  lesson_id: number
  title: number
  description: number
  time_limit: number
  question: number
  correct_answer: number
  option_b: number
  option_c: number
  option_d: number
  passing_score: number
  difficulty_level: number
  question_order: number
  points_value: number
  feedback_correct: number
  feedback_incorrect: number
  _all: number
}


export type Closing_exam_contentsAvgAggregateInputType = {
  id?: true
  lesson_id?: true
  time_limit?: true
  passing_score?: true
  question_order?: true
  points_value?: true
}

export type Closing_exam_contentsSumAggregateInputType = {
  id?: true
  lesson_id?: true
  time_limit?: true
  passing_score?: true
  question_order?: true
  points_value?: true
}

export type Closing_exam_contentsMinAggregateInputType = {
  id?: true
  lesson_id?: true
  title?: true
  description?: true
  time_limit?: true
  question?: true
  correct_answer?: true
  option_b?: true
  option_c?: true
  option_d?: true
  passing_score?: true
  difficulty_level?: true
  question_order?: true
  points_value?: true
  feedback_correct?: true
  feedback_incorrect?: true
}

export type Closing_exam_contentsMaxAggregateInputType = {
  id?: true
  lesson_id?: true
  title?: true
  description?: true
  time_limit?: true
  question?: true
  correct_answer?: true
  option_b?: true
  option_c?: true
  option_d?: true
  passing_score?: true
  difficulty_level?: true
  question_order?: true
  points_value?: true
  feedback_correct?: true
  feedback_incorrect?: true
}

export type Closing_exam_contentsCountAggregateInputType = {
  id?: true
  lesson_id?: true
  title?: true
  description?: true
  time_limit?: true
  question?: true
  correct_answer?: true
  option_b?: true
  option_c?: true
  option_d?: true
  passing_score?: true
  difficulty_level?: true
  question_order?: true
  points_value?: true
  feedback_correct?: true
  feedback_incorrect?: true
  _all?: true
}

export type Closing_exam_contentsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which closing_exam_contents to aggregate.
   */
  where?: Prisma.closing_exam_contentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of closing_exam_contents to fetch.
   */
  orderBy?: Prisma.closing_exam_contentsOrderByWithRelationInput | Prisma.closing_exam_contentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.closing_exam_contentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` closing_exam_contents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` closing_exam_contents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned closing_exam_contents
  **/
  _count?: true | Closing_exam_contentsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Closing_exam_contentsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Closing_exam_contentsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Closing_exam_contentsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Closing_exam_contentsMaxAggregateInputType
}

export type GetClosing_exam_contentsAggregateType<T extends Closing_exam_contentsAggregateArgs> = {
      [P in keyof T & keyof AggregateClosing_exam_contents]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateClosing_exam_contents[P]>
    : Prisma.GetScalarType<T[P], AggregateClosing_exam_contents[P]>
}




export type closing_exam_contentsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.closing_exam_contentsWhereInput
  orderBy?: Prisma.closing_exam_contentsOrderByWithAggregationInput | Prisma.closing_exam_contentsOrderByWithAggregationInput[]
  by: Prisma.Closing_exam_contentsScalarFieldEnum[] | Prisma.Closing_exam_contentsScalarFieldEnum
  having?: Prisma.closing_exam_contentsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Closing_exam_contentsCountAggregateInputType | true
  _avg?: Closing_exam_contentsAvgAggregateInputType
  _sum?: Closing_exam_contentsSumAggregateInputType
  _min?: Closing_exam_contentsMinAggregateInputType
  _max?: Closing_exam_contentsMaxAggregateInputType
}

export type Closing_exam_contentsGroupByOutputType = {
  id: number
  lesson_id: number
  title: string
  description: string | null
  time_limit: number
  question: string
  correct_answer: string
  option_b: string
  option_c: string
  option_d: string | null
  passing_score: number
  difficulty_level: string
  question_order: number
  points_value: number
  feedback_correct: string | null
  feedback_incorrect: string | null
  _count: Closing_exam_contentsCountAggregateOutputType | null
  _avg: Closing_exam_contentsAvgAggregateOutputType | null
  _sum: Closing_exam_contentsSumAggregateOutputType | null
  _min: Closing_exam_contentsMinAggregateOutputType | null
  _max: Closing_exam_contentsMaxAggregateOutputType | null
}

export type GetClosing_exam_contentsGroupByPayload<T extends closing_exam_contentsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Closing_exam_contentsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Closing_exam_contentsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Closing_exam_contentsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Closing_exam_contentsGroupByOutputType[P]>
      }
    >
  >



export type closing_exam_contentsWhereInput = {
  AND?: Prisma.closing_exam_contentsWhereInput | Prisma.closing_exam_contentsWhereInput[]
  OR?: Prisma.closing_exam_contentsWhereInput[]
  NOT?: Prisma.closing_exam_contentsWhereInput | Prisma.closing_exam_contentsWhereInput[]
  id?: Prisma.IntFilter<"closing_exam_contents"> | number
  lesson_id?: Prisma.IntFilter<"closing_exam_contents"> | number
  title?: Prisma.StringFilter<"closing_exam_contents"> | string
  description?: Prisma.StringNullableFilter<"closing_exam_contents"> | string | null
  time_limit?: Prisma.IntFilter<"closing_exam_contents"> | number
  question?: Prisma.StringFilter<"closing_exam_contents"> | string
  correct_answer?: Prisma.StringFilter<"closing_exam_contents"> | string
  option_b?: Prisma.StringFilter<"closing_exam_contents"> | string
  option_c?: Prisma.StringFilter<"closing_exam_contents"> | string
  option_d?: Prisma.StringNullableFilter<"closing_exam_contents"> | string | null
  passing_score?: Prisma.IntFilter<"closing_exam_contents"> | number
  difficulty_level?: Prisma.StringFilter<"closing_exam_contents"> | string
  question_order?: Prisma.IntFilter<"closing_exam_contents"> | number
  points_value?: Prisma.IntFilter<"closing_exam_contents"> | number
  feedback_correct?: Prisma.StringNullableFilter<"closing_exam_contents"> | string | null
  feedback_incorrect?: Prisma.StringNullableFilter<"closing_exam_contents"> | string | null
  lessons?: Prisma.XOR<Prisma.LessonsScalarRelationFilter, Prisma.lessonsWhereInput>
}

export type closing_exam_contentsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  lesson_id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  time_limit?: Prisma.SortOrder
  question?: Prisma.SortOrder
  correct_answer?: Prisma.SortOrder
  option_b?: Prisma.SortOrder
  option_c?: Prisma.SortOrder
  option_d?: Prisma.SortOrderInput | Prisma.SortOrder
  passing_score?: Prisma.SortOrder
  difficulty_level?: Prisma.SortOrder
  question_order?: Prisma.SortOrder
  points_value?: Prisma.SortOrder
  feedback_correct?: Prisma.SortOrderInput | Prisma.SortOrder
  feedback_incorrect?: Prisma.SortOrderInput | Prisma.SortOrder
  lessons?: Prisma.lessonsOrderByWithRelationInput
}

export type closing_exam_contentsWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.closing_exam_contentsWhereInput | Prisma.closing_exam_contentsWhereInput[]
  OR?: Prisma.closing_exam_contentsWhereInput[]
  NOT?: Prisma.closing_exam_contentsWhereInput | Prisma.closing_exam_contentsWhereInput[]
  lesson_id?: Prisma.IntFilter<"closing_exam_contents"> | number
  title?: Prisma.StringFilter<"closing_exam_contents"> | string
  description?: Prisma.StringNullableFilter<"closing_exam_contents"> | string | null
  time_limit?: Prisma.IntFilter<"closing_exam_contents"> | number
  question?: Prisma.StringFilter<"closing_exam_contents"> | string
  correct_answer?: Prisma.StringFilter<"closing_exam_contents"> | string
  option_b?: Prisma.StringFilter<"closing_exam_contents"> | string
  option_c?: Prisma.StringFilter<"closing_exam_contents"> | string
  option_d?: Prisma.StringNullableFilter<"closing_exam_contents"> | string | null
  passing_score?: Prisma.IntFilter<"closing_exam_contents"> | number
  difficulty_level?: Prisma.StringFilter<"closing_exam_contents"> | string
  question_order?: Prisma.IntFilter<"closing_exam_contents"> | number
  points_value?: Prisma.IntFilter<"closing_exam_contents"> | number
  feedback_correct?: Prisma.StringNullableFilter<"closing_exam_contents"> | string | null
  feedback_incorrect?: Prisma.StringNullableFilter<"closing_exam_contents"> | string | null
  lessons?: Prisma.XOR<Prisma.LessonsScalarRelationFilter, Prisma.lessonsWhereInput>
}, "id">

export type closing_exam_contentsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  lesson_id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  time_limit?: Prisma.SortOrder
  question?: Prisma.SortOrder
  correct_answer?: Prisma.SortOrder
  option_b?: Prisma.SortOrder
  option_c?: Prisma.SortOrder
  option_d?: Prisma.SortOrderInput | Prisma.SortOrder
  passing_score?: Prisma.SortOrder
  difficulty_level?: Prisma.SortOrder
  question_order?: Prisma.SortOrder
  points_value?: Prisma.SortOrder
  feedback_correct?: Prisma.SortOrderInput | Prisma.SortOrder
  feedback_incorrect?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.closing_exam_contentsCountOrderByAggregateInput
  _avg?: Prisma.closing_exam_contentsAvgOrderByAggregateInput
  _max?: Prisma.closing_exam_contentsMaxOrderByAggregateInput
  _min?: Prisma.closing_exam_contentsMinOrderByAggregateInput
  _sum?: Prisma.closing_exam_contentsSumOrderByAggregateInput
}

export type closing_exam_contentsScalarWhereWithAggregatesInput = {
  AND?: Prisma.closing_exam_contentsScalarWhereWithAggregatesInput | Prisma.closing_exam_contentsScalarWhereWithAggregatesInput[]
  OR?: Prisma.closing_exam_contentsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.closing_exam_contentsScalarWhereWithAggregatesInput | Prisma.closing_exam_contentsScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"closing_exam_contents"> | number
  lesson_id?: Prisma.IntWithAggregatesFilter<"closing_exam_contents"> | number
  title?: Prisma.StringWithAggregatesFilter<"closing_exam_contents"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"closing_exam_contents"> | string | null
  time_limit?: Prisma.IntWithAggregatesFilter<"closing_exam_contents"> | number
  question?: Prisma.StringWithAggregatesFilter<"closing_exam_contents"> | string
  correct_answer?: Prisma.StringWithAggregatesFilter<"closing_exam_contents"> | string
  option_b?: Prisma.StringWithAggregatesFilter<"closing_exam_contents"> | string
  option_c?: Prisma.StringWithAggregatesFilter<"closing_exam_contents"> | string
  option_d?: Prisma.StringNullableWithAggregatesFilter<"closing_exam_contents"> | string | null
  passing_score?: Prisma.IntWithAggregatesFilter<"closing_exam_contents"> | number
  difficulty_level?: Prisma.StringWithAggregatesFilter<"closing_exam_contents"> | string
  question_order?: Prisma.IntWithAggregatesFilter<"closing_exam_contents"> | number
  points_value?: Prisma.IntWithAggregatesFilter<"closing_exam_contents"> | number
  feedback_correct?: Prisma.StringNullableWithAggregatesFilter<"closing_exam_contents"> | string | null
  feedback_incorrect?: Prisma.StringNullableWithAggregatesFilter<"closing_exam_contents"> | string | null
}

export type closing_exam_contentsCreateInput = {
  title: string
  description?: string | null
  time_limit?: number
  question: string
  correct_answer: string
  option_b: string
  option_c: string
  option_d?: string | null
  passing_score?: number
  difficulty_level?: string
  question_order?: number
  points_value?: number
  feedback_correct?: string | null
  feedback_incorrect?: string | null
  lessons: Prisma.lessonsCreateNestedOneWithoutClosing_exam_contentsInput
}

export type closing_exam_contentsUncheckedCreateInput = {
  id?: number
  lesson_id: number
  title: string
  description?: string | null
  time_limit?: number
  question: string
  correct_answer: string
  option_b: string
  option_c: string
  option_d?: string | null
  passing_score?: number
  difficulty_level?: string
  question_order?: number
  points_value?: number
  feedback_correct?: string | null
  feedback_incorrect?: string | null
}

export type closing_exam_contentsUpdateInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  time_limit?: Prisma.IntFieldUpdateOperationsInput | number
  question?: Prisma.StringFieldUpdateOperationsInput | string
  correct_answer?: Prisma.StringFieldUpdateOperationsInput | string
  option_b?: Prisma.StringFieldUpdateOperationsInput | string
  option_c?: Prisma.StringFieldUpdateOperationsInput | string
  option_d?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  passing_score?: Prisma.IntFieldUpdateOperationsInput | number
  difficulty_level?: Prisma.StringFieldUpdateOperationsInput | string
  question_order?: Prisma.IntFieldUpdateOperationsInput | number
  points_value?: Prisma.IntFieldUpdateOperationsInput | number
  feedback_correct?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  feedback_incorrect?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  lessons?: Prisma.lessonsUpdateOneRequiredWithoutClosing_exam_contentsNestedInput
}

export type closing_exam_contentsUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  lesson_id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  time_limit?: Prisma.IntFieldUpdateOperationsInput | number
  question?: Prisma.StringFieldUpdateOperationsInput | string
  correct_answer?: Prisma.StringFieldUpdateOperationsInput | string
  option_b?: Prisma.StringFieldUpdateOperationsInput | string
  option_c?: Prisma.StringFieldUpdateOperationsInput | string
  option_d?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  passing_score?: Prisma.IntFieldUpdateOperationsInput | number
  difficulty_level?: Prisma.StringFieldUpdateOperationsInput | string
  question_order?: Prisma.IntFieldUpdateOperationsInput | number
  points_value?: Prisma.IntFieldUpdateOperationsInput | number
  feedback_correct?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  feedback_incorrect?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type closing_exam_contentsCreateManyInput = {
  id?: number
  lesson_id: number
  title: string
  description?: string | null
  time_limit?: number
  question: string
  correct_answer: string
  option_b: string
  option_c: string
  option_d?: string | null
  passing_score?: number
  difficulty_level?: string
  question_order?: number
  points_value?: number
  feedback_correct?: string | null
  feedback_incorrect?: string | null
}

export type closing_exam_contentsUpdateManyMutationInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  time_limit?: Prisma.IntFieldUpdateOperationsInput | number
  question?: Prisma.StringFieldUpdateOperationsInput | string
  correct_answer?: Prisma.StringFieldUpdateOperationsInput | string
  option_b?: Prisma.StringFieldUpdateOperationsInput | string
  option_c?: Prisma.StringFieldUpdateOperationsInput | string
  option_d?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  passing_score?: Prisma.IntFieldUpdateOperationsInput | number
  difficulty_level?: Prisma.StringFieldUpdateOperationsInput | string
  question_order?: Prisma.IntFieldUpdateOperationsInput | number
  points_value?: Prisma.IntFieldUpdateOperationsInput | number
  feedback_correct?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  feedback_incorrect?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type closing_exam_contentsUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  lesson_id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  time_limit?: Prisma.IntFieldUpdateOperationsInput | number
  question?: Prisma.StringFieldUpdateOperationsInput | string
  correct_answer?: Prisma.StringFieldUpdateOperationsInput | string
  option_b?: Prisma.StringFieldUpdateOperationsInput | string
  option_c?: Prisma.StringFieldUpdateOperationsInput | string
  option_d?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  passing_score?: Prisma.IntFieldUpdateOperationsInput | number
  difficulty_level?: Prisma.StringFieldUpdateOperationsInput | string
  question_order?: Prisma.IntFieldUpdateOperationsInput | number
  points_value?: Prisma.IntFieldUpdateOperationsInput | number
  feedback_correct?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  feedback_incorrect?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type Closing_exam_contentsListRelationFilter = {
  every?: Prisma.closing_exam_contentsWhereInput
  some?: Prisma.closing_exam_contentsWhereInput
  none?: Prisma.closing_exam_contentsWhereInput
}

export type closing_exam_contentsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type closing_exam_contentsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  lesson_id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  time_limit?: Prisma.SortOrder
  question?: Prisma.SortOrder
  correct_answer?: Prisma.SortOrder
  option_b?: Prisma.SortOrder
  option_c?: Prisma.SortOrder
  option_d?: Prisma.SortOrder
  passing_score?: Prisma.SortOrder
  difficulty_level?: Prisma.SortOrder
  question_order?: Prisma.SortOrder
  points_value?: Prisma.SortOrder
  feedback_correct?: Prisma.SortOrder
  feedback_incorrect?: Prisma.SortOrder
}

export type closing_exam_contentsAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  lesson_id?: Prisma.SortOrder
  time_limit?: Prisma.SortOrder
  passing_score?: Prisma.SortOrder
  question_order?: Prisma.SortOrder
  points_value?: Prisma.SortOrder
}

export type closing_exam_contentsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  lesson_id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  time_limit?: Prisma.SortOrder
  question?: Prisma.SortOrder
  correct_answer?: Prisma.SortOrder
  option_b?: Prisma.SortOrder
  option_c?: Prisma.SortOrder
  option_d?: Prisma.SortOrder
  passing_score?: Prisma.SortOrder
  difficulty_level?: Prisma.SortOrder
  question_order?: Prisma.SortOrder
  points_value?: Prisma.SortOrder
  feedback_correct?: Prisma.SortOrder
  feedback_incorrect?: Prisma.SortOrder
}

export type closing_exam_contentsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  lesson_id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  time_limit?: Prisma.SortOrder
  question?: Prisma.SortOrder
  correct_answer?: Prisma.SortOrder
  option_b?: Prisma.SortOrder
  option_c?: Prisma.SortOrder
  option_d?: Prisma.SortOrder
  passing_score?: Prisma.SortOrder
  difficulty_level?: Prisma.SortOrder
  question_order?: Prisma.SortOrder
  points_value?: Prisma.SortOrder
  feedback_correct?: Prisma.SortOrder
  feedback_incorrect?: Prisma.SortOrder
}

export type closing_exam_contentsSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  lesson_id?: Prisma.SortOrder
  time_limit?: Prisma.SortOrder
  passing_score?: Prisma.SortOrder
  question_order?: Prisma.SortOrder
  points_value?: Prisma.SortOrder
}

export type closing_exam_contentsCreateNestedManyWithoutLessonsInput = {
  create?: Prisma.XOR<Prisma.closing_exam_contentsCreateWithoutLessonsInput, Prisma.closing_exam_contentsUncheckedCreateWithoutLessonsInput> | Prisma.closing_exam_contentsCreateWithoutLessonsInput[] | Prisma.closing_exam_contentsUncheckedCreateWithoutLessonsInput[]
  connectOrCreate?: Prisma.closing_exam_contentsCreateOrConnectWithoutLessonsInput | Prisma.closing_exam_contentsCreateOrConnectWithoutLessonsInput[]
  createMany?: Prisma.closing_exam_contentsCreateManyLessonsInputEnvelope
  connect?: Prisma.closing_exam_contentsWhereUniqueInput | Prisma.closing_exam_contentsWhereUniqueInput[]
}

export type closing_exam_contentsUncheckedCreateNestedManyWithoutLessonsInput = {
  create?: Prisma.XOR<Prisma.closing_exam_contentsCreateWithoutLessonsInput, Prisma.closing_exam_contentsUncheckedCreateWithoutLessonsInput> | Prisma.closing_exam_contentsCreateWithoutLessonsInput[] | Prisma.closing_exam_contentsUncheckedCreateWithoutLessonsInput[]
  connectOrCreate?: Prisma.closing_exam_contentsCreateOrConnectWithoutLessonsInput | Prisma.closing_exam_contentsCreateOrConnectWithoutLessonsInput[]
  createMany?: Prisma.closing_exam_contentsCreateManyLessonsInputEnvelope
  connect?: Prisma.closing_exam_contentsWhereUniqueInput | Prisma.closing_exam_contentsWhereUniqueInput[]
}

export type closing_exam_contentsUpdateManyWithoutLessonsNestedInput = {
  create?: Prisma.XOR<Prisma.closing_exam_contentsCreateWithoutLessonsInput, Prisma.closing_exam_contentsUncheckedCreateWithoutLessonsInput> | Prisma.closing_exam_contentsCreateWithoutLessonsInput[] | Prisma.closing_exam_contentsUncheckedCreateWithoutLessonsInput[]
  connectOrCreate?: Prisma.closing_exam_contentsCreateOrConnectWithoutLessonsInput | Prisma.closing_exam_contentsCreateOrConnectWithoutLessonsInput[]
  upsert?: Prisma.closing_exam_contentsUpsertWithWhereUniqueWithoutLessonsInput | Prisma.closing_exam_contentsUpsertWithWhereUniqueWithoutLessonsInput[]
  createMany?: Prisma.closing_exam_contentsCreateManyLessonsInputEnvelope
  set?: Prisma.closing_exam_contentsWhereUniqueInput | Prisma.closing_exam_contentsWhereUniqueInput[]
  disconnect?: Prisma.closing_exam_contentsWhereUniqueInput | Prisma.closing_exam_contentsWhereUniqueInput[]
  delete?: Prisma.closing_exam_contentsWhereUniqueInput | Prisma.closing_exam_contentsWhereUniqueInput[]
  connect?: Prisma.closing_exam_contentsWhereUniqueInput | Prisma.closing_exam_contentsWhereUniqueInput[]
  update?: Prisma.closing_exam_contentsUpdateWithWhereUniqueWithoutLessonsInput | Prisma.closing_exam_contentsUpdateWithWhereUniqueWithoutLessonsInput[]
  updateMany?: Prisma.closing_exam_contentsUpdateManyWithWhereWithoutLessonsInput | Prisma.closing_exam_contentsUpdateManyWithWhereWithoutLessonsInput[]
  deleteMany?: Prisma.closing_exam_contentsScalarWhereInput | Prisma.closing_exam_contentsScalarWhereInput[]
}

export type closing_exam_contentsUncheckedUpdateManyWithoutLessonsNestedInput = {
  create?: Prisma.XOR<Prisma.closing_exam_contentsCreateWithoutLessonsInput, Prisma.closing_exam_contentsUncheckedCreateWithoutLessonsInput> | Prisma.closing_exam_contentsCreateWithoutLessonsInput[] | Prisma.closing_exam_contentsUncheckedCreateWithoutLessonsInput[]
  connectOrCreate?: Prisma.closing_exam_contentsCreateOrConnectWithoutLessonsInput | Prisma.closing_exam_contentsCreateOrConnectWithoutLessonsInput[]
  upsert?: Prisma.closing_exam_contentsUpsertWithWhereUniqueWithoutLessonsInput | Prisma.closing_exam_contentsUpsertWithWhereUniqueWithoutLessonsInput[]
  createMany?: Prisma.closing_exam_contentsCreateManyLessonsInputEnvelope
  set?: Prisma.closing_exam_contentsWhereUniqueInput | Prisma.closing_exam_contentsWhereUniqueInput[]
  disconnect?: Prisma.closing_exam_contentsWhereUniqueInput | Prisma.closing_exam_contentsWhereUniqueInput[]
  delete?: Prisma.closing_exam_contentsWhereUniqueInput | Prisma.closing_exam_contentsWhereUniqueInput[]
  connect?: Prisma.closing_exam_contentsWhereUniqueInput | Prisma.closing_exam_contentsWhereUniqueInput[]
  update?: Prisma.closing_exam_contentsUpdateWithWhereUniqueWithoutLessonsInput | Prisma.closing_exam_contentsUpdateWithWhereUniqueWithoutLessonsInput[]
  updateMany?: Prisma.closing_exam_contentsUpdateManyWithWhereWithoutLessonsInput | Prisma.closing_exam_contentsUpdateManyWithWhereWithoutLessonsInput[]
  deleteMany?: Prisma.closing_exam_contentsScalarWhereInput | Prisma.closing_exam_contentsScalarWhereInput[]
}

export type closing_exam_contentsCreateWithoutLessonsInput = {
  title: string
  description?: string | null
  time_limit?: number
  question: string
  correct_answer: string
  option_b: string
  option_c: string
  option_d?: string | null
  passing_score?: number
  difficulty_level?: string
  question_order?: number
  points_value?: number
  feedback_correct?: string | null
  feedback_incorrect?: string | null
}

export type closing_exam_contentsUncheckedCreateWithoutLessonsInput = {
  id?: number
  title: string
  description?: string | null
  time_limit?: number
  question: string
  correct_answer: string
  option_b: string
  option_c: string
  option_d?: string | null
  passing_score?: number
  difficulty_level?: string
  question_order?: number
  points_value?: number
  feedback_correct?: string | null
  feedback_incorrect?: string | null
}

export type closing_exam_contentsCreateOrConnectWithoutLessonsInput = {
  where: Prisma.closing_exam_contentsWhereUniqueInput
  create: Prisma.XOR<Prisma.closing_exam_contentsCreateWithoutLessonsInput, Prisma.closing_exam_contentsUncheckedCreateWithoutLessonsInput>
}

export type closing_exam_contentsCreateManyLessonsInputEnvelope = {
  data: Prisma.closing_exam_contentsCreateManyLessonsInput | Prisma.closing_exam_contentsCreateManyLessonsInput[]
  skipDuplicates?: boolean
}

export type closing_exam_contentsUpsertWithWhereUniqueWithoutLessonsInput = {
  where: Prisma.closing_exam_contentsWhereUniqueInput
  update: Prisma.XOR<Prisma.closing_exam_contentsUpdateWithoutLessonsInput, Prisma.closing_exam_contentsUncheckedUpdateWithoutLessonsInput>
  create: Prisma.XOR<Prisma.closing_exam_contentsCreateWithoutLessonsInput, Prisma.closing_exam_contentsUncheckedCreateWithoutLessonsInput>
}

export type closing_exam_contentsUpdateWithWhereUniqueWithoutLessonsInput = {
  where: Prisma.closing_exam_contentsWhereUniqueInput
  data: Prisma.XOR<Prisma.closing_exam_contentsUpdateWithoutLessonsInput, Prisma.closing_exam_contentsUncheckedUpdateWithoutLessonsInput>
}

export type closing_exam_contentsUpdateManyWithWhereWithoutLessonsInput = {
  where: Prisma.closing_exam_contentsScalarWhereInput
  data: Prisma.XOR<Prisma.closing_exam_contentsUpdateManyMutationInput, Prisma.closing_exam_contentsUncheckedUpdateManyWithoutLessonsInput>
}

export type closing_exam_contentsScalarWhereInput = {
  AND?: Prisma.closing_exam_contentsScalarWhereInput | Prisma.closing_exam_contentsScalarWhereInput[]
  OR?: Prisma.closing_exam_contentsScalarWhereInput[]
  NOT?: Prisma.closing_exam_contentsScalarWhereInput | Prisma.closing_exam_contentsScalarWhereInput[]
  id?: Prisma.IntFilter<"closing_exam_contents"> | number
  lesson_id?: Prisma.IntFilter<"closing_exam_contents"> | number
  title?: Prisma.StringFilter<"closing_exam_contents"> | string
  description?: Prisma.StringNullableFilter<"closing_exam_contents"> | string | null
  time_limit?: Prisma.IntFilter<"closing_exam_contents"> | number
  question?: Prisma.StringFilter<"closing_exam_contents"> | string
  correct_answer?: Prisma.StringFilter<"closing_exam_contents"> | string
  option_b?: Prisma.StringFilter<"closing_exam_contents"> | string
  option_c?: Prisma.StringFilter<"closing_exam_contents"> | string
  option_d?: Prisma.StringNullableFilter<"closing_exam_contents"> | string | null
  passing_score?: Prisma.IntFilter<"closing_exam_contents"> | number
  difficulty_level?: Prisma.StringFilter<"closing_exam_contents"> | string
  question_order?: Prisma.IntFilter<"closing_exam_contents"> | number
  points_value?: Prisma.IntFilter<"closing_exam_contents"> | number
  feedback_correct?: Prisma.StringNullableFilter<"closing_exam_contents"> | string | null
  feedback_incorrect?: Prisma.StringNullableFilter<"closing_exam_contents"> | string | null
}

export type closing_exam_contentsCreateManyLessonsInput = {
  id?: number
  title: string
  description?: string | null
  time_limit?: number
  question: string
  correct_answer: string
  option_b: string
  option_c: string
  option_d?: string | null
  passing_score?: number
  difficulty_level?: string
  question_order?: number
  points_value?: number
  feedback_correct?: string | null
  feedback_incorrect?: string | null
}

export type closing_exam_contentsUpdateWithoutLessonsInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  time_limit?: Prisma.IntFieldUpdateOperationsInput | number
  question?: Prisma.StringFieldUpdateOperationsInput | string
  correct_answer?: Prisma.StringFieldUpdateOperationsInput | string
  option_b?: Prisma.StringFieldUpdateOperationsInput | string
  option_c?: Prisma.StringFieldUpdateOperationsInput | string
  option_d?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  passing_score?: Prisma.IntFieldUpdateOperationsInput | number
  difficulty_level?: Prisma.StringFieldUpdateOperationsInput | string
  question_order?: Prisma.IntFieldUpdateOperationsInput | number
  points_value?: Prisma.IntFieldUpdateOperationsInput | number
  feedback_correct?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  feedback_incorrect?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type closing_exam_contentsUncheckedUpdateWithoutLessonsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  time_limit?: Prisma.IntFieldUpdateOperationsInput | number
  question?: Prisma.StringFieldUpdateOperationsInput | string
  correct_answer?: Prisma.StringFieldUpdateOperationsInput | string
  option_b?: Prisma.StringFieldUpdateOperationsInput | string
  option_c?: Prisma.StringFieldUpdateOperationsInput | string
  option_d?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  passing_score?: Prisma.IntFieldUpdateOperationsInput | number
  difficulty_level?: Prisma.StringFieldUpdateOperationsInput | string
  question_order?: Prisma.IntFieldUpdateOperationsInput | number
  points_value?: Prisma.IntFieldUpdateOperationsInput | number
  feedback_correct?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  feedback_incorrect?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type closing_exam_contentsUncheckedUpdateManyWithoutLessonsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  time_limit?: Prisma.IntFieldUpdateOperationsInput | number
  question?: Prisma.StringFieldUpdateOperationsInput | string
  correct_answer?: Prisma.StringFieldUpdateOperationsInput | string
  option_b?: Prisma.StringFieldUpdateOperationsInput | string
  option_c?: Prisma.StringFieldUpdateOperationsInput | string
  option_d?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  passing_score?: Prisma.IntFieldUpdateOperationsInput | number
  difficulty_level?: Prisma.StringFieldUpdateOperationsInput | string
  question_order?: Prisma.IntFieldUpdateOperationsInput | number
  points_value?: Prisma.IntFieldUpdateOperationsInput | number
  feedback_correct?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  feedback_incorrect?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}



export type closing_exam_contentsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  lesson_id?: boolean
  title?: boolean
  description?: boolean
  time_limit?: boolean
  question?: boolean
  correct_answer?: boolean
  option_b?: boolean
  option_c?: boolean
  option_d?: boolean
  passing_score?: boolean
  difficulty_level?: boolean
  question_order?: boolean
  points_value?: boolean
  feedback_correct?: boolean
  feedback_incorrect?: boolean
  lessons?: boolean | Prisma.lessonsDefaultArgs<ExtArgs>
}, ExtArgs["result"]["closing_exam_contents"]>

export type closing_exam_contentsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  lesson_id?: boolean
  title?: boolean
  description?: boolean
  time_limit?: boolean
  question?: boolean
  correct_answer?: boolean
  option_b?: boolean
  option_c?: boolean
  option_d?: boolean
  passing_score?: boolean
  difficulty_level?: boolean
  question_order?: boolean
  points_value?: boolean
  feedback_correct?: boolean
  feedback_incorrect?: boolean
  lessons?: boolean | Prisma.lessonsDefaultArgs<ExtArgs>
}, ExtArgs["result"]["closing_exam_contents"]>

export type closing_exam_contentsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  lesson_id?: boolean
  title?: boolean
  description?: boolean
  time_limit?: boolean
  question?: boolean
  correct_answer?: boolean
  option_b?: boolean
  option_c?: boolean
  option_d?: boolean
  passing_score?: boolean
  difficulty_level?: boolean
  question_order?: boolean
  points_value?: boolean
  feedback_correct?: boolean
  feedback_incorrect?: boolean
  lessons?: boolean | Prisma.lessonsDefaultArgs<ExtArgs>
}, ExtArgs["result"]["closing_exam_contents"]>

export type closing_exam_contentsSelectScalar = {
  id?: boolean
  lesson_id?: boolean
  title?: boolean
  description?: boolean
  time_limit?: boolean
  question?: boolean
  correct_answer?: boolean
  option_b?: boolean
  option_c?: boolean
  option_d?: boolean
  passing_score?: boolean
  difficulty_level?: boolean
  question_order?: boolean
  points_value?: boolean
  feedback_correct?: boolean
  feedback_incorrect?: boolean
}

export type closing_exam_contentsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "lesson_id" | "title" | "description" | "time_limit" | "question" | "correct_answer" | "option_b" | "option_c" | "option_d" | "passing_score" | "difficulty_level" | "question_order" | "points_value" | "feedback_correct" | "feedback_incorrect", ExtArgs["result"]["closing_exam_contents"]>
export type closing_exam_contentsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  lessons?: boolean | Prisma.lessonsDefaultArgs<ExtArgs>
}
export type closing_exam_contentsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  lessons?: boolean | Prisma.lessonsDefaultArgs<ExtArgs>
}
export type closing_exam_contentsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  lessons?: boolean | Prisma.lessonsDefaultArgs<ExtArgs>
}

export type $closing_exam_contentsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "closing_exam_contents"
  objects: {
    lessons: Prisma.$lessonsPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    lesson_id: number
    /**
     * Exam title
     */
    title: string
    /**
     * Exam description
     */
    description: string | null
    /**
     * Time limit in seconds for entire exam
     */
    time_limit: number
    /**
     * Question or prompt
     */
    question: string
    /**
     * Correct answer option
     */
    correct_answer: string
    /**
     * Alternative answer B
     */
    option_b: string
    /**
     * Alternative answer C
     */
    option_c: string
    /**
     * Optional alternative answer D
     */
    option_d: string | null
    /**
     * Passing score percentage
     */
    passing_score: number
    /**
     * Difficulty level: beginner, intermediate, advanced
     */
    difficulty_level: string
    /**
     * Question order in exam
     */
    question_order: number
    /**
     * Points value for this question
     */
    points_value: number
    /**
     * Feedback for correct answer
     */
    feedback_correct: string | null
    /**
     * Feedback for incorrect answers
     */
    feedback_incorrect: string | null
  }, ExtArgs["result"]["closing_exam_contents"]>
  composites: {}
}

export type closing_exam_contentsGetPayload<S extends boolean | null | undefined | closing_exam_contentsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$closing_exam_contentsPayload, S>

export type closing_exam_contentsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<closing_exam_contentsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Closing_exam_contentsCountAggregateInputType | true
  }

export interface closing_exam_contentsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['closing_exam_contents'], meta: { name: 'closing_exam_contents' } }
  /**
   * Find zero or one Closing_exam_contents that matches the filter.
   * @param {closing_exam_contentsFindUniqueArgs} args - Arguments to find a Closing_exam_contents
   * @example
   * // Get one Closing_exam_contents
   * const closing_exam_contents = await prisma.closing_exam_contents.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends closing_exam_contentsFindUniqueArgs>(args: Prisma.SelectSubset<T, closing_exam_contentsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__closing_exam_contentsClient<runtime.Types.Result.GetResult<Prisma.$closing_exam_contentsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Closing_exam_contents that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {closing_exam_contentsFindUniqueOrThrowArgs} args - Arguments to find a Closing_exam_contents
   * @example
   * // Get one Closing_exam_contents
   * const closing_exam_contents = await prisma.closing_exam_contents.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends closing_exam_contentsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, closing_exam_contentsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__closing_exam_contentsClient<runtime.Types.Result.GetResult<Prisma.$closing_exam_contentsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Closing_exam_contents that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {closing_exam_contentsFindFirstArgs} args - Arguments to find a Closing_exam_contents
   * @example
   * // Get one Closing_exam_contents
   * const closing_exam_contents = await prisma.closing_exam_contents.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends closing_exam_contentsFindFirstArgs>(args?: Prisma.SelectSubset<T, closing_exam_contentsFindFirstArgs<ExtArgs>>): Prisma.Prisma__closing_exam_contentsClient<runtime.Types.Result.GetResult<Prisma.$closing_exam_contentsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Closing_exam_contents that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {closing_exam_contentsFindFirstOrThrowArgs} args - Arguments to find a Closing_exam_contents
   * @example
   * // Get one Closing_exam_contents
   * const closing_exam_contents = await prisma.closing_exam_contents.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends closing_exam_contentsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, closing_exam_contentsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__closing_exam_contentsClient<runtime.Types.Result.GetResult<Prisma.$closing_exam_contentsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Closing_exam_contents that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {closing_exam_contentsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Closing_exam_contents
   * const closing_exam_contents = await prisma.closing_exam_contents.findMany()
   * 
   * // Get first 10 Closing_exam_contents
   * const closing_exam_contents = await prisma.closing_exam_contents.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const closing_exam_contentsWithIdOnly = await prisma.closing_exam_contents.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends closing_exam_contentsFindManyArgs>(args?: Prisma.SelectSubset<T, closing_exam_contentsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$closing_exam_contentsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Closing_exam_contents.
   * @param {closing_exam_contentsCreateArgs} args - Arguments to create a Closing_exam_contents.
   * @example
   * // Create one Closing_exam_contents
   * const Closing_exam_contents = await prisma.closing_exam_contents.create({
   *   data: {
   *     // ... data to create a Closing_exam_contents
   *   }
   * })
   * 
   */
  create<T extends closing_exam_contentsCreateArgs>(args: Prisma.SelectSubset<T, closing_exam_contentsCreateArgs<ExtArgs>>): Prisma.Prisma__closing_exam_contentsClient<runtime.Types.Result.GetResult<Prisma.$closing_exam_contentsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Closing_exam_contents.
   * @param {closing_exam_contentsCreateManyArgs} args - Arguments to create many Closing_exam_contents.
   * @example
   * // Create many Closing_exam_contents
   * const closing_exam_contents = await prisma.closing_exam_contents.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends closing_exam_contentsCreateManyArgs>(args?: Prisma.SelectSubset<T, closing_exam_contentsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Closing_exam_contents and returns the data saved in the database.
   * @param {closing_exam_contentsCreateManyAndReturnArgs} args - Arguments to create many Closing_exam_contents.
   * @example
   * // Create many Closing_exam_contents
   * const closing_exam_contents = await prisma.closing_exam_contents.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Closing_exam_contents and only return the `id`
   * const closing_exam_contentsWithIdOnly = await prisma.closing_exam_contents.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends closing_exam_contentsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, closing_exam_contentsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$closing_exam_contentsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Closing_exam_contents.
   * @param {closing_exam_contentsDeleteArgs} args - Arguments to delete one Closing_exam_contents.
   * @example
   * // Delete one Closing_exam_contents
   * const Closing_exam_contents = await prisma.closing_exam_contents.delete({
   *   where: {
   *     // ... filter to delete one Closing_exam_contents
   *   }
   * })
   * 
   */
  delete<T extends closing_exam_contentsDeleteArgs>(args: Prisma.SelectSubset<T, closing_exam_contentsDeleteArgs<ExtArgs>>): Prisma.Prisma__closing_exam_contentsClient<runtime.Types.Result.GetResult<Prisma.$closing_exam_contentsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Closing_exam_contents.
   * @param {closing_exam_contentsUpdateArgs} args - Arguments to update one Closing_exam_contents.
   * @example
   * // Update one Closing_exam_contents
   * const closing_exam_contents = await prisma.closing_exam_contents.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends closing_exam_contentsUpdateArgs>(args: Prisma.SelectSubset<T, closing_exam_contentsUpdateArgs<ExtArgs>>): Prisma.Prisma__closing_exam_contentsClient<runtime.Types.Result.GetResult<Prisma.$closing_exam_contentsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Closing_exam_contents.
   * @param {closing_exam_contentsDeleteManyArgs} args - Arguments to filter Closing_exam_contents to delete.
   * @example
   * // Delete a few Closing_exam_contents
   * const { count } = await prisma.closing_exam_contents.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends closing_exam_contentsDeleteManyArgs>(args?: Prisma.SelectSubset<T, closing_exam_contentsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Closing_exam_contents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {closing_exam_contentsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Closing_exam_contents
   * const closing_exam_contents = await prisma.closing_exam_contents.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends closing_exam_contentsUpdateManyArgs>(args: Prisma.SelectSubset<T, closing_exam_contentsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Closing_exam_contents and returns the data updated in the database.
   * @param {closing_exam_contentsUpdateManyAndReturnArgs} args - Arguments to update many Closing_exam_contents.
   * @example
   * // Update many Closing_exam_contents
   * const closing_exam_contents = await prisma.closing_exam_contents.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Closing_exam_contents and only return the `id`
   * const closing_exam_contentsWithIdOnly = await prisma.closing_exam_contents.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends closing_exam_contentsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, closing_exam_contentsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$closing_exam_contentsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Closing_exam_contents.
   * @param {closing_exam_contentsUpsertArgs} args - Arguments to update or create a Closing_exam_contents.
   * @example
   * // Update or create a Closing_exam_contents
   * const closing_exam_contents = await prisma.closing_exam_contents.upsert({
   *   create: {
   *     // ... data to create a Closing_exam_contents
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Closing_exam_contents we want to update
   *   }
   * })
   */
  upsert<T extends closing_exam_contentsUpsertArgs>(args: Prisma.SelectSubset<T, closing_exam_contentsUpsertArgs<ExtArgs>>): Prisma.Prisma__closing_exam_contentsClient<runtime.Types.Result.GetResult<Prisma.$closing_exam_contentsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Closing_exam_contents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {closing_exam_contentsCountArgs} args - Arguments to filter Closing_exam_contents to count.
   * @example
   * // Count the number of Closing_exam_contents
   * const count = await prisma.closing_exam_contents.count({
   *   where: {
   *     // ... the filter for the Closing_exam_contents we want to count
   *   }
   * })
  **/
  count<T extends closing_exam_contentsCountArgs>(
    args?: Prisma.Subset<T, closing_exam_contentsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Closing_exam_contentsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Closing_exam_contents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Closing_exam_contentsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Closing_exam_contentsAggregateArgs>(args: Prisma.Subset<T, Closing_exam_contentsAggregateArgs>): Prisma.PrismaPromise<GetClosing_exam_contentsAggregateType<T>>

  /**
   * Group by Closing_exam_contents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {closing_exam_contentsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends closing_exam_contentsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: closing_exam_contentsGroupByArgs['orderBy'] }
      : { orderBy?: closing_exam_contentsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, closing_exam_contentsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetClosing_exam_contentsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the closing_exam_contents model
 */
readonly fields: closing_exam_contentsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for closing_exam_contents.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__closing_exam_contentsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  lessons<T extends Prisma.lessonsDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.lessonsDefaultArgs<ExtArgs>>): Prisma.Prisma__lessonsClient<runtime.Types.Result.GetResult<Prisma.$lessonsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the closing_exam_contents model
 */
export interface closing_exam_contentsFieldRefs {
  readonly id: Prisma.FieldRef<"closing_exam_contents", 'Int'>
  readonly lesson_id: Prisma.FieldRef<"closing_exam_contents", 'Int'>
  readonly title: Prisma.FieldRef<"closing_exam_contents", 'String'>
  readonly description: Prisma.FieldRef<"closing_exam_contents", 'String'>
  readonly time_limit: Prisma.FieldRef<"closing_exam_contents", 'Int'>
  readonly question: Prisma.FieldRef<"closing_exam_contents", 'String'>
  readonly correct_answer: Prisma.FieldRef<"closing_exam_contents", 'String'>
  readonly option_b: Prisma.FieldRef<"closing_exam_contents", 'String'>
  readonly option_c: Prisma.FieldRef<"closing_exam_contents", 'String'>
  readonly option_d: Prisma.FieldRef<"closing_exam_contents", 'String'>
  readonly passing_score: Prisma.FieldRef<"closing_exam_contents", 'Int'>
  readonly difficulty_level: Prisma.FieldRef<"closing_exam_contents", 'String'>
  readonly question_order: Prisma.FieldRef<"closing_exam_contents", 'Int'>
  readonly points_value: Prisma.FieldRef<"closing_exam_contents", 'Int'>
  readonly feedback_correct: Prisma.FieldRef<"closing_exam_contents", 'String'>
  readonly feedback_incorrect: Prisma.FieldRef<"closing_exam_contents", 'String'>
}
    

// Custom InputTypes
/**
 * closing_exam_contents findUnique
 */
export type closing_exam_contentsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the closing_exam_contents
   */
  select?: Prisma.closing_exam_contentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the closing_exam_contents
   */
  omit?: Prisma.closing_exam_contentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.closing_exam_contentsInclude<ExtArgs> | null
  /**
   * Filter, which closing_exam_contents to fetch.
   */
  where: Prisma.closing_exam_contentsWhereUniqueInput
}

/**
 * closing_exam_contents findUniqueOrThrow
 */
export type closing_exam_contentsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the closing_exam_contents
   */
  select?: Prisma.closing_exam_contentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the closing_exam_contents
   */
  omit?: Prisma.closing_exam_contentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.closing_exam_contentsInclude<ExtArgs> | null
  /**
   * Filter, which closing_exam_contents to fetch.
   */
  where: Prisma.closing_exam_contentsWhereUniqueInput
}

/**
 * closing_exam_contents findFirst
 */
export type closing_exam_contentsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the closing_exam_contents
   */
  select?: Prisma.closing_exam_contentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the closing_exam_contents
   */
  omit?: Prisma.closing_exam_contentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.closing_exam_contentsInclude<ExtArgs> | null
  /**
   * Filter, which closing_exam_contents to fetch.
   */
  where?: Prisma.closing_exam_contentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of closing_exam_contents to fetch.
   */
  orderBy?: Prisma.closing_exam_contentsOrderByWithRelationInput | Prisma.closing_exam_contentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for closing_exam_contents.
   */
  cursor?: Prisma.closing_exam_contentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` closing_exam_contents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` closing_exam_contents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of closing_exam_contents.
   */
  distinct?: Prisma.Closing_exam_contentsScalarFieldEnum | Prisma.Closing_exam_contentsScalarFieldEnum[]
}

/**
 * closing_exam_contents findFirstOrThrow
 */
export type closing_exam_contentsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the closing_exam_contents
   */
  select?: Prisma.closing_exam_contentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the closing_exam_contents
   */
  omit?: Prisma.closing_exam_contentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.closing_exam_contentsInclude<ExtArgs> | null
  /**
   * Filter, which closing_exam_contents to fetch.
   */
  where?: Prisma.closing_exam_contentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of closing_exam_contents to fetch.
   */
  orderBy?: Prisma.closing_exam_contentsOrderByWithRelationInput | Prisma.closing_exam_contentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for closing_exam_contents.
   */
  cursor?: Prisma.closing_exam_contentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` closing_exam_contents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` closing_exam_contents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of closing_exam_contents.
   */
  distinct?: Prisma.Closing_exam_contentsScalarFieldEnum | Prisma.Closing_exam_contentsScalarFieldEnum[]
}

/**
 * closing_exam_contents findMany
 */
export type closing_exam_contentsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the closing_exam_contents
   */
  select?: Prisma.closing_exam_contentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the closing_exam_contents
   */
  omit?: Prisma.closing_exam_contentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.closing_exam_contentsInclude<ExtArgs> | null
  /**
   * Filter, which closing_exam_contents to fetch.
   */
  where?: Prisma.closing_exam_contentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of closing_exam_contents to fetch.
   */
  orderBy?: Prisma.closing_exam_contentsOrderByWithRelationInput | Prisma.closing_exam_contentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing closing_exam_contents.
   */
  cursor?: Prisma.closing_exam_contentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` closing_exam_contents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` closing_exam_contents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of closing_exam_contents.
   */
  distinct?: Prisma.Closing_exam_contentsScalarFieldEnum | Prisma.Closing_exam_contentsScalarFieldEnum[]
}

/**
 * closing_exam_contents create
 */
export type closing_exam_contentsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the closing_exam_contents
   */
  select?: Prisma.closing_exam_contentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the closing_exam_contents
   */
  omit?: Prisma.closing_exam_contentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.closing_exam_contentsInclude<ExtArgs> | null
  /**
   * The data needed to create a closing_exam_contents.
   */
  data: Prisma.XOR<Prisma.closing_exam_contentsCreateInput, Prisma.closing_exam_contentsUncheckedCreateInput>
}

/**
 * closing_exam_contents createMany
 */
export type closing_exam_contentsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many closing_exam_contents.
   */
  data: Prisma.closing_exam_contentsCreateManyInput | Prisma.closing_exam_contentsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * closing_exam_contents createManyAndReturn
 */
export type closing_exam_contentsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the closing_exam_contents
   */
  select?: Prisma.closing_exam_contentsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the closing_exam_contents
   */
  omit?: Prisma.closing_exam_contentsOmit<ExtArgs> | null
  /**
   * The data used to create many closing_exam_contents.
   */
  data: Prisma.closing_exam_contentsCreateManyInput | Prisma.closing_exam_contentsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.closing_exam_contentsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * closing_exam_contents update
 */
export type closing_exam_contentsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the closing_exam_contents
   */
  select?: Prisma.closing_exam_contentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the closing_exam_contents
   */
  omit?: Prisma.closing_exam_contentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.closing_exam_contentsInclude<ExtArgs> | null
  /**
   * The data needed to update a closing_exam_contents.
   */
  data: Prisma.XOR<Prisma.closing_exam_contentsUpdateInput, Prisma.closing_exam_contentsUncheckedUpdateInput>
  /**
   * Choose, which closing_exam_contents to update.
   */
  where: Prisma.closing_exam_contentsWhereUniqueInput
}

/**
 * closing_exam_contents updateMany
 */
export type closing_exam_contentsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update closing_exam_contents.
   */
  data: Prisma.XOR<Prisma.closing_exam_contentsUpdateManyMutationInput, Prisma.closing_exam_contentsUncheckedUpdateManyInput>
  /**
   * Filter which closing_exam_contents to update
   */
  where?: Prisma.closing_exam_contentsWhereInput
  /**
   * Limit how many closing_exam_contents to update.
   */
  limit?: number
}

/**
 * closing_exam_contents updateManyAndReturn
 */
export type closing_exam_contentsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the closing_exam_contents
   */
  select?: Prisma.closing_exam_contentsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the closing_exam_contents
   */
  omit?: Prisma.closing_exam_contentsOmit<ExtArgs> | null
  /**
   * The data used to update closing_exam_contents.
   */
  data: Prisma.XOR<Prisma.closing_exam_contentsUpdateManyMutationInput, Prisma.closing_exam_contentsUncheckedUpdateManyInput>
  /**
   * Filter which closing_exam_contents to update
   */
  where?: Prisma.closing_exam_contentsWhereInput
  /**
   * Limit how many closing_exam_contents to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.closing_exam_contentsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * closing_exam_contents upsert
 */
export type closing_exam_contentsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the closing_exam_contents
   */
  select?: Prisma.closing_exam_contentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the closing_exam_contents
   */
  omit?: Prisma.closing_exam_contentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.closing_exam_contentsInclude<ExtArgs> | null
  /**
   * The filter to search for the closing_exam_contents to update in case it exists.
   */
  where: Prisma.closing_exam_contentsWhereUniqueInput
  /**
   * In case the closing_exam_contents found by the `where` argument doesn't exist, create a new closing_exam_contents with this data.
   */
  create: Prisma.XOR<Prisma.closing_exam_contentsCreateInput, Prisma.closing_exam_contentsUncheckedCreateInput>
  /**
   * In case the closing_exam_contents was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.closing_exam_contentsUpdateInput, Prisma.closing_exam_contentsUncheckedUpdateInput>
}

/**
 * closing_exam_contents delete
 */
export type closing_exam_contentsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the closing_exam_contents
   */
  select?: Prisma.closing_exam_contentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the closing_exam_contents
   */
  omit?: Prisma.closing_exam_contentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.closing_exam_contentsInclude<ExtArgs> | null
  /**
   * Filter which closing_exam_contents to delete.
   */
  where: Prisma.closing_exam_contentsWhereUniqueInput
}

/**
 * closing_exam_contents deleteMany
 */
export type closing_exam_contentsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which closing_exam_contents to delete
   */
  where?: Prisma.closing_exam_contentsWhereInput
  /**
   * Limit how many closing_exam_contents to delete.
   */
  limit?: number
}

/**
 * closing_exam_contents without action
 */
export type closing_exam_contentsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the closing_exam_contents
   */
  select?: Prisma.closing_exam_contentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the closing_exam_contents
   */
  omit?: Prisma.closing_exam_contentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.closing_exam_contentsInclude<ExtArgs> | null
}
