
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `courses` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model courses
 * Represents a language course (e.g., "English", "Spanish").
 * Primary key is the course slug for URL-friendly identifiers.
 * Topics are organized within courses for curriculum structure.
 */
export type coursesModel = runtime.Types.Result.DefaultSelection<Prisma.$coursesPayload>

export type AggregateCourses = {
  _count: CoursesCountAggregateOutputType | null
  _avg: CoursesAvgAggregateOutputType | null
  _sum: CoursesSumAggregateOutputType | null
  _min: CoursesMinAggregateOutputType | null
  _max: CoursesMaxAggregateOutputType | null
}

export type CoursesAvgAggregateOutputType = {
  id: number | null
}

export type CoursesSumAggregateOutputType = {
  id: number | null
}

export type CoursesMinAggregateOutputType = {
  slug: string | null
  id: number | null
  title: string | null
  description: string | null
}

export type CoursesMaxAggregateOutputType = {
  slug: string | null
  id: number | null
  title: string | null
  description: string | null
}

export type CoursesCountAggregateOutputType = {
  slug: number
  id: number
  title: number
  description: number
  _all: number
}


export type CoursesAvgAggregateInputType = {
  id?: true
}

export type CoursesSumAggregateInputType = {
  id?: true
}

export type CoursesMinAggregateInputType = {
  slug?: true
  id?: true
  title?: true
  description?: true
}

export type CoursesMaxAggregateInputType = {
  slug?: true
  id?: true
  title?: true
  description?: true
}

export type CoursesCountAggregateInputType = {
  slug?: true
  id?: true
  title?: true
  description?: true
  _all?: true
}

export type CoursesAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which courses to aggregate.
   */
  where?: Prisma.coursesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of courses to fetch.
   */
  orderBy?: Prisma.coursesOrderByWithRelationInput | Prisma.coursesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.coursesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` courses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` courses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned courses
  **/
  _count?: true | CoursesCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: CoursesAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: CoursesSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CoursesMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CoursesMaxAggregateInputType
}

export type GetCoursesAggregateType<T extends CoursesAggregateArgs> = {
      [P in keyof T & keyof AggregateCourses]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCourses[P]>
    : Prisma.GetScalarType<T[P], AggregateCourses[P]>
}




export type coursesGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.coursesWhereInput
  orderBy?: Prisma.coursesOrderByWithAggregationInput | Prisma.coursesOrderByWithAggregationInput[]
  by: Prisma.CoursesScalarFieldEnum[] | Prisma.CoursesScalarFieldEnum
  having?: Prisma.coursesScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CoursesCountAggregateInputType | true
  _avg?: CoursesAvgAggregateInputType
  _sum?: CoursesSumAggregateInputType
  _min?: CoursesMinAggregateInputType
  _max?: CoursesMaxAggregateInputType
}

export type CoursesGroupByOutputType = {
  slug: string
  id: number
  title: string
  description: string | null
  _count: CoursesCountAggregateOutputType | null
  _avg: CoursesAvgAggregateOutputType | null
  _sum: CoursesSumAggregateOutputType | null
  _min: CoursesMinAggregateOutputType | null
  _max: CoursesMaxAggregateOutputType | null
}

export type GetCoursesGroupByPayload<T extends coursesGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CoursesGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CoursesGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CoursesGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CoursesGroupByOutputType[P]>
      }
    >
  >



export type coursesWhereInput = {
  AND?: Prisma.coursesWhereInput | Prisma.coursesWhereInput[]
  OR?: Prisma.coursesWhereInput[]
  NOT?: Prisma.coursesWhereInput | Prisma.coursesWhereInput[]
  slug?: Prisma.StringFilter<"courses"> | string
  id?: Prisma.IntFilter<"courses"> | number
  title?: Prisma.StringFilter<"courses"> | string
  description?: Prisma.StringNullableFilter<"courses"> | string | null
  topics?: Prisma.TopicsListRelationFilter
}

export type coursesOrderByWithRelationInput = {
  slug?: Prisma.SortOrder
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  topics?: Prisma.topicsOrderByRelationAggregateInput
}

export type coursesWhereUniqueInput = Prisma.AtLeast<{
  slug?: string
  AND?: Prisma.coursesWhereInput | Prisma.coursesWhereInput[]
  OR?: Prisma.coursesWhereInput[]
  NOT?: Prisma.coursesWhereInput | Prisma.coursesWhereInput[]
  id?: Prisma.IntFilter<"courses"> | number
  title?: Prisma.StringFilter<"courses"> | string
  description?: Prisma.StringNullableFilter<"courses"> | string | null
  topics?: Prisma.TopicsListRelationFilter
}, "slug">

export type coursesOrderByWithAggregationInput = {
  slug?: Prisma.SortOrder
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.coursesCountOrderByAggregateInput
  _avg?: Prisma.coursesAvgOrderByAggregateInput
  _max?: Prisma.coursesMaxOrderByAggregateInput
  _min?: Prisma.coursesMinOrderByAggregateInput
  _sum?: Prisma.coursesSumOrderByAggregateInput
}

export type coursesScalarWhereWithAggregatesInput = {
  AND?: Prisma.coursesScalarWhereWithAggregatesInput | Prisma.coursesScalarWhereWithAggregatesInput[]
  OR?: Prisma.coursesScalarWhereWithAggregatesInput[]
  NOT?: Prisma.coursesScalarWhereWithAggregatesInput | Prisma.coursesScalarWhereWithAggregatesInput[]
  slug?: Prisma.StringWithAggregatesFilter<"courses"> | string
  id?: Prisma.IntWithAggregatesFilter<"courses"> | number
  title?: Prisma.StringWithAggregatesFilter<"courses"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"courses"> | string | null
}

export type coursesCreateInput = {
  slug: string
  id?: number
  title: string
  description?: string | null
  topics?: Prisma.topicsCreateNestedManyWithoutCoursesInput
}

export type coursesUncheckedCreateInput = {
  slug: string
  id?: number
  title: string
  description?: string | null
  topics?: Prisma.topicsUncheckedCreateNestedManyWithoutCoursesInput
}

export type coursesUpdateInput = {
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  topics?: Prisma.topicsUpdateManyWithoutCoursesNestedInput
}

export type coursesUncheckedUpdateInput = {
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  topics?: Prisma.topicsUncheckedUpdateManyWithoutCoursesNestedInput
}

export type coursesCreateManyInput = {
  slug: string
  id?: number
  title: string
  description?: string | null
}

export type coursesUpdateManyMutationInput = {
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type coursesUncheckedUpdateManyInput = {
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type coursesCountOrderByAggregateInput = {
  slug?: Prisma.SortOrder
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
}

export type coursesAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type coursesMaxOrderByAggregateInput = {
  slug?: Prisma.SortOrder
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
}

export type coursesMinOrderByAggregateInput = {
  slug?: Prisma.SortOrder
  id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
}

export type coursesSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type CoursesScalarRelationFilter = {
  is?: Prisma.coursesWhereInput
  isNot?: Prisma.coursesWhereInput
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type coursesCreateNestedOneWithoutTopicsInput = {
  create?: Prisma.XOR<Prisma.coursesCreateWithoutTopicsInput, Prisma.coursesUncheckedCreateWithoutTopicsInput>
  connectOrCreate?: Prisma.coursesCreateOrConnectWithoutTopicsInput
  connect?: Prisma.coursesWhereUniqueInput
}

export type coursesUpdateOneRequiredWithoutTopicsNestedInput = {
  create?: Prisma.XOR<Prisma.coursesCreateWithoutTopicsInput, Prisma.coursesUncheckedCreateWithoutTopicsInput>
  connectOrCreate?: Prisma.coursesCreateOrConnectWithoutTopicsInput
  upsert?: Prisma.coursesUpsertWithoutTopicsInput
  connect?: Prisma.coursesWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.coursesUpdateToOneWithWhereWithoutTopicsInput, Prisma.coursesUpdateWithoutTopicsInput>, Prisma.coursesUncheckedUpdateWithoutTopicsInput>
}

export type coursesCreateWithoutTopicsInput = {
  slug: string
  id?: number
  title: string
  description?: string | null
}

export type coursesUncheckedCreateWithoutTopicsInput = {
  slug: string
  id?: number
  title: string
  description?: string | null
}

export type coursesCreateOrConnectWithoutTopicsInput = {
  where: Prisma.coursesWhereUniqueInput
  create: Prisma.XOR<Prisma.coursesCreateWithoutTopicsInput, Prisma.coursesUncheckedCreateWithoutTopicsInput>
}

export type coursesUpsertWithoutTopicsInput = {
  update: Prisma.XOR<Prisma.coursesUpdateWithoutTopicsInput, Prisma.coursesUncheckedUpdateWithoutTopicsInput>
  create: Prisma.XOR<Prisma.coursesCreateWithoutTopicsInput, Prisma.coursesUncheckedCreateWithoutTopicsInput>
  where?: Prisma.coursesWhereInput
}

export type coursesUpdateToOneWithWhereWithoutTopicsInput = {
  where?: Prisma.coursesWhereInput
  data: Prisma.XOR<Prisma.coursesUpdateWithoutTopicsInput, Prisma.coursesUncheckedUpdateWithoutTopicsInput>
}

export type coursesUpdateWithoutTopicsInput = {
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type coursesUncheckedUpdateWithoutTopicsInput = {
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}


/**
 * Count Type CoursesCountOutputType
 */

export type CoursesCountOutputType = {
  topics: number
}

export type CoursesCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  topics?: boolean | CoursesCountOutputTypeCountTopicsArgs
}

/**
 * CoursesCountOutputType without action
 */
export type CoursesCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CoursesCountOutputType
   */
  select?: Prisma.CoursesCountOutputTypeSelect<ExtArgs> | null
}

/**
 * CoursesCountOutputType without action
 */
export type CoursesCountOutputTypeCountTopicsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.topicsWhereInput
}


export type coursesSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  slug?: boolean
  id?: boolean
  title?: boolean
  description?: boolean
  topics?: boolean | Prisma.courses$topicsArgs<ExtArgs>
  _count?: boolean | Prisma.CoursesCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["courses"]>

export type coursesSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  slug?: boolean
  id?: boolean
  title?: boolean
  description?: boolean
}, ExtArgs["result"]["courses"]>

export type coursesSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  slug?: boolean
  id?: boolean
  title?: boolean
  description?: boolean
}, ExtArgs["result"]["courses"]>

export type coursesSelectScalar = {
  slug?: boolean
  id?: boolean
  title?: boolean
  description?: boolean
}

export type coursesOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"slug" | "id" | "title" | "description", ExtArgs["result"]["courses"]>
export type coursesInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  topics?: boolean | Prisma.courses$topicsArgs<ExtArgs>
  _count?: boolean | Prisma.CoursesCountOutputTypeDefaultArgs<ExtArgs>
}
export type coursesIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type coursesIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $coursesPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "courses"
  objects: {
    topics: Prisma.$topicsPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    slug: string
    id: number
    title: string
    description: string | null
  }, ExtArgs["result"]["courses"]>
  composites: {}
}

export type coursesGetPayload<S extends boolean | null | undefined | coursesDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$coursesPayload, S>

export type coursesCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<coursesFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CoursesCountAggregateInputType | true
  }

export interface coursesDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['courses'], meta: { name: 'courses' } }
  /**
   * Find zero or one Courses that matches the filter.
   * @param {coursesFindUniqueArgs} args - Arguments to find a Courses
   * @example
   * // Get one Courses
   * const courses = await prisma.courses.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends coursesFindUniqueArgs>(args: Prisma.SelectSubset<T, coursesFindUniqueArgs<ExtArgs>>): Prisma.Prisma__coursesClient<runtime.Types.Result.GetResult<Prisma.$coursesPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Courses that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {coursesFindUniqueOrThrowArgs} args - Arguments to find a Courses
   * @example
   * // Get one Courses
   * const courses = await prisma.courses.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends coursesFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, coursesFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__coursesClient<runtime.Types.Result.GetResult<Prisma.$coursesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Courses that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {coursesFindFirstArgs} args - Arguments to find a Courses
   * @example
   * // Get one Courses
   * const courses = await prisma.courses.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends coursesFindFirstArgs>(args?: Prisma.SelectSubset<T, coursesFindFirstArgs<ExtArgs>>): Prisma.Prisma__coursesClient<runtime.Types.Result.GetResult<Prisma.$coursesPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Courses that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {coursesFindFirstOrThrowArgs} args - Arguments to find a Courses
   * @example
   * // Get one Courses
   * const courses = await prisma.courses.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends coursesFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, coursesFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__coursesClient<runtime.Types.Result.GetResult<Prisma.$coursesPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Courses that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {coursesFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Courses
   * const courses = await prisma.courses.findMany()
   * 
   * // Get first 10 Courses
   * const courses = await prisma.courses.findMany({ take: 10 })
   * 
   * // Only select the `slug`
   * const coursesWithSlugOnly = await prisma.courses.findMany({ select: { slug: true } })
   * 
   */
  findMany<T extends coursesFindManyArgs>(args?: Prisma.SelectSubset<T, coursesFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$coursesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Courses.
   * @param {coursesCreateArgs} args - Arguments to create a Courses.
   * @example
   * // Create one Courses
   * const Courses = await prisma.courses.create({
   *   data: {
   *     // ... data to create a Courses
   *   }
   * })
   * 
   */
  create<T extends coursesCreateArgs>(args: Prisma.SelectSubset<T, coursesCreateArgs<ExtArgs>>): Prisma.Prisma__coursesClient<runtime.Types.Result.GetResult<Prisma.$coursesPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Courses.
   * @param {coursesCreateManyArgs} args - Arguments to create many Courses.
   * @example
   * // Create many Courses
   * const courses = await prisma.courses.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends coursesCreateManyArgs>(args?: Prisma.SelectSubset<T, coursesCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Courses and returns the data saved in the database.
   * @param {coursesCreateManyAndReturnArgs} args - Arguments to create many Courses.
   * @example
   * // Create many Courses
   * const courses = await prisma.courses.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Courses and only return the `slug`
   * const coursesWithSlugOnly = await prisma.courses.createManyAndReturn({
   *   select: { slug: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends coursesCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, coursesCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$coursesPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Courses.
   * @param {coursesDeleteArgs} args - Arguments to delete one Courses.
   * @example
   * // Delete one Courses
   * const Courses = await prisma.courses.delete({
   *   where: {
   *     // ... filter to delete one Courses
   *   }
   * })
   * 
   */
  delete<T extends coursesDeleteArgs>(args: Prisma.SelectSubset<T, coursesDeleteArgs<ExtArgs>>): Prisma.Prisma__coursesClient<runtime.Types.Result.GetResult<Prisma.$coursesPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Courses.
   * @param {coursesUpdateArgs} args - Arguments to update one Courses.
   * @example
   * // Update one Courses
   * const courses = await prisma.courses.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends coursesUpdateArgs>(args: Prisma.SelectSubset<T, coursesUpdateArgs<ExtArgs>>): Prisma.Prisma__coursesClient<runtime.Types.Result.GetResult<Prisma.$coursesPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Courses.
   * @param {coursesDeleteManyArgs} args - Arguments to filter Courses to delete.
   * @example
   * // Delete a few Courses
   * const { count } = await prisma.courses.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends coursesDeleteManyArgs>(args?: Prisma.SelectSubset<T, coursesDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Courses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {coursesUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Courses
   * const courses = await prisma.courses.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends coursesUpdateManyArgs>(args: Prisma.SelectSubset<T, coursesUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Courses and returns the data updated in the database.
   * @param {coursesUpdateManyAndReturnArgs} args - Arguments to update many Courses.
   * @example
   * // Update many Courses
   * const courses = await prisma.courses.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Courses and only return the `slug`
   * const coursesWithSlugOnly = await prisma.courses.updateManyAndReturn({
   *   select: { slug: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends coursesUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, coursesUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$coursesPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Courses.
   * @param {coursesUpsertArgs} args - Arguments to update or create a Courses.
   * @example
   * // Update or create a Courses
   * const courses = await prisma.courses.upsert({
   *   create: {
   *     // ... data to create a Courses
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Courses we want to update
   *   }
   * })
   */
  upsert<T extends coursesUpsertArgs>(args: Prisma.SelectSubset<T, coursesUpsertArgs<ExtArgs>>): Prisma.Prisma__coursesClient<runtime.Types.Result.GetResult<Prisma.$coursesPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Courses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {coursesCountArgs} args - Arguments to filter Courses to count.
   * @example
   * // Count the number of Courses
   * const count = await prisma.courses.count({
   *   where: {
   *     // ... the filter for the Courses we want to count
   *   }
   * })
  **/
  count<T extends coursesCountArgs>(
    args?: Prisma.Subset<T, coursesCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CoursesCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Courses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CoursesAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CoursesAggregateArgs>(args: Prisma.Subset<T, CoursesAggregateArgs>): Prisma.PrismaPromise<GetCoursesAggregateType<T>>

  /**
   * Group by Courses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {coursesGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends coursesGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: coursesGroupByArgs['orderBy'] }
      : { orderBy?: coursesGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, coursesGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCoursesGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the courses model
 */
readonly fields: coursesFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for courses.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__coursesClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  topics<T extends Prisma.courses$topicsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.courses$topicsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$topicsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the courses model
 */
export interface coursesFieldRefs {
  readonly slug: Prisma.FieldRef<"courses", 'String'>
  readonly id: Prisma.FieldRef<"courses", 'Int'>
  readonly title: Prisma.FieldRef<"courses", 'String'>
  readonly description: Prisma.FieldRef<"courses", 'String'>
}
    

// Custom InputTypes
/**
 * courses findUnique
 */
export type coursesFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the courses
   */
  select?: Prisma.coursesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the courses
   */
  omit?: Prisma.coursesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.coursesInclude<ExtArgs> | null
  /**
   * Filter, which courses to fetch.
   */
  where: Prisma.coursesWhereUniqueInput
}

/**
 * courses findUniqueOrThrow
 */
export type coursesFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the courses
   */
  select?: Prisma.coursesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the courses
   */
  omit?: Prisma.coursesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.coursesInclude<ExtArgs> | null
  /**
   * Filter, which courses to fetch.
   */
  where: Prisma.coursesWhereUniqueInput
}

/**
 * courses findFirst
 */
export type coursesFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the courses
   */
  select?: Prisma.coursesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the courses
   */
  omit?: Prisma.coursesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.coursesInclude<ExtArgs> | null
  /**
   * Filter, which courses to fetch.
   */
  where?: Prisma.coursesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of courses to fetch.
   */
  orderBy?: Prisma.coursesOrderByWithRelationInput | Prisma.coursesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for courses.
   */
  cursor?: Prisma.coursesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` courses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` courses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of courses.
   */
  distinct?: Prisma.CoursesScalarFieldEnum | Prisma.CoursesScalarFieldEnum[]
}

/**
 * courses findFirstOrThrow
 */
export type coursesFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the courses
   */
  select?: Prisma.coursesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the courses
   */
  omit?: Prisma.coursesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.coursesInclude<ExtArgs> | null
  /**
   * Filter, which courses to fetch.
   */
  where?: Prisma.coursesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of courses to fetch.
   */
  orderBy?: Prisma.coursesOrderByWithRelationInput | Prisma.coursesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for courses.
   */
  cursor?: Prisma.coursesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` courses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` courses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of courses.
   */
  distinct?: Prisma.CoursesScalarFieldEnum | Prisma.CoursesScalarFieldEnum[]
}

/**
 * courses findMany
 */
export type coursesFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the courses
   */
  select?: Prisma.coursesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the courses
   */
  omit?: Prisma.coursesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.coursesInclude<ExtArgs> | null
  /**
   * Filter, which courses to fetch.
   */
  where?: Prisma.coursesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of courses to fetch.
   */
  orderBy?: Prisma.coursesOrderByWithRelationInput | Prisma.coursesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing courses.
   */
  cursor?: Prisma.coursesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` courses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` courses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of courses.
   */
  distinct?: Prisma.CoursesScalarFieldEnum | Prisma.CoursesScalarFieldEnum[]
}

/**
 * courses create
 */
export type coursesCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the courses
   */
  select?: Prisma.coursesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the courses
   */
  omit?: Prisma.coursesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.coursesInclude<ExtArgs> | null
  /**
   * The data needed to create a courses.
   */
  data: Prisma.XOR<Prisma.coursesCreateInput, Prisma.coursesUncheckedCreateInput>
}

/**
 * courses createMany
 */
export type coursesCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many courses.
   */
  data: Prisma.coursesCreateManyInput | Prisma.coursesCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * courses createManyAndReturn
 */
export type coursesCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the courses
   */
  select?: Prisma.coursesSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the courses
   */
  omit?: Prisma.coursesOmit<ExtArgs> | null
  /**
   * The data used to create many courses.
   */
  data: Prisma.coursesCreateManyInput | Prisma.coursesCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * courses update
 */
export type coursesUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the courses
   */
  select?: Prisma.coursesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the courses
   */
  omit?: Prisma.coursesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.coursesInclude<ExtArgs> | null
  /**
   * The data needed to update a courses.
   */
  data: Prisma.XOR<Prisma.coursesUpdateInput, Prisma.coursesUncheckedUpdateInput>
  /**
   * Choose, which courses to update.
   */
  where: Prisma.coursesWhereUniqueInput
}

/**
 * courses updateMany
 */
export type coursesUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update courses.
   */
  data: Prisma.XOR<Prisma.coursesUpdateManyMutationInput, Prisma.coursesUncheckedUpdateManyInput>
  /**
   * Filter which courses to update
   */
  where?: Prisma.coursesWhereInput
  /**
   * Limit how many courses to update.
   */
  limit?: number
}

/**
 * courses updateManyAndReturn
 */
export type coursesUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the courses
   */
  select?: Prisma.coursesSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the courses
   */
  omit?: Prisma.coursesOmit<ExtArgs> | null
  /**
   * The data used to update courses.
   */
  data: Prisma.XOR<Prisma.coursesUpdateManyMutationInput, Prisma.coursesUncheckedUpdateManyInput>
  /**
   * Filter which courses to update
   */
  where?: Prisma.coursesWhereInput
  /**
   * Limit how many courses to update.
   */
  limit?: number
}

/**
 * courses upsert
 */
export type coursesUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the courses
   */
  select?: Prisma.coursesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the courses
   */
  omit?: Prisma.coursesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.coursesInclude<ExtArgs> | null
  /**
   * The filter to search for the courses to update in case it exists.
   */
  where: Prisma.coursesWhereUniqueInput
  /**
   * In case the courses found by the `where` argument doesn't exist, create a new courses with this data.
   */
  create: Prisma.XOR<Prisma.coursesCreateInput, Prisma.coursesUncheckedCreateInput>
  /**
   * In case the courses was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.coursesUpdateInput, Prisma.coursesUncheckedUpdateInput>
}

/**
 * courses delete
 */
export type coursesDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the courses
   */
  select?: Prisma.coursesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the courses
   */
  omit?: Prisma.coursesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.coursesInclude<ExtArgs> | null
  /**
   * Filter which courses to delete.
   */
  where: Prisma.coursesWhereUniqueInput
}

/**
 * courses deleteMany
 */
export type coursesDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which courses to delete
   */
  where?: Prisma.coursesWhereInput
  /**
   * Limit how many courses to delete.
   */
  limit?: number
}

/**
 * courses.topics
 */
export type courses$topicsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the topics
   */
  select?: Prisma.topicsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the topics
   */
  omit?: Prisma.topicsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.topicsInclude<ExtArgs> | null
  where?: Prisma.topicsWhereInput
  orderBy?: Prisma.topicsOrderByWithRelationInput | Prisma.topicsOrderByWithRelationInput[]
  cursor?: Prisma.topicsWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.TopicsScalarFieldEnum | Prisma.TopicsScalarFieldEnum[]
}

/**
 * courses without action
 */
export type coursesDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the courses
   */
  select?: Prisma.coursesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the courses
   */
  omit?: Prisma.coursesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.coursesInclude<ExtArgs> | null
}
