
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `icebreaker_contents` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model icebreaker_contents
 * Stores icebreaker dynamics: matching expressions with situation illustrations.
 * Teaches real-world communication in engaging visual context.
 */
export type icebreaker_contentsModel = runtime.Types.Result.DefaultSelection<Prisma.$icebreaker_contentsPayload>

export type AggregateIcebreaker_contents = {
  _count: Icebreaker_contentsCountAggregateOutputType | null
  _avg: Icebreaker_contentsAvgAggregateOutputType | null
  _sum: Icebreaker_contentsSumAggregateOutputType | null
  _min: Icebreaker_contentsMinAggregateOutputType | null
  _max: Icebreaker_contentsMaxAggregateOutputType | null
}

export type Icebreaker_contentsAvgAggregateOutputType = {
  id: number | null
  lesson_id: number | null
  pair_id: number | null
  pair_order: number | null
}

export type Icebreaker_contentsSumAggregateOutputType = {
  id: number | null
  lesson_id: number | null
  pair_id: number | null
  pair_order: number | null
}

export type Icebreaker_contentsMinAggregateOutputType = {
  id: number | null
  lesson_id: number | null
  title: string | null
  description: string | null
  expression: string | null
  illustration_url: string | null
  situation_description: string | null
  pair_id: number | null
  difficulty_level: string | null
  pair_order: number | null
}

export type Icebreaker_contentsMaxAggregateOutputType = {
  id: number | null
  lesson_id: number | null
  title: string | null
  description: string | null
  expression: string | null
  illustration_url: string | null
  situation_description: string | null
  pair_id: number | null
  difficulty_level: string | null
  pair_order: number | null
}

export type Icebreaker_contentsCountAggregateOutputType = {
  id: number
  lesson_id: number
  title: number
  description: number
  expression: number
  illustration_url: number
  situation_description: number
  pair_id: number
  difficulty_level: number
  pair_order: number
  _all: number
}


export type Icebreaker_contentsAvgAggregateInputType = {
  id?: true
  lesson_id?: true
  pair_id?: true
  pair_order?: true
}

export type Icebreaker_contentsSumAggregateInputType = {
  id?: true
  lesson_id?: true
  pair_id?: true
  pair_order?: true
}

export type Icebreaker_contentsMinAggregateInputType = {
  id?: true
  lesson_id?: true
  title?: true
  description?: true
  expression?: true
  illustration_url?: true
  situation_description?: true
  pair_id?: true
  difficulty_level?: true
  pair_order?: true
}

export type Icebreaker_contentsMaxAggregateInputType = {
  id?: true
  lesson_id?: true
  title?: true
  description?: true
  expression?: true
  illustration_url?: true
  situation_description?: true
  pair_id?: true
  difficulty_level?: true
  pair_order?: true
}

export type Icebreaker_contentsCountAggregateInputType = {
  id?: true
  lesson_id?: true
  title?: true
  description?: true
  expression?: true
  illustration_url?: true
  situation_description?: true
  pair_id?: true
  difficulty_level?: true
  pair_order?: true
  _all?: true
}

export type Icebreaker_contentsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which icebreaker_contents to aggregate.
   */
  where?: Prisma.icebreaker_contentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of icebreaker_contents to fetch.
   */
  orderBy?: Prisma.icebreaker_contentsOrderByWithRelationInput | Prisma.icebreaker_contentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.icebreaker_contentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` icebreaker_contents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` icebreaker_contents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned icebreaker_contents
  **/
  _count?: true | Icebreaker_contentsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Icebreaker_contentsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Icebreaker_contentsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Icebreaker_contentsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Icebreaker_contentsMaxAggregateInputType
}

export type GetIcebreaker_contentsAggregateType<T extends Icebreaker_contentsAggregateArgs> = {
      [P in keyof T & keyof AggregateIcebreaker_contents]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateIcebreaker_contents[P]>
    : Prisma.GetScalarType<T[P], AggregateIcebreaker_contents[P]>
}




export type icebreaker_contentsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.icebreaker_contentsWhereInput
  orderBy?: Prisma.icebreaker_contentsOrderByWithAggregationInput | Prisma.icebreaker_contentsOrderByWithAggregationInput[]
  by: Prisma.Icebreaker_contentsScalarFieldEnum[] | Prisma.Icebreaker_contentsScalarFieldEnum
  having?: Prisma.icebreaker_contentsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Icebreaker_contentsCountAggregateInputType | true
  _avg?: Icebreaker_contentsAvgAggregateInputType
  _sum?: Icebreaker_contentsSumAggregateInputType
  _min?: Icebreaker_contentsMinAggregateInputType
  _max?: Icebreaker_contentsMaxAggregateInputType
}

export type Icebreaker_contentsGroupByOutputType = {
  id: number
  lesson_id: number
  title: string
  description: string | null
  expression: string
  illustration_url: string
  situation_description: string
  pair_id: number | null
  difficulty_level: string
  pair_order: number
  _count: Icebreaker_contentsCountAggregateOutputType | null
  _avg: Icebreaker_contentsAvgAggregateOutputType | null
  _sum: Icebreaker_contentsSumAggregateOutputType | null
  _min: Icebreaker_contentsMinAggregateOutputType | null
  _max: Icebreaker_contentsMaxAggregateOutputType | null
}

export type GetIcebreaker_contentsGroupByPayload<T extends icebreaker_contentsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Icebreaker_contentsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Icebreaker_contentsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Icebreaker_contentsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Icebreaker_contentsGroupByOutputType[P]>
      }
    >
  >



export type icebreaker_contentsWhereInput = {
  AND?: Prisma.icebreaker_contentsWhereInput | Prisma.icebreaker_contentsWhereInput[]
  OR?: Prisma.icebreaker_contentsWhereInput[]
  NOT?: Prisma.icebreaker_contentsWhereInput | Prisma.icebreaker_contentsWhereInput[]
  id?: Prisma.IntFilter<"icebreaker_contents"> | number
  lesson_id?: Prisma.IntFilter<"icebreaker_contents"> | number
  title?: Prisma.StringFilter<"icebreaker_contents"> | string
  description?: Prisma.StringNullableFilter<"icebreaker_contents"> | string | null
  expression?: Prisma.StringFilter<"icebreaker_contents"> | string
  illustration_url?: Prisma.StringFilter<"icebreaker_contents"> | string
  situation_description?: Prisma.StringFilter<"icebreaker_contents"> | string
  pair_id?: Prisma.IntNullableFilter<"icebreaker_contents"> | number | null
  difficulty_level?: Prisma.StringFilter<"icebreaker_contents"> | string
  pair_order?: Prisma.IntFilter<"icebreaker_contents"> | number
  lessons?: Prisma.XOR<Prisma.LessonsScalarRelationFilter, Prisma.lessonsWhereInput>
}

export type icebreaker_contentsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  lesson_id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  expression?: Prisma.SortOrder
  illustration_url?: Prisma.SortOrder
  situation_description?: Prisma.SortOrder
  pair_id?: Prisma.SortOrderInput | Prisma.SortOrder
  difficulty_level?: Prisma.SortOrder
  pair_order?: Prisma.SortOrder
  lessons?: Prisma.lessonsOrderByWithRelationInput
}

export type icebreaker_contentsWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.icebreaker_contentsWhereInput | Prisma.icebreaker_contentsWhereInput[]
  OR?: Prisma.icebreaker_contentsWhereInput[]
  NOT?: Prisma.icebreaker_contentsWhereInput | Prisma.icebreaker_contentsWhereInput[]
  lesson_id?: Prisma.IntFilter<"icebreaker_contents"> | number
  title?: Prisma.StringFilter<"icebreaker_contents"> | string
  description?: Prisma.StringNullableFilter<"icebreaker_contents"> | string | null
  expression?: Prisma.StringFilter<"icebreaker_contents"> | string
  illustration_url?: Prisma.StringFilter<"icebreaker_contents"> | string
  situation_description?: Prisma.StringFilter<"icebreaker_contents"> | string
  pair_id?: Prisma.IntNullableFilter<"icebreaker_contents"> | number | null
  difficulty_level?: Prisma.StringFilter<"icebreaker_contents"> | string
  pair_order?: Prisma.IntFilter<"icebreaker_contents"> | number
  lessons?: Prisma.XOR<Prisma.LessonsScalarRelationFilter, Prisma.lessonsWhereInput>
}, "id">

export type icebreaker_contentsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  lesson_id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  expression?: Prisma.SortOrder
  illustration_url?: Prisma.SortOrder
  situation_description?: Prisma.SortOrder
  pair_id?: Prisma.SortOrderInput | Prisma.SortOrder
  difficulty_level?: Prisma.SortOrder
  pair_order?: Prisma.SortOrder
  _count?: Prisma.icebreaker_contentsCountOrderByAggregateInput
  _avg?: Prisma.icebreaker_contentsAvgOrderByAggregateInput
  _max?: Prisma.icebreaker_contentsMaxOrderByAggregateInput
  _min?: Prisma.icebreaker_contentsMinOrderByAggregateInput
  _sum?: Prisma.icebreaker_contentsSumOrderByAggregateInput
}

export type icebreaker_contentsScalarWhereWithAggregatesInput = {
  AND?: Prisma.icebreaker_contentsScalarWhereWithAggregatesInput | Prisma.icebreaker_contentsScalarWhereWithAggregatesInput[]
  OR?: Prisma.icebreaker_contentsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.icebreaker_contentsScalarWhereWithAggregatesInput | Prisma.icebreaker_contentsScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"icebreaker_contents"> | number
  lesson_id?: Prisma.IntWithAggregatesFilter<"icebreaker_contents"> | number
  title?: Prisma.StringWithAggregatesFilter<"icebreaker_contents"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"icebreaker_contents"> | string | null
  expression?: Prisma.StringWithAggregatesFilter<"icebreaker_contents"> | string
  illustration_url?: Prisma.StringWithAggregatesFilter<"icebreaker_contents"> | string
  situation_description?: Prisma.StringWithAggregatesFilter<"icebreaker_contents"> | string
  pair_id?: Prisma.IntNullableWithAggregatesFilter<"icebreaker_contents"> | number | null
  difficulty_level?: Prisma.StringWithAggregatesFilter<"icebreaker_contents"> | string
  pair_order?: Prisma.IntWithAggregatesFilter<"icebreaker_contents"> | number
}

export type icebreaker_contentsCreateInput = {
  title: string
  description?: string | null
  expression: string
  illustration_url: string
  situation_description: string
  pair_id?: number | null
  difficulty_level?: string
  pair_order?: number
  lessons: Prisma.lessonsCreateNestedOneWithoutIcebreaker_contentsInput
}

export type icebreaker_contentsUncheckedCreateInput = {
  id?: number
  lesson_id: number
  title: string
  description?: string | null
  expression: string
  illustration_url: string
  situation_description: string
  pair_id?: number | null
  difficulty_level?: string
  pair_order?: number
}

export type icebreaker_contentsUpdateInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  expression?: Prisma.StringFieldUpdateOperationsInput | string
  illustration_url?: Prisma.StringFieldUpdateOperationsInput | string
  situation_description?: Prisma.StringFieldUpdateOperationsInput | string
  pair_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  difficulty_level?: Prisma.StringFieldUpdateOperationsInput | string
  pair_order?: Prisma.IntFieldUpdateOperationsInput | number
  lessons?: Prisma.lessonsUpdateOneRequiredWithoutIcebreaker_contentsNestedInput
}

export type icebreaker_contentsUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  lesson_id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  expression?: Prisma.StringFieldUpdateOperationsInput | string
  illustration_url?: Prisma.StringFieldUpdateOperationsInput | string
  situation_description?: Prisma.StringFieldUpdateOperationsInput | string
  pair_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  difficulty_level?: Prisma.StringFieldUpdateOperationsInput | string
  pair_order?: Prisma.IntFieldUpdateOperationsInput | number
}

export type icebreaker_contentsCreateManyInput = {
  id?: number
  lesson_id: number
  title: string
  description?: string | null
  expression: string
  illustration_url: string
  situation_description: string
  pair_id?: number | null
  difficulty_level?: string
  pair_order?: number
}

export type icebreaker_contentsUpdateManyMutationInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  expression?: Prisma.StringFieldUpdateOperationsInput | string
  illustration_url?: Prisma.StringFieldUpdateOperationsInput | string
  situation_description?: Prisma.StringFieldUpdateOperationsInput | string
  pair_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  difficulty_level?: Prisma.StringFieldUpdateOperationsInput | string
  pair_order?: Prisma.IntFieldUpdateOperationsInput | number
}

export type icebreaker_contentsUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  lesson_id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  expression?: Prisma.StringFieldUpdateOperationsInput | string
  illustration_url?: Prisma.StringFieldUpdateOperationsInput | string
  situation_description?: Prisma.StringFieldUpdateOperationsInput | string
  pair_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  difficulty_level?: Prisma.StringFieldUpdateOperationsInput | string
  pair_order?: Prisma.IntFieldUpdateOperationsInput | number
}

export type Icebreaker_contentsListRelationFilter = {
  every?: Prisma.icebreaker_contentsWhereInput
  some?: Prisma.icebreaker_contentsWhereInput
  none?: Prisma.icebreaker_contentsWhereInput
}

export type icebreaker_contentsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type icebreaker_contentsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  lesson_id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  expression?: Prisma.SortOrder
  illustration_url?: Prisma.SortOrder
  situation_description?: Prisma.SortOrder
  pair_id?: Prisma.SortOrder
  difficulty_level?: Prisma.SortOrder
  pair_order?: Prisma.SortOrder
}

export type icebreaker_contentsAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  lesson_id?: Prisma.SortOrder
  pair_id?: Prisma.SortOrder
  pair_order?: Prisma.SortOrder
}

export type icebreaker_contentsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  lesson_id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  expression?: Prisma.SortOrder
  illustration_url?: Prisma.SortOrder
  situation_description?: Prisma.SortOrder
  pair_id?: Prisma.SortOrder
  difficulty_level?: Prisma.SortOrder
  pair_order?: Prisma.SortOrder
}

export type icebreaker_contentsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  lesson_id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  expression?: Prisma.SortOrder
  illustration_url?: Prisma.SortOrder
  situation_description?: Prisma.SortOrder
  pair_id?: Prisma.SortOrder
  difficulty_level?: Prisma.SortOrder
  pair_order?: Prisma.SortOrder
}

export type icebreaker_contentsSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  lesson_id?: Prisma.SortOrder
  pair_id?: Prisma.SortOrder
  pair_order?: Prisma.SortOrder
}

export type icebreaker_contentsCreateNestedManyWithoutLessonsInput = {
  create?: Prisma.XOR<Prisma.icebreaker_contentsCreateWithoutLessonsInput, Prisma.icebreaker_contentsUncheckedCreateWithoutLessonsInput> | Prisma.icebreaker_contentsCreateWithoutLessonsInput[] | Prisma.icebreaker_contentsUncheckedCreateWithoutLessonsInput[]
  connectOrCreate?: Prisma.icebreaker_contentsCreateOrConnectWithoutLessonsInput | Prisma.icebreaker_contentsCreateOrConnectWithoutLessonsInput[]
  createMany?: Prisma.icebreaker_contentsCreateManyLessonsInputEnvelope
  connect?: Prisma.icebreaker_contentsWhereUniqueInput | Prisma.icebreaker_contentsWhereUniqueInput[]
}

export type icebreaker_contentsUncheckedCreateNestedManyWithoutLessonsInput = {
  create?: Prisma.XOR<Prisma.icebreaker_contentsCreateWithoutLessonsInput, Prisma.icebreaker_contentsUncheckedCreateWithoutLessonsInput> | Prisma.icebreaker_contentsCreateWithoutLessonsInput[] | Prisma.icebreaker_contentsUncheckedCreateWithoutLessonsInput[]
  connectOrCreate?: Prisma.icebreaker_contentsCreateOrConnectWithoutLessonsInput | Prisma.icebreaker_contentsCreateOrConnectWithoutLessonsInput[]
  createMany?: Prisma.icebreaker_contentsCreateManyLessonsInputEnvelope
  connect?: Prisma.icebreaker_contentsWhereUniqueInput | Prisma.icebreaker_contentsWhereUniqueInput[]
}

export type icebreaker_contentsUpdateManyWithoutLessonsNestedInput = {
  create?: Prisma.XOR<Prisma.icebreaker_contentsCreateWithoutLessonsInput, Prisma.icebreaker_contentsUncheckedCreateWithoutLessonsInput> | Prisma.icebreaker_contentsCreateWithoutLessonsInput[] | Prisma.icebreaker_contentsUncheckedCreateWithoutLessonsInput[]
  connectOrCreate?: Prisma.icebreaker_contentsCreateOrConnectWithoutLessonsInput | Prisma.icebreaker_contentsCreateOrConnectWithoutLessonsInput[]
  upsert?: Prisma.icebreaker_contentsUpsertWithWhereUniqueWithoutLessonsInput | Prisma.icebreaker_contentsUpsertWithWhereUniqueWithoutLessonsInput[]
  createMany?: Prisma.icebreaker_contentsCreateManyLessonsInputEnvelope
  set?: Prisma.icebreaker_contentsWhereUniqueInput | Prisma.icebreaker_contentsWhereUniqueInput[]
  disconnect?: Prisma.icebreaker_contentsWhereUniqueInput | Prisma.icebreaker_contentsWhereUniqueInput[]
  delete?: Prisma.icebreaker_contentsWhereUniqueInput | Prisma.icebreaker_contentsWhereUniqueInput[]
  connect?: Prisma.icebreaker_contentsWhereUniqueInput | Prisma.icebreaker_contentsWhereUniqueInput[]
  update?: Prisma.icebreaker_contentsUpdateWithWhereUniqueWithoutLessonsInput | Prisma.icebreaker_contentsUpdateWithWhereUniqueWithoutLessonsInput[]
  updateMany?: Prisma.icebreaker_contentsUpdateManyWithWhereWithoutLessonsInput | Prisma.icebreaker_contentsUpdateManyWithWhereWithoutLessonsInput[]
  deleteMany?: Prisma.icebreaker_contentsScalarWhereInput | Prisma.icebreaker_contentsScalarWhereInput[]
}

export type icebreaker_contentsUncheckedUpdateManyWithoutLessonsNestedInput = {
  create?: Prisma.XOR<Prisma.icebreaker_contentsCreateWithoutLessonsInput, Prisma.icebreaker_contentsUncheckedCreateWithoutLessonsInput> | Prisma.icebreaker_contentsCreateWithoutLessonsInput[] | Prisma.icebreaker_contentsUncheckedCreateWithoutLessonsInput[]
  connectOrCreate?: Prisma.icebreaker_contentsCreateOrConnectWithoutLessonsInput | Prisma.icebreaker_contentsCreateOrConnectWithoutLessonsInput[]
  upsert?: Prisma.icebreaker_contentsUpsertWithWhereUniqueWithoutLessonsInput | Prisma.icebreaker_contentsUpsertWithWhereUniqueWithoutLessonsInput[]
  createMany?: Prisma.icebreaker_contentsCreateManyLessonsInputEnvelope
  set?: Prisma.icebreaker_contentsWhereUniqueInput | Prisma.icebreaker_contentsWhereUniqueInput[]
  disconnect?: Prisma.icebreaker_contentsWhereUniqueInput | Prisma.icebreaker_contentsWhereUniqueInput[]
  delete?: Prisma.icebreaker_contentsWhereUniqueInput | Prisma.icebreaker_contentsWhereUniqueInput[]
  connect?: Prisma.icebreaker_contentsWhereUniqueInput | Prisma.icebreaker_contentsWhereUniqueInput[]
  update?: Prisma.icebreaker_contentsUpdateWithWhereUniqueWithoutLessonsInput | Prisma.icebreaker_contentsUpdateWithWhereUniqueWithoutLessonsInput[]
  updateMany?: Prisma.icebreaker_contentsUpdateManyWithWhereWithoutLessonsInput | Prisma.icebreaker_contentsUpdateManyWithWhereWithoutLessonsInput[]
  deleteMany?: Prisma.icebreaker_contentsScalarWhereInput | Prisma.icebreaker_contentsScalarWhereInput[]
}

export type icebreaker_contentsCreateWithoutLessonsInput = {
  title: string
  description?: string | null
  expression: string
  illustration_url: string
  situation_description: string
  pair_id?: number | null
  difficulty_level?: string
  pair_order?: number
}

export type icebreaker_contentsUncheckedCreateWithoutLessonsInput = {
  id?: number
  title: string
  description?: string | null
  expression: string
  illustration_url: string
  situation_description: string
  pair_id?: number | null
  difficulty_level?: string
  pair_order?: number
}

export type icebreaker_contentsCreateOrConnectWithoutLessonsInput = {
  where: Prisma.icebreaker_contentsWhereUniqueInput
  create: Prisma.XOR<Prisma.icebreaker_contentsCreateWithoutLessonsInput, Prisma.icebreaker_contentsUncheckedCreateWithoutLessonsInput>
}

export type icebreaker_contentsCreateManyLessonsInputEnvelope = {
  data: Prisma.icebreaker_contentsCreateManyLessonsInput | Prisma.icebreaker_contentsCreateManyLessonsInput[]
  skipDuplicates?: boolean
}

export type icebreaker_contentsUpsertWithWhereUniqueWithoutLessonsInput = {
  where: Prisma.icebreaker_contentsWhereUniqueInput
  update: Prisma.XOR<Prisma.icebreaker_contentsUpdateWithoutLessonsInput, Prisma.icebreaker_contentsUncheckedUpdateWithoutLessonsInput>
  create: Prisma.XOR<Prisma.icebreaker_contentsCreateWithoutLessonsInput, Prisma.icebreaker_contentsUncheckedCreateWithoutLessonsInput>
}

export type icebreaker_contentsUpdateWithWhereUniqueWithoutLessonsInput = {
  where: Prisma.icebreaker_contentsWhereUniqueInput
  data: Prisma.XOR<Prisma.icebreaker_contentsUpdateWithoutLessonsInput, Prisma.icebreaker_contentsUncheckedUpdateWithoutLessonsInput>
}

export type icebreaker_contentsUpdateManyWithWhereWithoutLessonsInput = {
  where: Prisma.icebreaker_contentsScalarWhereInput
  data: Prisma.XOR<Prisma.icebreaker_contentsUpdateManyMutationInput, Prisma.icebreaker_contentsUncheckedUpdateManyWithoutLessonsInput>
}

export type icebreaker_contentsScalarWhereInput = {
  AND?: Prisma.icebreaker_contentsScalarWhereInput | Prisma.icebreaker_contentsScalarWhereInput[]
  OR?: Prisma.icebreaker_contentsScalarWhereInput[]
  NOT?: Prisma.icebreaker_contentsScalarWhereInput | Prisma.icebreaker_contentsScalarWhereInput[]
  id?: Prisma.IntFilter<"icebreaker_contents"> | number
  lesson_id?: Prisma.IntFilter<"icebreaker_contents"> | number
  title?: Prisma.StringFilter<"icebreaker_contents"> | string
  description?: Prisma.StringNullableFilter<"icebreaker_contents"> | string | null
  expression?: Prisma.StringFilter<"icebreaker_contents"> | string
  illustration_url?: Prisma.StringFilter<"icebreaker_contents"> | string
  situation_description?: Prisma.StringFilter<"icebreaker_contents"> | string
  pair_id?: Prisma.IntNullableFilter<"icebreaker_contents"> | number | null
  difficulty_level?: Prisma.StringFilter<"icebreaker_contents"> | string
  pair_order?: Prisma.IntFilter<"icebreaker_contents"> | number
}

export type icebreaker_contentsCreateManyLessonsInput = {
  id?: number
  title: string
  description?: string | null
  expression: string
  illustration_url: string
  situation_description: string
  pair_id?: number | null
  difficulty_level?: string
  pair_order?: number
}

export type icebreaker_contentsUpdateWithoutLessonsInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  expression?: Prisma.StringFieldUpdateOperationsInput | string
  illustration_url?: Prisma.StringFieldUpdateOperationsInput | string
  situation_description?: Prisma.StringFieldUpdateOperationsInput | string
  pair_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  difficulty_level?: Prisma.StringFieldUpdateOperationsInput | string
  pair_order?: Prisma.IntFieldUpdateOperationsInput | number
}

export type icebreaker_contentsUncheckedUpdateWithoutLessonsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  expression?: Prisma.StringFieldUpdateOperationsInput | string
  illustration_url?: Prisma.StringFieldUpdateOperationsInput | string
  situation_description?: Prisma.StringFieldUpdateOperationsInput | string
  pair_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  difficulty_level?: Prisma.StringFieldUpdateOperationsInput | string
  pair_order?: Prisma.IntFieldUpdateOperationsInput | number
}

export type icebreaker_contentsUncheckedUpdateManyWithoutLessonsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  expression?: Prisma.StringFieldUpdateOperationsInput | string
  illustration_url?: Prisma.StringFieldUpdateOperationsInput | string
  situation_description?: Prisma.StringFieldUpdateOperationsInput | string
  pair_id?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  difficulty_level?: Prisma.StringFieldUpdateOperationsInput | string
  pair_order?: Prisma.IntFieldUpdateOperationsInput | number
}



export type icebreaker_contentsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  lesson_id?: boolean
  title?: boolean
  description?: boolean
  expression?: boolean
  illustration_url?: boolean
  situation_description?: boolean
  pair_id?: boolean
  difficulty_level?: boolean
  pair_order?: boolean
  lessons?: boolean | Prisma.lessonsDefaultArgs<ExtArgs>
}, ExtArgs["result"]["icebreaker_contents"]>

export type icebreaker_contentsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  lesson_id?: boolean
  title?: boolean
  description?: boolean
  expression?: boolean
  illustration_url?: boolean
  situation_description?: boolean
  pair_id?: boolean
  difficulty_level?: boolean
  pair_order?: boolean
  lessons?: boolean | Prisma.lessonsDefaultArgs<ExtArgs>
}, ExtArgs["result"]["icebreaker_contents"]>

export type icebreaker_contentsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  lesson_id?: boolean
  title?: boolean
  description?: boolean
  expression?: boolean
  illustration_url?: boolean
  situation_description?: boolean
  pair_id?: boolean
  difficulty_level?: boolean
  pair_order?: boolean
  lessons?: boolean | Prisma.lessonsDefaultArgs<ExtArgs>
}, ExtArgs["result"]["icebreaker_contents"]>

export type icebreaker_contentsSelectScalar = {
  id?: boolean
  lesson_id?: boolean
  title?: boolean
  description?: boolean
  expression?: boolean
  illustration_url?: boolean
  situation_description?: boolean
  pair_id?: boolean
  difficulty_level?: boolean
  pair_order?: boolean
}

export type icebreaker_contentsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "lesson_id" | "title" | "description" | "expression" | "illustration_url" | "situation_description" | "pair_id" | "difficulty_level" | "pair_order", ExtArgs["result"]["icebreaker_contents"]>
export type icebreaker_contentsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  lessons?: boolean | Prisma.lessonsDefaultArgs<ExtArgs>
}
export type icebreaker_contentsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  lessons?: boolean | Prisma.lessonsDefaultArgs<ExtArgs>
}
export type icebreaker_contentsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  lessons?: boolean | Prisma.lessonsDefaultArgs<ExtArgs>
}

export type $icebreaker_contentsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "icebreaker_contents"
  objects: {
    lessons: Prisma.$lessonsPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    lesson_id: number
    /**
     * Expression title
     */
    title: string
    /**
     * Expression description
     */
    description: string | null
    /**
     * English expression
     */
    expression: string
    /**
     * Illustration URL (situation context)
     */
    illustration_url: string
    /**
     * Description of the situation
     */
    situation_description: string
    /**
     * Pair ID (connects to matching expression)
     */
    pair_id: number | null
    /**
     * Difficulty level: beginner, intermediate, advanced
     */
    difficulty_level: string
    /**
     * Order within the lesson
     */
    pair_order: number
  }, ExtArgs["result"]["icebreaker_contents"]>
  composites: {}
}

export type icebreaker_contentsGetPayload<S extends boolean | null | undefined | icebreaker_contentsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$icebreaker_contentsPayload, S>

export type icebreaker_contentsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<icebreaker_contentsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Icebreaker_contentsCountAggregateInputType | true
  }

export interface icebreaker_contentsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['icebreaker_contents'], meta: { name: 'icebreaker_contents' } }
  /**
   * Find zero or one Icebreaker_contents that matches the filter.
   * @param {icebreaker_contentsFindUniqueArgs} args - Arguments to find a Icebreaker_contents
   * @example
   * // Get one Icebreaker_contents
   * const icebreaker_contents = await prisma.icebreaker_contents.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends icebreaker_contentsFindUniqueArgs>(args: Prisma.SelectSubset<T, icebreaker_contentsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__icebreaker_contentsClient<runtime.Types.Result.GetResult<Prisma.$icebreaker_contentsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Icebreaker_contents that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {icebreaker_contentsFindUniqueOrThrowArgs} args - Arguments to find a Icebreaker_contents
   * @example
   * // Get one Icebreaker_contents
   * const icebreaker_contents = await prisma.icebreaker_contents.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends icebreaker_contentsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, icebreaker_contentsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__icebreaker_contentsClient<runtime.Types.Result.GetResult<Prisma.$icebreaker_contentsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Icebreaker_contents that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {icebreaker_contentsFindFirstArgs} args - Arguments to find a Icebreaker_contents
   * @example
   * // Get one Icebreaker_contents
   * const icebreaker_contents = await prisma.icebreaker_contents.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends icebreaker_contentsFindFirstArgs>(args?: Prisma.SelectSubset<T, icebreaker_contentsFindFirstArgs<ExtArgs>>): Prisma.Prisma__icebreaker_contentsClient<runtime.Types.Result.GetResult<Prisma.$icebreaker_contentsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Icebreaker_contents that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {icebreaker_contentsFindFirstOrThrowArgs} args - Arguments to find a Icebreaker_contents
   * @example
   * // Get one Icebreaker_contents
   * const icebreaker_contents = await prisma.icebreaker_contents.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends icebreaker_contentsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, icebreaker_contentsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__icebreaker_contentsClient<runtime.Types.Result.GetResult<Prisma.$icebreaker_contentsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Icebreaker_contents that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {icebreaker_contentsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Icebreaker_contents
   * const icebreaker_contents = await prisma.icebreaker_contents.findMany()
   * 
   * // Get first 10 Icebreaker_contents
   * const icebreaker_contents = await prisma.icebreaker_contents.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const icebreaker_contentsWithIdOnly = await prisma.icebreaker_contents.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends icebreaker_contentsFindManyArgs>(args?: Prisma.SelectSubset<T, icebreaker_contentsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$icebreaker_contentsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Icebreaker_contents.
   * @param {icebreaker_contentsCreateArgs} args - Arguments to create a Icebreaker_contents.
   * @example
   * // Create one Icebreaker_contents
   * const Icebreaker_contents = await prisma.icebreaker_contents.create({
   *   data: {
   *     // ... data to create a Icebreaker_contents
   *   }
   * })
   * 
   */
  create<T extends icebreaker_contentsCreateArgs>(args: Prisma.SelectSubset<T, icebreaker_contentsCreateArgs<ExtArgs>>): Prisma.Prisma__icebreaker_contentsClient<runtime.Types.Result.GetResult<Prisma.$icebreaker_contentsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Icebreaker_contents.
   * @param {icebreaker_contentsCreateManyArgs} args - Arguments to create many Icebreaker_contents.
   * @example
   * // Create many Icebreaker_contents
   * const icebreaker_contents = await prisma.icebreaker_contents.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends icebreaker_contentsCreateManyArgs>(args?: Prisma.SelectSubset<T, icebreaker_contentsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Icebreaker_contents and returns the data saved in the database.
   * @param {icebreaker_contentsCreateManyAndReturnArgs} args - Arguments to create many Icebreaker_contents.
   * @example
   * // Create many Icebreaker_contents
   * const icebreaker_contents = await prisma.icebreaker_contents.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Icebreaker_contents and only return the `id`
   * const icebreaker_contentsWithIdOnly = await prisma.icebreaker_contents.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends icebreaker_contentsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, icebreaker_contentsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$icebreaker_contentsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Icebreaker_contents.
   * @param {icebreaker_contentsDeleteArgs} args - Arguments to delete one Icebreaker_contents.
   * @example
   * // Delete one Icebreaker_contents
   * const Icebreaker_contents = await prisma.icebreaker_contents.delete({
   *   where: {
   *     // ... filter to delete one Icebreaker_contents
   *   }
   * })
   * 
   */
  delete<T extends icebreaker_contentsDeleteArgs>(args: Prisma.SelectSubset<T, icebreaker_contentsDeleteArgs<ExtArgs>>): Prisma.Prisma__icebreaker_contentsClient<runtime.Types.Result.GetResult<Prisma.$icebreaker_contentsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Icebreaker_contents.
   * @param {icebreaker_contentsUpdateArgs} args - Arguments to update one Icebreaker_contents.
   * @example
   * // Update one Icebreaker_contents
   * const icebreaker_contents = await prisma.icebreaker_contents.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends icebreaker_contentsUpdateArgs>(args: Prisma.SelectSubset<T, icebreaker_contentsUpdateArgs<ExtArgs>>): Prisma.Prisma__icebreaker_contentsClient<runtime.Types.Result.GetResult<Prisma.$icebreaker_contentsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Icebreaker_contents.
   * @param {icebreaker_contentsDeleteManyArgs} args - Arguments to filter Icebreaker_contents to delete.
   * @example
   * // Delete a few Icebreaker_contents
   * const { count } = await prisma.icebreaker_contents.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends icebreaker_contentsDeleteManyArgs>(args?: Prisma.SelectSubset<T, icebreaker_contentsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Icebreaker_contents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {icebreaker_contentsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Icebreaker_contents
   * const icebreaker_contents = await prisma.icebreaker_contents.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends icebreaker_contentsUpdateManyArgs>(args: Prisma.SelectSubset<T, icebreaker_contentsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Icebreaker_contents and returns the data updated in the database.
   * @param {icebreaker_contentsUpdateManyAndReturnArgs} args - Arguments to update many Icebreaker_contents.
   * @example
   * // Update many Icebreaker_contents
   * const icebreaker_contents = await prisma.icebreaker_contents.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Icebreaker_contents and only return the `id`
   * const icebreaker_contentsWithIdOnly = await prisma.icebreaker_contents.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends icebreaker_contentsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, icebreaker_contentsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$icebreaker_contentsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Icebreaker_contents.
   * @param {icebreaker_contentsUpsertArgs} args - Arguments to update or create a Icebreaker_contents.
   * @example
   * // Update or create a Icebreaker_contents
   * const icebreaker_contents = await prisma.icebreaker_contents.upsert({
   *   create: {
   *     // ... data to create a Icebreaker_contents
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Icebreaker_contents we want to update
   *   }
   * })
   */
  upsert<T extends icebreaker_contentsUpsertArgs>(args: Prisma.SelectSubset<T, icebreaker_contentsUpsertArgs<ExtArgs>>): Prisma.Prisma__icebreaker_contentsClient<runtime.Types.Result.GetResult<Prisma.$icebreaker_contentsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Icebreaker_contents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {icebreaker_contentsCountArgs} args - Arguments to filter Icebreaker_contents to count.
   * @example
   * // Count the number of Icebreaker_contents
   * const count = await prisma.icebreaker_contents.count({
   *   where: {
   *     // ... the filter for the Icebreaker_contents we want to count
   *   }
   * })
  **/
  count<T extends icebreaker_contentsCountArgs>(
    args?: Prisma.Subset<T, icebreaker_contentsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Icebreaker_contentsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Icebreaker_contents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Icebreaker_contentsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Icebreaker_contentsAggregateArgs>(args: Prisma.Subset<T, Icebreaker_contentsAggregateArgs>): Prisma.PrismaPromise<GetIcebreaker_contentsAggregateType<T>>

  /**
   * Group by Icebreaker_contents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {icebreaker_contentsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends icebreaker_contentsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: icebreaker_contentsGroupByArgs['orderBy'] }
      : { orderBy?: icebreaker_contentsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, icebreaker_contentsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetIcebreaker_contentsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the icebreaker_contents model
 */
readonly fields: icebreaker_contentsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for icebreaker_contents.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__icebreaker_contentsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  lessons<T extends Prisma.lessonsDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.lessonsDefaultArgs<ExtArgs>>): Prisma.Prisma__lessonsClient<runtime.Types.Result.GetResult<Prisma.$lessonsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the icebreaker_contents model
 */
export interface icebreaker_contentsFieldRefs {
  readonly id: Prisma.FieldRef<"icebreaker_contents", 'Int'>
  readonly lesson_id: Prisma.FieldRef<"icebreaker_contents", 'Int'>
  readonly title: Prisma.FieldRef<"icebreaker_contents", 'String'>
  readonly description: Prisma.FieldRef<"icebreaker_contents", 'String'>
  readonly expression: Prisma.FieldRef<"icebreaker_contents", 'String'>
  readonly illustration_url: Prisma.FieldRef<"icebreaker_contents", 'String'>
  readonly situation_description: Prisma.FieldRef<"icebreaker_contents", 'String'>
  readonly pair_id: Prisma.FieldRef<"icebreaker_contents", 'Int'>
  readonly difficulty_level: Prisma.FieldRef<"icebreaker_contents", 'String'>
  readonly pair_order: Prisma.FieldRef<"icebreaker_contents", 'Int'>
}
    

// Custom InputTypes
/**
 * icebreaker_contents findUnique
 */
export type icebreaker_contentsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the icebreaker_contents
   */
  select?: Prisma.icebreaker_contentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the icebreaker_contents
   */
  omit?: Prisma.icebreaker_contentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.icebreaker_contentsInclude<ExtArgs> | null
  /**
   * Filter, which icebreaker_contents to fetch.
   */
  where: Prisma.icebreaker_contentsWhereUniqueInput
}

/**
 * icebreaker_contents findUniqueOrThrow
 */
export type icebreaker_contentsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the icebreaker_contents
   */
  select?: Prisma.icebreaker_contentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the icebreaker_contents
   */
  omit?: Prisma.icebreaker_contentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.icebreaker_contentsInclude<ExtArgs> | null
  /**
   * Filter, which icebreaker_contents to fetch.
   */
  where: Prisma.icebreaker_contentsWhereUniqueInput
}

/**
 * icebreaker_contents findFirst
 */
export type icebreaker_contentsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the icebreaker_contents
   */
  select?: Prisma.icebreaker_contentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the icebreaker_contents
   */
  omit?: Prisma.icebreaker_contentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.icebreaker_contentsInclude<ExtArgs> | null
  /**
   * Filter, which icebreaker_contents to fetch.
   */
  where?: Prisma.icebreaker_contentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of icebreaker_contents to fetch.
   */
  orderBy?: Prisma.icebreaker_contentsOrderByWithRelationInput | Prisma.icebreaker_contentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for icebreaker_contents.
   */
  cursor?: Prisma.icebreaker_contentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` icebreaker_contents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` icebreaker_contents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of icebreaker_contents.
   */
  distinct?: Prisma.Icebreaker_contentsScalarFieldEnum | Prisma.Icebreaker_contentsScalarFieldEnum[]
}

/**
 * icebreaker_contents findFirstOrThrow
 */
export type icebreaker_contentsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the icebreaker_contents
   */
  select?: Prisma.icebreaker_contentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the icebreaker_contents
   */
  omit?: Prisma.icebreaker_contentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.icebreaker_contentsInclude<ExtArgs> | null
  /**
   * Filter, which icebreaker_contents to fetch.
   */
  where?: Prisma.icebreaker_contentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of icebreaker_contents to fetch.
   */
  orderBy?: Prisma.icebreaker_contentsOrderByWithRelationInput | Prisma.icebreaker_contentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for icebreaker_contents.
   */
  cursor?: Prisma.icebreaker_contentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` icebreaker_contents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` icebreaker_contents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of icebreaker_contents.
   */
  distinct?: Prisma.Icebreaker_contentsScalarFieldEnum | Prisma.Icebreaker_contentsScalarFieldEnum[]
}

/**
 * icebreaker_contents findMany
 */
export type icebreaker_contentsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the icebreaker_contents
   */
  select?: Prisma.icebreaker_contentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the icebreaker_contents
   */
  omit?: Prisma.icebreaker_contentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.icebreaker_contentsInclude<ExtArgs> | null
  /**
   * Filter, which icebreaker_contents to fetch.
   */
  where?: Prisma.icebreaker_contentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of icebreaker_contents to fetch.
   */
  orderBy?: Prisma.icebreaker_contentsOrderByWithRelationInput | Prisma.icebreaker_contentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing icebreaker_contents.
   */
  cursor?: Prisma.icebreaker_contentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` icebreaker_contents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` icebreaker_contents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of icebreaker_contents.
   */
  distinct?: Prisma.Icebreaker_contentsScalarFieldEnum | Prisma.Icebreaker_contentsScalarFieldEnum[]
}

/**
 * icebreaker_contents create
 */
export type icebreaker_contentsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the icebreaker_contents
   */
  select?: Prisma.icebreaker_contentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the icebreaker_contents
   */
  omit?: Prisma.icebreaker_contentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.icebreaker_contentsInclude<ExtArgs> | null
  /**
   * The data needed to create a icebreaker_contents.
   */
  data: Prisma.XOR<Prisma.icebreaker_contentsCreateInput, Prisma.icebreaker_contentsUncheckedCreateInput>
}

/**
 * icebreaker_contents createMany
 */
export type icebreaker_contentsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many icebreaker_contents.
   */
  data: Prisma.icebreaker_contentsCreateManyInput | Prisma.icebreaker_contentsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * icebreaker_contents createManyAndReturn
 */
export type icebreaker_contentsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the icebreaker_contents
   */
  select?: Prisma.icebreaker_contentsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the icebreaker_contents
   */
  omit?: Prisma.icebreaker_contentsOmit<ExtArgs> | null
  /**
   * The data used to create many icebreaker_contents.
   */
  data: Prisma.icebreaker_contentsCreateManyInput | Prisma.icebreaker_contentsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.icebreaker_contentsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * icebreaker_contents update
 */
export type icebreaker_contentsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the icebreaker_contents
   */
  select?: Prisma.icebreaker_contentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the icebreaker_contents
   */
  omit?: Prisma.icebreaker_contentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.icebreaker_contentsInclude<ExtArgs> | null
  /**
   * The data needed to update a icebreaker_contents.
   */
  data: Prisma.XOR<Prisma.icebreaker_contentsUpdateInput, Prisma.icebreaker_contentsUncheckedUpdateInput>
  /**
   * Choose, which icebreaker_contents to update.
   */
  where: Prisma.icebreaker_contentsWhereUniqueInput
}

/**
 * icebreaker_contents updateMany
 */
export type icebreaker_contentsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update icebreaker_contents.
   */
  data: Prisma.XOR<Prisma.icebreaker_contentsUpdateManyMutationInput, Prisma.icebreaker_contentsUncheckedUpdateManyInput>
  /**
   * Filter which icebreaker_contents to update
   */
  where?: Prisma.icebreaker_contentsWhereInput
  /**
   * Limit how many icebreaker_contents to update.
   */
  limit?: number
}

/**
 * icebreaker_contents updateManyAndReturn
 */
export type icebreaker_contentsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the icebreaker_contents
   */
  select?: Prisma.icebreaker_contentsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the icebreaker_contents
   */
  omit?: Prisma.icebreaker_contentsOmit<ExtArgs> | null
  /**
   * The data used to update icebreaker_contents.
   */
  data: Prisma.XOR<Prisma.icebreaker_contentsUpdateManyMutationInput, Prisma.icebreaker_contentsUncheckedUpdateManyInput>
  /**
   * Filter which icebreaker_contents to update
   */
  where?: Prisma.icebreaker_contentsWhereInput
  /**
   * Limit how many icebreaker_contents to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.icebreaker_contentsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * icebreaker_contents upsert
 */
export type icebreaker_contentsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the icebreaker_contents
   */
  select?: Prisma.icebreaker_contentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the icebreaker_contents
   */
  omit?: Prisma.icebreaker_contentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.icebreaker_contentsInclude<ExtArgs> | null
  /**
   * The filter to search for the icebreaker_contents to update in case it exists.
   */
  where: Prisma.icebreaker_contentsWhereUniqueInput
  /**
   * In case the icebreaker_contents found by the `where` argument doesn't exist, create a new icebreaker_contents with this data.
   */
  create: Prisma.XOR<Prisma.icebreaker_contentsCreateInput, Prisma.icebreaker_contentsUncheckedCreateInput>
  /**
   * In case the icebreaker_contents was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.icebreaker_contentsUpdateInput, Prisma.icebreaker_contentsUncheckedUpdateInput>
}

/**
 * icebreaker_contents delete
 */
export type icebreaker_contentsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the icebreaker_contents
   */
  select?: Prisma.icebreaker_contentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the icebreaker_contents
   */
  omit?: Prisma.icebreaker_contentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.icebreaker_contentsInclude<ExtArgs> | null
  /**
   * Filter which icebreaker_contents to delete.
   */
  where: Prisma.icebreaker_contentsWhereUniqueInput
}

/**
 * icebreaker_contents deleteMany
 */
export type icebreaker_contentsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which icebreaker_contents to delete
   */
  where?: Prisma.icebreaker_contentsWhereInput
  /**
   * Limit how many icebreaker_contents to delete.
   */
  limit?: number
}

/**
 * icebreaker_contents without action
 */
export type icebreaker_contentsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the icebreaker_contents
   */
  select?: Prisma.icebreaker_contentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the icebreaker_contents
   */
  omit?: Prisma.icebreaker_contentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.icebreaker_contentsInclude<ExtArgs> | null
}
