
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `listening_contents` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model listening_contents
 * Stores audio comprehension exercises with image-based answer selection.
 * Includes audio clips and multiple choice image selections.
 */
export type listening_contentsModel = runtime.Types.Result.DefaultSelection<Prisma.$listening_contentsPayload>

export type AggregateListening_contents = {
  _count: Listening_contentsCountAggregateOutputType | null
  _avg: Listening_contentsAvgAggregateOutputType | null
  _sum: Listening_contentsSumAggregateOutputType | null
  _min: Listening_contentsMinAggregateOutputType | null
  _max: Listening_contentsMaxAggregateOutputType | null
}

export type Listening_contentsAvgAggregateOutputType = {
  id: number | null
  lesson_id: number | null
  correct_answer: number | null
  question_order: number | null
}

export type Listening_contentsSumAggregateOutputType = {
  id: number | null
  lesson_id: number | null
  correct_answer: number | null
  question_order: number | null
}

export type Listening_contentsMinAggregateOutputType = {
  id: number | null
  lesson_id: number | null
  title: string | null
  description: string | null
  question: string | null
  audio_url: string | null
  image_options: string | null
  correct_answer: number | null
  feedback_correct: string | null
  feedback_incorrect: string | null
  difficulty_level: string | null
  question_order: number | null
}

export type Listening_contentsMaxAggregateOutputType = {
  id: number | null
  lesson_id: number | null
  title: string | null
  description: string | null
  question: string | null
  audio_url: string | null
  image_options: string | null
  correct_answer: number | null
  feedback_correct: string | null
  feedback_incorrect: string | null
  difficulty_level: string | null
  question_order: number | null
}

export type Listening_contentsCountAggregateOutputType = {
  id: number
  lesson_id: number
  title: number
  description: number
  question: number
  audio_url: number
  image_options: number
  correct_answer: number
  feedback_correct: number
  feedback_incorrect: number
  difficulty_level: number
  question_order: number
  _all: number
}


export type Listening_contentsAvgAggregateInputType = {
  id?: true
  lesson_id?: true
  correct_answer?: true
  question_order?: true
}

export type Listening_contentsSumAggregateInputType = {
  id?: true
  lesson_id?: true
  correct_answer?: true
  question_order?: true
}

export type Listening_contentsMinAggregateInputType = {
  id?: true
  lesson_id?: true
  title?: true
  description?: true
  question?: true
  audio_url?: true
  image_options?: true
  correct_answer?: true
  feedback_correct?: true
  feedback_incorrect?: true
  difficulty_level?: true
  question_order?: true
}

export type Listening_contentsMaxAggregateInputType = {
  id?: true
  lesson_id?: true
  title?: true
  description?: true
  question?: true
  audio_url?: true
  image_options?: true
  correct_answer?: true
  feedback_correct?: true
  feedback_incorrect?: true
  difficulty_level?: true
  question_order?: true
}

export type Listening_contentsCountAggregateInputType = {
  id?: true
  lesson_id?: true
  title?: true
  description?: true
  question?: true
  audio_url?: true
  image_options?: true
  correct_answer?: true
  feedback_correct?: true
  feedback_incorrect?: true
  difficulty_level?: true
  question_order?: true
  _all?: true
}

export type Listening_contentsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which listening_contents to aggregate.
   */
  where?: Prisma.listening_contentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of listening_contents to fetch.
   */
  orderBy?: Prisma.listening_contentsOrderByWithRelationInput | Prisma.listening_contentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.listening_contentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` listening_contents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` listening_contents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned listening_contents
  **/
  _count?: true | Listening_contentsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Listening_contentsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Listening_contentsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Listening_contentsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Listening_contentsMaxAggregateInputType
}

export type GetListening_contentsAggregateType<T extends Listening_contentsAggregateArgs> = {
      [P in keyof T & keyof AggregateListening_contents]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateListening_contents[P]>
    : Prisma.GetScalarType<T[P], AggregateListening_contents[P]>
}




export type listening_contentsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.listening_contentsWhereInput
  orderBy?: Prisma.listening_contentsOrderByWithAggregationInput | Prisma.listening_contentsOrderByWithAggregationInput[]
  by: Prisma.Listening_contentsScalarFieldEnum[] | Prisma.Listening_contentsScalarFieldEnum
  having?: Prisma.listening_contentsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Listening_contentsCountAggregateInputType | true
  _avg?: Listening_contentsAvgAggregateInputType
  _sum?: Listening_contentsSumAggregateInputType
  _min?: Listening_contentsMinAggregateInputType
  _max?: Listening_contentsMaxAggregateInputType
}

export type Listening_contentsGroupByOutputType = {
  id: number
  lesson_id: number
  title: string
  description: string | null
  question: string
  audio_url: string
  image_options: string
  correct_answer: number
  feedback_correct: string | null
  feedback_incorrect: string | null
  difficulty_level: string
  question_order: number
  _count: Listening_contentsCountAggregateOutputType | null
  _avg: Listening_contentsAvgAggregateOutputType | null
  _sum: Listening_contentsSumAggregateOutputType | null
  _min: Listening_contentsMinAggregateOutputType | null
  _max: Listening_contentsMaxAggregateOutputType | null
}

export type GetListening_contentsGroupByPayload<T extends listening_contentsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Listening_contentsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Listening_contentsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Listening_contentsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Listening_contentsGroupByOutputType[P]>
      }
    >
  >



export type listening_contentsWhereInput = {
  AND?: Prisma.listening_contentsWhereInput | Prisma.listening_contentsWhereInput[]
  OR?: Prisma.listening_contentsWhereInput[]
  NOT?: Prisma.listening_contentsWhereInput | Prisma.listening_contentsWhereInput[]
  id?: Prisma.IntFilter<"listening_contents"> | number
  lesson_id?: Prisma.IntFilter<"listening_contents"> | number
  title?: Prisma.StringFilter<"listening_contents"> | string
  description?: Prisma.StringNullableFilter<"listening_contents"> | string | null
  question?: Prisma.StringFilter<"listening_contents"> | string
  audio_url?: Prisma.StringFilter<"listening_contents"> | string
  image_options?: Prisma.StringFilter<"listening_contents"> | string
  correct_answer?: Prisma.IntFilter<"listening_contents"> | number
  feedback_correct?: Prisma.StringNullableFilter<"listening_contents"> | string | null
  feedback_incorrect?: Prisma.StringNullableFilter<"listening_contents"> | string | null
  difficulty_level?: Prisma.StringFilter<"listening_contents"> | string
  question_order?: Prisma.IntFilter<"listening_contents"> | number
  lessons?: Prisma.XOR<Prisma.LessonsScalarRelationFilter, Prisma.lessonsWhereInput>
}

export type listening_contentsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  lesson_id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  question?: Prisma.SortOrder
  audio_url?: Prisma.SortOrder
  image_options?: Prisma.SortOrder
  correct_answer?: Prisma.SortOrder
  feedback_correct?: Prisma.SortOrderInput | Prisma.SortOrder
  feedback_incorrect?: Prisma.SortOrderInput | Prisma.SortOrder
  difficulty_level?: Prisma.SortOrder
  question_order?: Prisma.SortOrder
  lessons?: Prisma.lessonsOrderByWithRelationInput
}

export type listening_contentsWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.listening_contentsWhereInput | Prisma.listening_contentsWhereInput[]
  OR?: Prisma.listening_contentsWhereInput[]
  NOT?: Prisma.listening_contentsWhereInput | Prisma.listening_contentsWhereInput[]
  lesson_id?: Prisma.IntFilter<"listening_contents"> | number
  title?: Prisma.StringFilter<"listening_contents"> | string
  description?: Prisma.StringNullableFilter<"listening_contents"> | string | null
  question?: Prisma.StringFilter<"listening_contents"> | string
  audio_url?: Prisma.StringFilter<"listening_contents"> | string
  image_options?: Prisma.StringFilter<"listening_contents"> | string
  correct_answer?: Prisma.IntFilter<"listening_contents"> | number
  feedback_correct?: Prisma.StringNullableFilter<"listening_contents"> | string | null
  feedback_incorrect?: Prisma.StringNullableFilter<"listening_contents"> | string | null
  difficulty_level?: Prisma.StringFilter<"listening_contents"> | string
  question_order?: Prisma.IntFilter<"listening_contents"> | number
  lessons?: Prisma.XOR<Prisma.LessonsScalarRelationFilter, Prisma.lessonsWhereInput>
}, "id">

export type listening_contentsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  lesson_id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  question?: Prisma.SortOrder
  audio_url?: Prisma.SortOrder
  image_options?: Prisma.SortOrder
  correct_answer?: Prisma.SortOrder
  feedback_correct?: Prisma.SortOrderInput | Prisma.SortOrder
  feedback_incorrect?: Prisma.SortOrderInput | Prisma.SortOrder
  difficulty_level?: Prisma.SortOrder
  question_order?: Prisma.SortOrder
  _count?: Prisma.listening_contentsCountOrderByAggregateInput
  _avg?: Prisma.listening_contentsAvgOrderByAggregateInput
  _max?: Prisma.listening_contentsMaxOrderByAggregateInput
  _min?: Prisma.listening_contentsMinOrderByAggregateInput
  _sum?: Prisma.listening_contentsSumOrderByAggregateInput
}

export type listening_contentsScalarWhereWithAggregatesInput = {
  AND?: Prisma.listening_contentsScalarWhereWithAggregatesInput | Prisma.listening_contentsScalarWhereWithAggregatesInput[]
  OR?: Prisma.listening_contentsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.listening_contentsScalarWhereWithAggregatesInput | Prisma.listening_contentsScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"listening_contents"> | number
  lesson_id?: Prisma.IntWithAggregatesFilter<"listening_contents"> | number
  title?: Prisma.StringWithAggregatesFilter<"listening_contents"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"listening_contents"> | string | null
  question?: Prisma.StringWithAggregatesFilter<"listening_contents"> | string
  audio_url?: Prisma.StringWithAggregatesFilter<"listening_contents"> | string
  image_options?: Prisma.StringWithAggregatesFilter<"listening_contents"> | string
  correct_answer?: Prisma.IntWithAggregatesFilter<"listening_contents"> | number
  feedback_correct?: Prisma.StringNullableWithAggregatesFilter<"listening_contents"> | string | null
  feedback_incorrect?: Prisma.StringNullableWithAggregatesFilter<"listening_contents"> | string | null
  difficulty_level?: Prisma.StringWithAggregatesFilter<"listening_contents"> | string
  question_order?: Prisma.IntWithAggregatesFilter<"listening_contents"> | number
}

export type listening_contentsCreateInput = {
  title: string
  description?: string | null
  question: string
  audio_url: string
  image_options: string
  correct_answer: number
  feedback_correct?: string | null
  feedback_incorrect?: string | null
  difficulty_level?: string
  question_order?: number
  lessons: Prisma.lessonsCreateNestedOneWithoutListening_contentsInput
}

export type listening_contentsUncheckedCreateInput = {
  id?: number
  lesson_id: number
  title: string
  description?: string | null
  question: string
  audio_url: string
  image_options: string
  correct_answer: number
  feedback_correct?: string | null
  feedback_incorrect?: string | null
  difficulty_level?: string
  question_order?: number
}

export type listening_contentsUpdateInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  question?: Prisma.StringFieldUpdateOperationsInput | string
  audio_url?: Prisma.StringFieldUpdateOperationsInput | string
  image_options?: Prisma.StringFieldUpdateOperationsInput | string
  correct_answer?: Prisma.IntFieldUpdateOperationsInput | number
  feedback_correct?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  feedback_incorrect?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  difficulty_level?: Prisma.StringFieldUpdateOperationsInput | string
  question_order?: Prisma.IntFieldUpdateOperationsInput | number
  lessons?: Prisma.lessonsUpdateOneRequiredWithoutListening_contentsNestedInput
}

export type listening_contentsUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  lesson_id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  question?: Prisma.StringFieldUpdateOperationsInput | string
  audio_url?: Prisma.StringFieldUpdateOperationsInput | string
  image_options?: Prisma.StringFieldUpdateOperationsInput | string
  correct_answer?: Prisma.IntFieldUpdateOperationsInput | number
  feedback_correct?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  feedback_incorrect?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  difficulty_level?: Prisma.StringFieldUpdateOperationsInput | string
  question_order?: Prisma.IntFieldUpdateOperationsInput | number
}

export type listening_contentsCreateManyInput = {
  id?: number
  lesson_id: number
  title: string
  description?: string | null
  question: string
  audio_url: string
  image_options: string
  correct_answer: number
  feedback_correct?: string | null
  feedback_incorrect?: string | null
  difficulty_level?: string
  question_order?: number
}

export type listening_contentsUpdateManyMutationInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  question?: Prisma.StringFieldUpdateOperationsInput | string
  audio_url?: Prisma.StringFieldUpdateOperationsInput | string
  image_options?: Prisma.StringFieldUpdateOperationsInput | string
  correct_answer?: Prisma.IntFieldUpdateOperationsInput | number
  feedback_correct?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  feedback_incorrect?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  difficulty_level?: Prisma.StringFieldUpdateOperationsInput | string
  question_order?: Prisma.IntFieldUpdateOperationsInput | number
}

export type listening_contentsUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  lesson_id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  question?: Prisma.StringFieldUpdateOperationsInput | string
  audio_url?: Prisma.StringFieldUpdateOperationsInput | string
  image_options?: Prisma.StringFieldUpdateOperationsInput | string
  correct_answer?: Prisma.IntFieldUpdateOperationsInput | number
  feedback_correct?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  feedback_incorrect?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  difficulty_level?: Prisma.StringFieldUpdateOperationsInput | string
  question_order?: Prisma.IntFieldUpdateOperationsInput | number
}

export type Listening_contentsListRelationFilter = {
  every?: Prisma.listening_contentsWhereInput
  some?: Prisma.listening_contentsWhereInput
  none?: Prisma.listening_contentsWhereInput
}

export type listening_contentsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type listening_contentsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  lesson_id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  question?: Prisma.SortOrder
  audio_url?: Prisma.SortOrder
  image_options?: Prisma.SortOrder
  correct_answer?: Prisma.SortOrder
  feedback_correct?: Prisma.SortOrder
  feedback_incorrect?: Prisma.SortOrder
  difficulty_level?: Prisma.SortOrder
  question_order?: Prisma.SortOrder
}

export type listening_contentsAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  lesson_id?: Prisma.SortOrder
  correct_answer?: Prisma.SortOrder
  question_order?: Prisma.SortOrder
}

export type listening_contentsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  lesson_id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  question?: Prisma.SortOrder
  audio_url?: Prisma.SortOrder
  image_options?: Prisma.SortOrder
  correct_answer?: Prisma.SortOrder
  feedback_correct?: Prisma.SortOrder
  feedback_incorrect?: Prisma.SortOrder
  difficulty_level?: Prisma.SortOrder
  question_order?: Prisma.SortOrder
}

export type listening_contentsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  lesson_id?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  question?: Prisma.SortOrder
  audio_url?: Prisma.SortOrder
  image_options?: Prisma.SortOrder
  correct_answer?: Prisma.SortOrder
  feedback_correct?: Prisma.SortOrder
  feedback_incorrect?: Prisma.SortOrder
  difficulty_level?: Prisma.SortOrder
  question_order?: Prisma.SortOrder
}

export type listening_contentsSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  lesson_id?: Prisma.SortOrder
  correct_answer?: Prisma.SortOrder
  question_order?: Prisma.SortOrder
}

export type listening_contentsCreateNestedManyWithoutLessonsInput = {
  create?: Prisma.XOR<Prisma.listening_contentsCreateWithoutLessonsInput, Prisma.listening_contentsUncheckedCreateWithoutLessonsInput> | Prisma.listening_contentsCreateWithoutLessonsInput[] | Prisma.listening_contentsUncheckedCreateWithoutLessonsInput[]
  connectOrCreate?: Prisma.listening_contentsCreateOrConnectWithoutLessonsInput | Prisma.listening_contentsCreateOrConnectWithoutLessonsInput[]
  createMany?: Prisma.listening_contentsCreateManyLessonsInputEnvelope
  connect?: Prisma.listening_contentsWhereUniqueInput | Prisma.listening_contentsWhereUniqueInput[]
}

export type listening_contentsUncheckedCreateNestedManyWithoutLessonsInput = {
  create?: Prisma.XOR<Prisma.listening_contentsCreateWithoutLessonsInput, Prisma.listening_contentsUncheckedCreateWithoutLessonsInput> | Prisma.listening_contentsCreateWithoutLessonsInput[] | Prisma.listening_contentsUncheckedCreateWithoutLessonsInput[]
  connectOrCreate?: Prisma.listening_contentsCreateOrConnectWithoutLessonsInput | Prisma.listening_contentsCreateOrConnectWithoutLessonsInput[]
  createMany?: Prisma.listening_contentsCreateManyLessonsInputEnvelope
  connect?: Prisma.listening_contentsWhereUniqueInput | Prisma.listening_contentsWhereUniqueInput[]
}

export type listening_contentsUpdateManyWithoutLessonsNestedInput = {
  create?: Prisma.XOR<Prisma.listening_contentsCreateWithoutLessonsInput, Prisma.listening_contentsUncheckedCreateWithoutLessonsInput> | Prisma.listening_contentsCreateWithoutLessonsInput[] | Prisma.listening_contentsUncheckedCreateWithoutLessonsInput[]
  connectOrCreate?: Prisma.listening_contentsCreateOrConnectWithoutLessonsInput | Prisma.listening_contentsCreateOrConnectWithoutLessonsInput[]
  upsert?: Prisma.listening_contentsUpsertWithWhereUniqueWithoutLessonsInput | Prisma.listening_contentsUpsertWithWhereUniqueWithoutLessonsInput[]
  createMany?: Prisma.listening_contentsCreateManyLessonsInputEnvelope
  set?: Prisma.listening_contentsWhereUniqueInput | Prisma.listening_contentsWhereUniqueInput[]
  disconnect?: Prisma.listening_contentsWhereUniqueInput | Prisma.listening_contentsWhereUniqueInput[]
  delete?: Prisma.listening_contentsWhereUniqueInput | Prisma.listening_contentsWhereUniqueInput[]
  connect?: Prisma.listening_contentsWhereUniqueInput | Prisma.listening_contentsWhereUniqueInput[]
  update?: Prisma.listening_contentsUpdateWithWhereUniqueWithoutLessonsInput | Prisma.listening_contentsUpdateWithWhereUniqueWithoutLessonsInput[]
  updateMany?: Prisma.listening_contentsUpdateManyWithWhereWithoutLessonsInput | Prisma.listening_contentsUpdateManyWithWhereWithoutLessonsInput[]
  deleteMany?: Prisma.listening_contentsScalarWhereInput | Prisma.listening_contentsScalarWhereInput[]
}

export type listening_contentsUncheckedUpdateManyWithoutLessonsNestedInput = {
  create?: Prisma.XOR<Prisma.listening_contentsCreateWithoutLessonsInput, Prisma.listening_contentsUncheckedCreateWithoutLessonsInput> | Prisma.listening_contentsCreateWithoutLessonsInput[] | Prisma.listening_contentsUncheckedCreateWithoutLessonsInput[]
  connectOrCreate?: Prisma.listening_contentsCreateOrConnectWithoutLessonsInput | Prisma.listening_contentsCreateOrConnectWithoutLessonsInput[]
  upsert?: Prisma.listening_contentsUpsertWithWhereUniqueWithoutLessonsInput | Prisma.listening_contentsUpsertWithWhereUniqueWithoutLessonsInput[]
  createMany?: Prisma.listening_contentsCreateManyLessonsInputEnvelope
  set?: Prisma.listening_contentsWhereUniqueInput | Prisma.listening_contentsWhereUniqueInput[]
  disconnect?: Prisma.listening_contentsWhereUniqueInput | Prisma.listening_contentsWhereUniqueInput[]
  delete?: Prisma.listening_contentsWhereUniqueInput | Prisma.listening_contentsWhereUniqueInput[]
  connect?: Prisma.listening_contentsWhereUniqueInput | Prisma.listening_contentsWhereUniqueInput[]
  update?: Prisma.listening_contentsUpdateWithWhereUniqueWithoutLessonsInput | Prisma.listening_contentsUpdateWithWhereUniqueWithoutLessonsInput[]
  updateMany?: Prisma.listening_contentsUpdateManyWithWhereWithoutLessonsInput | Prisma.listening_contentsUpdateManyWithWhereWithoutLessonsInput[]
  deleteMany?: Prisma.listening_contentsScalarWhereInput | Prisma.listening_contentsScalarWhereInput[]
}

export type listening_contentsCreateWithoutLessonsInput = {
  title: string
  description?: string | null
  question: string
  audio_url: string
  image_options: string
  correct_answer: number
  feedback_correct?: string | null
  feedback_incorrect?: string | null
  difficulty_level?: string
  question_order?: number
}

export type listening_contentsUncheckedCreateWithoutLessonsInput = {
  id?: number
  title: string
  description?: string | null
  question: string
  audio_url: string
  image_options: string
  correct_answer: number
  feedback_correct?: string | null
  feedback_incorrect?: string | null
  difficulty_level?: string
  question_order?: number
}

export type listening_contentsCreateOrConnectWithoutLessonsInput = {
  where: Prisma.listening_contentsWhereUniqueInput
  create: Prisma.XOR<Prisma.listening_contentsCreateWithoutLessonsInput, Prisma.listening_contentsUncheckedCreateWithoutLessonsInput>
}

export type listening_contentsCreateManyLessonsInputEnvelope = {
  data: Prisma.listening_contentsCreateManyLessonsInput | Prisma.listening_contentsCreateManyLessonsInput[]
  skipDuplicates?: boolean
}

export type listening_contentsUpsertWithWhereUniqueWithoutLessonsInput = {
  where: Prisma.listening_contentsWhereUniqueInput
  update: Prisma.XOR<Prisma.listening_contentsUpdateWithoutLessonsInput, Prisma.listening_contentsUncheckedUpdateWithoutLessonsInput>
  create: Prisma.XOR<Prisma.listening_contentsCreateWithoutLessonsInput, Prisma.listening_contentsUncheckedCreateWithoutLessonsInput>
}

export type listening_contentsUpdateWithWhereUniqueWithoutLessonsInput = {
  where: Prisma.listening_contentsWhereUniqueInput
  data: Prisma.XOR<Prisma.listening_contentsUpdateWithoutLessonsInput, Prisma.listening_contentsUncheckedUpdateWithoutLessonsInput>
}

export type listening_contentsUpdateManyWithWhereWithoutLessonsInput = {
  where: Prisma.listening_contentsScalarWhereInput
  data: Prisma.XOR<Prisma.listening_contentsUpdateManyMutationInput, Prisma.listening_contentsUncheckedUpdateManyWithoutLessonsInput>
}

export type listening_contentsScalarWhereInput = {
  AND?: Prisma.listening_contentsScalarWhereInput | Prisma.listening_contentsScalarWhereInput[]
  OR?: Prisma.listening_contentsScalarWhereInput[]
  NOT?: Prisma.listening_contentsScalarWhereInput | Prisma.listening_contentsScalarWhereInput[]
  id?: Prisma.IntFilter<"listening_contents"> | number
  lesson_id?: Prisma.IntFilter<"listening_contents"> | number
  title?: Prisma.StringFilter<"listening_contents"> | string
  description?: Prisma.StringNullableFilter<"listening_contents"> | string | null
  question?: Prisma.StringFilter<"listening_contents"> | string
  audio_url?: Prisma.StringFilter<"listening_contents"> | string
  image_options?: Prisma.StringFilter<"listening_contents"> | string
  correct_answer?: Prisma.IntFilter<"listening_contents"> | number
  feedback_correct?: Prisma.StringNullableFilter<"listening_contents"> | string | null
  feedback_incorrect?: Prisma.StringNullableFilter<"listening_contents"> | string | null
  difficulty_level?: Prisma.StringFilter<"listening_contents"> | string
  question_order?: Prisma.IntFilter<"listening_contents"> | number
}

export type listening_contentsCreateManyLessonsInput = {
  id?: number
  title: string
  description?: string | null
  question: string
  audio_url: string
  image_options: string
  correct_answer: number
  feedback_correct?: string | null
  feedback_incorrect?: string | null
  difficulty_level?: string
  question_order?: number
}

export type listening_contentsUpdateWithoutLessonsInput = {
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  question?: Prisma.StringFieldUpdateOperationsInput | string
  audio_url?: Prisma.StringFieldUpdateOperationsInput | string
  image_options?: Prisma.StringFieldUpdateOperationsInput | string
  correct_answer?: Prisma.IntFieldUpdateOperationsInput | number
  feedback_correct?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  feedback_incorrect?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  difficulty_level?: Prisma.StringFieldUpdateOperationsInput | string
  question_order?: Prisma.IntFieldUpdateOperationsInput | number
}

export type listening_contentsUncheckedUpdateWithoutLessonsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  question?: Prisma.StringFieldUpdateOperationsInput | string
  audio_url?: Prisma.StringFieldUpdateOperationsInput | string
  image_options?: Prisma.StringFieldUpdateOperationsInput | string
  correct_answer?: Prisma.IntFieldUpdateOperationsInput | number
  feedback_correct?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  feedback_incorrect?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  difficulty_level?: Prisma.StringFieldUpdateOperationsInput | string
  question_order?: Prisma.IntFieldUpdateOperationsInput | number
}

export type listening_contentsUncheckedUpdateManyWithoutLessonsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  question?: Prisma.StringFieldUpdateOperationsInput | string
  audio_url?: Prisma.StringFieldUpdateOperationsInput | string
  image_options?: Prisma.StringFieldUpdateOperationsInput | string
  correct_answer?: Prisma.IntFieldUpdateOperationsInput | number
  feedback_correct?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  feedback_incorrect?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  difficulty_level?: Prisma.StringFieldUpdateOperationsInput | string
  question_order?: Prisma.IntFieldUpdateOperationsInput | number
}



export type listening_contentsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  lesson_id?: boolean
  title?: boolean
  description?: boolean
  question?: boolean
  audio_url?: boolean
  image_options?: boolean
  correct_answer?: boolean
  feedback_correct?: boolean
  feedback_incorrect?: boolean
  difficulty_level?: boolean
  question_order?: boolean
  lessons?: boolean | Prisma.lessonsDefaultArgs<ExtArgs>
}, ExtArgs["result"]["listening_contents"]>

export type listening_contentsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  lesson_id?: boolean
  title?: boolean
  description?: boolean
  question?: boolean
  audio_url?: boolean
  image_options?: boolean
  correct_answer?: boolean
  feedback_correct?: boolean
  feedback_incorrect?: boolean
  difficulty_level?: boolean
  question_order?: boolean
  lessons?: boolean | Prisma.lessonsDefaultArgs<ExtArgs>
}, ExtArgs["result"]["listening_contents"]>

export type listening_contentsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  lesson_id?: boolean
  title?: boolean
  description?: boolean
  question?: boolean
  audio_url?: boolean
  image_options?: boolean
  correct_answer?: boolean
  feedback_correct?: boolean
  feedback_incorrect?: boolean
  difficulty_level?: boolean
  question_order?: boolean
  lessons?: boolean | Prisma.lessonsDefaultArgs<ExtArgs>
}, ExtArgs["result"]["listening_contents"]>

export type listening_contentsSelectScalar = {
  id?: boolean
  lesson_id?: boolean
  title?: boolean
  description?: boolean
  question?: boolean
  audio_url?: boolean
  image_options?: boolean
  correct_answer?: boolean
  feedback_correct?: boolean
  feedback_incorrect?: boolean
  difficulty_level?: boolean
  question_order?: boolean
}

export type listening_contentsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "lesson_id" | "title" | "description" | "question" | "audio_url" | "image_options" | "correct_answer" | "feedback_correct" | "feedback_incorrect" | "difficulty_level" | "question_order", ExtArgs["result"]["listening_contents"]>
export type listening_contentsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  lessons?: boolean | Prisma.lessonsDefaultArgs<ExtArgs>
}
export type listening_contentsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  lessons?: boolean | Prisma.lessonsDefaultArgs<ExtArgs>
}
export type listening_contentsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  lessons?: boolean | Prisma.lessonsDefaultArgs<ExtArgs>
}

export type $listening_contentsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "listening_contents"
  objects: {
    lessons: Prisma.$lessonsPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    lesson_id: number
    /**
     * Exercise title
     */
    title: string
    /**
     * Exercise description
     */
    description: string | null
    /**
     * Question or prompt
     */
    question: string
    /**
     * Audio clip URL
     */
    audio_url: string
    /**
     * Image options (JSON array with image URLs and descriptions)
     */
    image_options: string
    /**
     * Correct answer index (position in image_options array)
     */
    correct_answer: number
    /**
     * Feedback for correct answer
     */
    feedback_correct: string | null
    /**
     * Feedback for incorrect answers
     */
    feedback_incorrect: string | null
    /**
     * Difficulty level: beginner, intermediate, advanced
     */
    difficulty_level: string
    /**
     * Order of questions within the lesson
     */
    question_order: number
  }, ExtArgs["result"]["listening_contents"]>
  composites: {}
}

export type listening_contentsGetPayload<S extends boolean | null | undefined | listening_contentsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$listening_contentsPayload, S>

export type listening_contentsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<listening_contentsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Listening_contentsCountAggregateInputType | true
  }

export interface listening_contentsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['listening_contents'], meta: { name: 'listening_contents' } }
  /**
   * Find zero or one Listening_contents that matches the filter.
   * @param {listening_contentsFindUniqueArgs} args - Arguments to find a Listening_contents
   * @example
   * // Get one Listening_contents
   * const listening_contents = await prisma.listening_contents.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends listening_contentsFindUniqueArgs>(args: Prisma.SelectSubset<T, listening_contentsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__listening_contentsClient<runtime.Types.Result.GetResult<Prisma.$listening_contentsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Listening_contents that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {listening_contentsFindUniqueOrThrowArgs} args - Arguments to find a Listening_contents
   * @example
   * // Get one Listening_contents
   * const listening_contents = await prisma.listening_contents.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends listening_contentsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, listening_contentsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__listening_contentsClient<runtime.Types.Result.GetResult<Prisma.$listening_contentsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Listening_contents that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {listening_contentsFindFirstArgs} args - Arguments to find a Listening_contents
   * @example
   * // Get one Listening_contents
   * const listening_contents = await prisma.listening_contents.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends listening_contentsFindFirstArgs>(args?: Prisma.SelectSubset<T, listening_contentsFindFirstArgs<ExtArgs>>): Prisma.Prisma__listening_contentsClient<runtime.Types.Result.GetResult<Prisma.$listening_contentsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Listening_contents that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {listening_contentsFindFirstOrThrowArgs} args - Arguments to find a Listening_contents
   * @example
   * // Get one Listening_contents
   * const listening_contents = await prisma.listening_contents.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends listening_contentsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, listening_contentsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__listening_contentsClient<runtime.Types.Result.GetResult<Prisma.$listening_contentsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Listening_contents that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {listening_contentsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Listening_contents
   * const listening_contents = await prisma.listening_contents.findMany()
   * 
   * // Get first 10 Listening_contents
   * const listening_contents = await prisma.listening_contents.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const listening_contentsWithIdOnly = await prisma.listening_contents.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends listening_contentsFindManyArgs>(args?: Prisma.SelectSubset<T, listening_contentsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$listening_contentsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Listening_contents.
   * @param {listening_contentsCreateArgs} args - Arguments to create a Listening_contents.
   * @example
   * // Create one Listening_contents
   * const Listening_contents = await prisma.listening_contents.create({
   *   data: {
   *     // ... data to create a Listening_contents
   *   }
   * })
   * 
   */
  create<T extends listening_contentsCreateArgs>(args: Prisma.SelectSubset<T, listening_contentsCreateArgs<ExtArgs>>): Prisma.Prisma__listening_contentsClient<runtime.Types.Result.GetResult<Prisma.$listening_contentsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Listening_contents.
   * @param {listening_contentsCreateManyArgs} args - Arguments to create many Listening_contents.
   * @example
   * // Create many Listening_contents
   * const listening_contents = await prisma.listening_contents.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends listening_contentsCreateManyArgs>(args?: Prisma.SelectSubset<T, listening_contentsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Listening_contents and returns the data saved in the database.
   * @param {listening_contentsCreateManyAndReturnArgs} args - Arguments to create many Listening_contents.
   * @example
   * // Create many Listening_contents
   * const listening_contents = await prisma.listening_contents.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Listening_contents and only return the `id`
   * const listening_contentsWithIdOnly = await prisma.listening_contents.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends listening_contentsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, listening_contentsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$listening_contentsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Listening_contents.
   * @param {listening_contentsDeleteArgs} args - Arguments to delete one Listening_contents.
   * @example
   * // Delete one Listening_contents
   * const Listening_contents = await prisma.listening_contents.delete({
   *   where: {
   *     // ... filter to delete one Listening_contents
   *   }
   * })
   * 
   */
  delete<T extends listening_contentsDeleteArgs>(args: Prisma.SelectSubset<T, listening_contentsDeleteArgs<ExtArgs>>): Prisma.Prisma__listening_contentsClient<runtime.Types.Result.GetResult<Prisma.$listening_contentsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Listening_contents.
   * @param {listening_contentsUpdateArgs} args - Arguments to update one Listening_contents.
   * @example
   * // Update one Listening_contents
   * const listening_contents = await prisma.listening_contents.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends listening_contentsUpdateArgs>(args: Prisma.SelectSubset<T, listening_contentsUpdateArgs<ExtArgs>>): Prisma.Prisma__listening_contentsClient<runtime.Types.Result.GetResult<Prisma.$listening_contentsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Listening_contents.
   * @param {listening_contentsDeleteManyArgs} args - Arguments to filter Listening_contents to delete.
   * @example
   * // Delete a few Listening_contents
   * const { count } = await prisma.listening_contents.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends listening_contentsDeleteManyArgs>(args?: Prisma.SelectSubset<T, listening_contentsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Listening_contents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {listening_contentsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Listening_contents
   * const listening_contents = await prisma.listening_contents.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends listening_contentsUpdateManyArgs>(args: Prisma.SelectSubset<T, listening_contentsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Listening_contents and returns the data updated in the database.
   * @param {listening_contentsUpdateManyAndReturnArgs} args - Arguments to update many Listening_contents.
   * @example
   * // Update many Listening_contents
   * const listening_contents = await prisma.listening_contents.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Listening_contents and only return the `id`
   * const listening_contentsWithIdOnly = await prisma.listening_contents.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends listening_contentsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, listening_contentsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$listening_contentsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Listening_contents.
   * @param {listening_contentsUpsertArgs} args - Arguments to update or create a Listening_contents.
   * @example
   * // Update or create a Listening_contents
   * const listening_contents = await prisma.listening_contents.upsert({
   *   create: {
   *     // ... data to create a Listening_contents
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Listening_contents we want to update
   *   }
   * })
   */
  upsert<T extends listening_contentsUpsertArgs>(args: Prisma.SelectSubset<T, listening_contentsUpsertArgs<ExtArgs>>): Prisma.Prisma__listening_contentsClient<runtime.Types.Result.GetResult<Prisma.$listening_contentsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Listening_contents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {listening_contentsCountArgs} args - Arguments to filter Listening_contents to count.
   * @example
   * // Count the number of Listening_contents
   * const count = await prisma.listening_contents.count({
   *   where: {
   *     // ... the filter for the Listening_contents we want to count
   *   }
   * })
  **/
  count<T extends listening_contentsCountArgs>(
    args?: Prisma.Subset<T, listening_contentsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Listening_contentsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Listening_contents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Listening_contentsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Listening_contentsAggregateArgs>(args: Prisma.Subset<T, Listening_contentsAggregateArgs>): Prisma.PrismaPromise<GetListening_contentsAggregateType<T>>

  /**
   * Group by Listening_contents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {listening_contentsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends listening_contentsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: listening_contentsGroupByArgs['orderBy'] }
      : { orderBy?: listening_contentsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, listening_contentsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetListening_contentsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the listening_contents model
 */
readonly fields: listening_contentsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for listening_contents.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__listening_contentsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  lessons<T extends Prisma.lessonsDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.lessonsDefaultArgs<ExtArgs>>): Prisma.Prisma__lessonsClient<runtime.Types.Result.GetResult<Prisma.$lessonsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the listening_contents model
 */
export interface listening_contentsFieldRefs {
  readonly id: Prisma.FieldRef<"listening_contents", 'Int'>
  readonly lesson_id: Prisma.FieldRef<"listening_contents", 'Int'>
  readonly title: Prisma.FieldRef<"listening_contents", 'String'>
  readonly description: Prisma.FieldRef<"listening_contents", 'String'>
  readonly question: Prisma.FieldRef<"listening_contents", 'String'>
  readonly audio_url: Prisma.FieldRef<"listening_contents", 'String'>
  readonly image_options: Prisma.FieldRef<"listening_contents", 'String'>
  readonly correct_answer: Prisma.FieldRef<"listening_contents", 'Int'>
  readonly feedback_correct: Prisma.FieldRef<"listening_contents", 'String'>
  readonly feedback_incorrect: Prisma.FieldRef<"listening_contents", 'String'>
  readonly difficulty_level: Prisma.FieldRef<"listening_contents", 'String'>
  readonly question_order: Prisma.FieldRef<"listening_contents", 'Int'>
}
    

// Custom InputTypes
/**
 * listening_contents findUnique
 */
export type listening_contentsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the listening_contents
   */
  select?: Prisma.listening_contentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the listening_contents
   */
  omit?: Prisma.listening_contentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.listening_contentsInclude<ExtArgs> | null
  /**
   * Filter, which listening_contents to fetch.
   */
  where: Prisma.listening_contentsWhereUniqueInput
}

/**
 * listening_contents findUniqueOrThrow
 */
export type listening_contentsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the listening_contents
   */
  select?: Prisma.listening_contentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the listening_contents
   */
  omit?: Prisma.listening_contentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.listening_contentsInclude<ExtArgs> | null
  /**
   * Filter, which listening_contents to fetch.
   */
  where: Prisma.listening_contentsWhereUniqueInput
}

/**
 * listening_contents findFirst
 */
export type listening_contentsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the listening_contents
   */
  select?: Prisma.listening_contentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the listening_contents
   */
  omit?: Prisma.listening_contentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.listening_contentsInclude<ExtArgs> | null
  /**
   * Filter, which listening_contents to fetch.
   */
  where?: Prisma.listening_contentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of listening_contents to fetch.
   */
  orderBy?: Prisma.listening_contentsOrderByWithRelationInput | Prisma.listening_contentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for listening_contents.
   */
  cursor?: Prisma.listening_contentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` listening_contents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` listening_contents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of listening_contents.
   */
  distinct?: Prisma.Listening_contentsScalarFieldEnum | Prisma.Listening_contentsScalarFieldEnum[]
}

/**
 * listening_contents findFirstOrThrow
 */
export type listening_contentsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the listening_contents
   */
  select?: Prisma.listening_contentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the listening_contents
   */
  omit?: Prisma.listening_contentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.listening_contentsInclude<ExtArgs> | null
  /**
   * Filter, which listening_contents to fetch.
   */
  where?: Prisma.listening_contentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of listening_contents to fetch.
   */
  orderBy?: Prisma.listening_contentsOrderByWithRelationInput | Prisma.listening_contentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for listening_contents.
   */
  cursor?: Prisma.listening_contentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` listening_contents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` listening_contents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of listening_contents.
   */
  distinct?: Prisma.Listening_contentsScalarFieldEnum | Prisma.Listening_contentsScalarFieldEnum[]
}

/**
 * listening_contents findMany
 */
export type listening_contentsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the listening_contents
   */
  select?: Prisma.listening_contentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the listening_contents
   */
  omit?: Prisma.listening_contentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.listening_contentsInclude<ExtArgs> | null
  /**
   * Filter, which listening_contents to fetch.
   */
  where?: Prisma.listening_contentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of listening_contents to fetch.
   */
  orderBy?: Prisma.listening_contentsOrderByWithRelationInput | Prisma.listening_contentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing listening_contents.
   */
  cursor?: Prisma.listening_contentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` listening_contents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` listening_contents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of listening_contents.
   */
  distinct?: Prisma.Listening_contentsScalarFieldEnum | Prisma.Listening_contentsScalarFieldEnum[]
}

/**
 * listening_contents create
 */
export type listening_contentsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the listening_contents
   */
  select?: Prisma.listening_contentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the listening_contents
   */
  omit?: Prisma.listening_contentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.listening_contentsInclude<ExtArgs> | null
  /**
   * The data needed to create a listening_contents.
   */
  data: Prisma.XOR<Prisma.listening_contentsCreateInput, Prisma.listening_contentsUncheckedCreateInput>
}

/**
 * listening_contents createMany
 */
export type listening_contentsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many listening_contents.
   */
  data: Prisma.listening_contentsCreateManyInput | Prisma.listening_contentsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * listening_contents createManyAndReturn
 */
export type listening_contentsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the listening_contents
   */
  select?: Prisma.listening_contentsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the listening_contents
   */
  omit?: Prisma.listening_contentsOmit<ExtArgs> | null
  /**
   * The data used to create many listening_contents.
   */
  data: Prisma.listening_contentsCreateManyInput | Prisma.listening_contentsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.listening_contentsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * listening_contents update
 */
export type listening_contentsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the listening_contents
   */
  select?: Prisma.listening_contentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the listening_contents
   */
  omit?: Prisma.listening_contentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.listening_contentsInclude<ExtArgs> | null
  /**
   * The data needed to update a listening_contents.
   */
  data: Prisma.XOR<Prisma.listening_contentsUpdateInput, Prisma.listening_contentsUncheckedUpdateInput>
  /**
   * Choose, which listening_contents to update.
   */
  where: Prisma.listening_contentsWhereUniqueInput
}

/**
 * listening_contents updateMany
 */
export type listening_contentsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update listening_contents.
   */
  data: Prisma.XOR<Prisma.listening_contentsUpdateManyMutationInput, Prisma.listening_contentsUncheckedUpdateManyInput>
  /**
   * Filter which listening_contents to update
   */
  where?: Prisma.listening_contentsWhereInput
  /**
   * Limit how many listening_contents to update.
   */
  limit?: number
}

/**
 * listening_contents updateManyAndReturn
 */
export type listening_contentsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the listening_contents
   */
  select?: Prisma.listening_contentsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the listening_contents
   */
  omit?: Prisma.listening_contentsOmit<ExtArgs> | null
  /**
   * The data used to update listening_contents.
   */
  data: Prisma.XOR<Prisma.listening_contentsUpdateManyMutationInput, Prisma.listening_contentsUncheckedUpdateManyInput>
  /**
   * Filter which listening_contents to update
   */
  where?: Prisma.listening_contentsWhereInput
  /**
   * Limit how many listening_contents to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.listening_contentsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * listening_contents upsert
 */
export type listening_contentsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the listening_contents
   */
  select?: Prisma.listening_contentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the listening_contents
   */
  omit?: Prisma.listening_contentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.listening_contentsInclude<ExtArgs> | null
  /**
   * The filter to search for the listening_contents to update in case it exists.
   */
  where: Prisma.listening_contentsWhereUniqueInput
  /**
   * In case the listening_contents found by the `where` argument doesn't exist, create a new listening_contents with this data.
   */
  create: Prisma.XOR<Prisma.listening_contentsCreateInput, Prisma.listening_contentsUncheckedCreateInput>
  /**
   * In case the listening_contents was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.listening_contentsUpdateInput, Prisma.listening_contentsUncheckedUpdateInput>
}

/**
 * listening_contents delete
 */
export type listening_contentsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the listening_contents
   */
  select?: Prisma.listening_contentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the listening_contents
   */
  omit?: Prisma.listening_contentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.listening_contentsInclude<ExtArgs> | null
  /**
   * Filter which listening_contents to delete.
   */
  where: Prisma.listening_contentsWhereUniqueInput
}

/**
 * listening_contents deleteMany
 */
export type listening_contentsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which listening_contents to delete
   */
  where?: Prisma.listening_contentsWhereInput
  /**
   * Limit how many listening_contents to delete.
   */
  limit?: number
}

/**
 * listening_contents without action
 */
export type listening_contentsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the listening_contents
   */
  select?: Prisma.listening_contentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the listening_contents
   */
  omit?: Prisma.listening_contentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.listening_contentsInclude<ExtArgs> | null
}
