
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `topics` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model topics
 * Represents a learning module within a course (e.g., "Greetings", "Numbers").
 * Topics contain lessons and organize curriculum hierarchically.
 */
export type topicsModel = runtime.Types.Result.DefaultSelection<Prisma.$topicsPayload>

export type AggregateTopics = {
  _count: TopicsCountAggregateOutputType | null
  _avg: TopicsAvgAggregateOutputType | null
  _sum: TopicsSumAggregateOutputType | null
  _min: TopicsMinAggregateOutputType | null
  _max: TopicsMaxAggregateOutputType | null
}

export type TopicsAvgAggregateOutputType = {
  id: number | null
}

export type TopicsSumAggregateOutputType = {
  id: number | null
}

export type TopicsMinAggregateOutputType = {
  id: number | null
  slug: string | null
  title: string | null
  course_slug: string | null
}

export type TopicsMaxAggregateOutputType = {
  id: number | null
  slug: string | null
  title: string | null
  course_slug: string | null
}

export type TopicsCountAggregateOutputType = {
  id: number
  slug: number
  title: number
  course_slug: number
  _all: number
}


export type TopicsAvgAggregateInputType = {
  id?: true
}

export type TopicsSumAggregateInputType = {
  id?: true
}

export type TopicsMinAggregateInputType = {
  id?: true
  slug?: true
  title?: true
  course_slug?: true
}

export type TopicsMaxAggregateInputType = {
  id?: true
  slug?: true
  title?: true
  course_slug?: true
}

export type TopicsCountAggregateInputType = {
  id?: true
  slug?: true
  title?: true
  course_slug?: true
  _all?: true
}

export type TopicsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which topics to aggregate.
   */
  where?: Prisma.topicsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of topics to fetch.
   */
  orderBy?: Prisma.topicsOrderByWithRelationInput | Prisma.topicsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.topicsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` topics from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` topics.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned topics
  **/
  _count?: true | TopicsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: TopicsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: TopicsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: TopicsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: TopicsMaxAggregateInputType
}

export type GetTopicsAggregateType<T extends TopicsAggregateArgs> = {
      [P in keyof T & keyof AggregateTopics]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateTopics[P]>
    : Prisma.GetScalarType<T[P], AggregateTopics[P]>
}




export type topicsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.topicsWhereInput
  orderBy?: Prisma.topicsOrderByWithAggregationInput | Prisma.topicsOrderByWithAggregationInput[]
  by: Prisma.TopicsScalarFieldEnum[] | Prisma.TopicsScalarFieldEnum
  having?: Prisma.topicsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: TopicsCountAggregateInputType | true
  _avg?: TopicsAvgAggregateInputType
  _sum?: TopicsSumAggregateInputType
  _min?: TopicsMinAggregateInputType
  _max?: TopicsMaxAggregateInputType
}

export type TopicsGroupByOutputType = {
  id: number
  slug: string
  title: string
  course_slug: string
  _count: TopicsCountAggregateOutputType | null
  _avg: TopicsAvgAggregateOutputType | null
  _sum: TopicsSumAggregateOutputType | null
  _min: TopicsMinAggregateOutputType | null
  _max: TopicsMaxAggregateOutputType | null
}

export type GetTopicsGroupByPayload<T extends topicsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<TopicsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof TopicsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], TopicsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], TopicsGroupByOutputType[P]>
      }
    >
  >



export type topicsWhereInput = {
  AND?: Prisma.topicsWhereInput | Prisma.topicsWhereInput[]
  OR?: Prisma.topicsWhereInput[]
  NOT?: Prisma.topicsWhereInput | Prisma.topicsWhereInput[]
  id?: Prisma.IntFilter<"topics"> | number
  slug?: Prisma.StringFilter<"topics"> | string
  title?: Prisma.StringFilter<"topics"> | string
  course_slug?: Prisma.StringFilter<"topics"> | string
  lessons?: Prisma.LessonsListRelationFilter
  courses?: Prisma.XOR<Prisma.CoursesScalarRelationFilter, Prisma.coursesWhereInput>
}

export type topicsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  title?: Prisma.SortOrder
  course_slug?: Prisma.SortOrder
  lessons?: Prisma.lessonsOrderByRelationAggregateInput
  courses?: Prisma.coursesOrderByWithRelationInput
}

export type topicsWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  slug?: string
  AND?: Prisma.topicsWhereInput | Prisma.topicsWhereInput[]
  OR?: Prisma.topicsWhereInput[]
  NOT?: Prisma.topicsWhereInput | Prisma.topicsWhereInput[]
  title?: Prisma.StringFilter<"topics"> | string
  course_slug?: Prisma.StringFilter<"topics"> | string
  lessons?: Prisma.LessonsListRelationFilter
  courses?: Prisma.XOR<Prisma.CoursesScalarRelationFilter, Prisma.coursesWhereInput>
}, "id" | "slug">

export type topicsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  title?: Prisma.SortOrder
  course_slug?: Prisma.SortOrder
  _count?: Prisma.topicsCountOrderByAggregateInput
  _avg?: Prisma.topicsAvgOrderByAggregateInput
  _max?: Prisma.topicsMaxOrderByAggregateInput
  _min?: Prisma.topicsMinOrderByAggregateInput
  _sum?: Prisma.topicsSumOrderByAggregateInput
}

export type topicsScalarWhereWithAggregatesInput = {
  AND?: Prisma.topicsScalarWhereWithAggregatesInput | Prisma.topicsScalarWhereWithAggregatesInput[]
  OR?: Prisma.topicsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.topicsScalarWhereWithAggregatesInput | Prisma.topicsScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"topics"> | number
  slug?: Prisma.StringWithAggregatesFilter<"topics"> | string
  title?: Prisma.StringWithAggregatesFilter<"topics"> | string
  course_slug?: Prisma.StringWithAggregatesFilter<"topics"> | string
}

export type topicsCreateInput = {
  slug: string
  title: string
  lessons?: Prisma.lessonsCreateNestedManyWithoutTopicsInput
  courses: Prisma.coursesCreateNestedOneWithoutTopicsInput
}

export type topicsUncheckedCreateInput = {
  id?: number
  slug: string
  title: string
  course_slug: string
  lessons?: Prisma.lessonsUncheckedCreateNestedManyWithoutTopicsInput
}

export type topicsUpdateInput = {
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  lessons?: Prisma.lessonsUpdateManyWithoutTopicsNestedInput
  courses?: Prisma.coursesUpdateOneRequiredWithoutTopicsNestedInput
}

export type topicsUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  course_slug?: Prisma.StringFieldUpdateOperationsInput | string
  lessons?: Prisma.lessonsUncheckedUpdateManyWithoutTopicsNestedInput
}

export type topicsCreateManyInput = {
  id?: number
  slug: string
  title: string
  course_slug: string
}

export type topicsUpdateManyMutationInput = {
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
}

export type topicsUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  course_slug?: Prisma.StringFieldUpdateOperationsInput | string
}

export type TopicsListRelationFilter = {
  every?: Prisma.topicsWhereInput
  some?: Prisma.topicsWhereInput
  none?: Prisma.topicsWhereInput
}

export type topicsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type topicsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  title?: Prisma.SortOrder
  course_slug?: Prisma.SortOrder
}

export type topicsAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type topicsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  title?: Prisma.SortOrder
  course_slug?: Prisma.SortOrder
}

export type topicsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  slug?: Prisma.SortOrder
  title?: Prisma.SortOrder
  course_slug?: Prisma.SortOrder
}

export type topicsSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type TopicsScalarRelationFilter = {
  is?: Prisma.topicsWhereInput
  isNot?: Prisma.topicsWhereInput
}

export type topicsCreateNestedManyWithoutCoursesInput = {
  create?: Prisma.XOR<Prisma.topicsCreateWithoutCoursesInput, Prisma.topicsUncheckedCreateWithoutCoursesInput> | Prisma.topicsCreateWithoutCoursesInput[] | Prisma.topicsUncheckedCreateWithoutCoursesInput[]
  connectOrCreate?: Prisma.topicsCreateOrConnectWithoutCoursesInput | Prisma.topicsCreateOrConnectWithoutCoursesInput[]
  createMany?: Prisma.topicsCreateManyCoursesInputEnvelope
  connect?: Prisma.topicsWhereUniqueInput | Prisma.topicsWhereUniqueInput[]
}

export type topicsUncheckedCreateNestedManyWithoutCoursesInput = {
  create?: Prisma.XOR<Prisma.topicsCreateWithoutCoursesInput, Prisma.topicsUncheckedCreateWithoutCoursesInput> | Prisma.topicsCreateWithoutCoursesInput[] | Prisma.topicsUncheckedCreateWithoutCoursesInput[]
  connectOrCreate?: Prisma.topicsCreateOrConnectWithoutCoursesInput | Prisma.topicsCreateOrConnectWithoutCoursesInput[]
  createMany?: Prisma.topicsCreateManyCoursesInputEnvelope
  connect?: Prisma.topicsWhereUniqueInput | Prisma.topicsWhereUniqueInput[]
}

export type topicsUpdateManyWithoutCoursesNestedInput = {
  create?: Prisma.XOR<Prisma.topicsCreateWithoutCoursesInput, Prisma.topicsUncheckedCreateWithoutCoursesInput> | Prisma.topicsCreateWithoutCoursesInput[] | Prisma.topicsUncheckedCreateWithoutCoursesInput[]
  connectOrCreate?: Prisma.topicsCreateOrConnectWithoutCoursesInput | Prisma.topicsCreateOrConnectWithoutCoursesInput[]
  upsert?: Prisma.topicsUpsertWithWhereUniqueWithoutCoursesInput | Prisma.topicsUpsertWithWhereUniqueWithoutCoursesInput[]
  createMany?: Prisma.topicsCreateManyCoursesInputEnvelope
  set?: Prisma.topicsWhereUniqueInput | Prisma.topicsWhereUniqueInput[]
  disconnect?: Prisma.topicsWhereUniqueInput | Prisma.topicsWhereUniqueInput[]
  delete?: Prisma.topicsWhereUniqueInput | Prisma.topicsWhereUniqueInput[]
  connect?: Prisma.topicsWhereUniqueInput | Prisma.topicsWhereUniqueInput[]
  update?: Prisma.topicsUpdateWithWhereUniqueWithoutCoursesInput | Prisma.topicsUpdateWithWhereUniqueWithoutCoursesInput[]
  updateMany?: Prisma.topicsUpdateManyWithWhereWithoutCoursesInput | Prisma.topicsUpdateManyWithWhereWithoutCoursesInput[]
  deleteMany?: Prisma.topicsScalarWhereInput | Prisma.topicsScalarWhereInput[]
}

export type topicsUncheckedUpdateManyWithoutCoursesNestedInput = {
  create?: Prisma.XOR<Prisma.topicsCreateWithoutCoursesInput, Prisma.topicsUncheckedCreateWithoutCoursesInput> | Prisma.topicsCreateWithoutCoursesInput[] | Prisma.topicsUncheckedCreateWithoutCoursesInput[]
  connectOrCreate?: Prisma.topicsCreateOrConnectWithoutCoursesInput | Prisma.topicsCreateOrConnectWithoutCoursesInput[]
  upsert?: Prisma.topicsUpsertWithWhereUniqueWithoutCoursesInput | Prisma.topicsUpsertWithWhereUniqueWithoutCoursesInput[]
  createMany?: Prisma.topicsCreateManyCoursesInputEnvelope
  set?: Prisma.topicsWhereUniqueInput | Prisma.topicsWhereUniqueInput[]
  disconnect?: Prisma.topicsWhereUniqueInput | Prisma.topicsWhereUniqueInput[]
  delete?: Prisma.topicsWhereUniqueInput | Prisma.topicsWhereUniqueInput[]
  connect?: Prisma.topicsWhereUniqueInput | Prisma.topicsWhereUniqueInput[]
  update?: Prisma.topicsUpdateWithWhereUniqueWithoutCoursesInput | Prisma.topicsUpdateWithWhereUniqueWithoutCoursesInput[]
  updateMany?: Prisma.topicsUpdateManyWithWhereWithoutCoursesInput | Prisma.topicsUpdateManyWithWhereWithoutCoursesInput[]
  deleteMany?: Prisma.topicsScalarWhereInput | Prisma.topicsScalarWhereInput[]
}

export type topicsCreateNestedOneWithoutLessonsInput = {
  create?: Prisma.XOR<Prisma.topicsCreateWithoutLessonsInput, Prisma.topicsUncheckedCreateWithoutLessonsInput>
  connectOrCreate?: Prisma.topicsCreateOrConnectWithoutLessonsInput
  connect?: Prisma.topicsWhereUniqueInput
}

export type topicsUpdateOneRequiredWithoutLessonsNestedInput = {
  create?: Prisma.XOR<Prisma.topicsCreateWithoutLessonsInput, Prisma.topicsUncheckedCreateWithoutLessonsInput>
  connectOrCreate?: Prisma.topicsCreateOrConnectWithoutLessonsInput
  upsert?: Prisma.topicsUpsertWithoutLessonsInput
  connect?: Prisma.topicsWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.topicsUpdateToOneWithWhereWithoutLessonsInput, Prisma.topicsUpdateWithoutLessonsInput>, Prisma.topicsUncheckedUpdateWithoutLessonsInput>
}

export type topicsCreateWithoutCoursesInput = {
  slug: string
  title: string
  lessons?: Prisma.lessonsCreateNestedManyWithoutTopicsInput
}

export type topicsUncheckedCreateWithoutCoursesInput = {
  id?: number
  slug: string
  title: string
  lessons?: Prisma.lessonsUncheckedCreateNestedManyWithoutTopicsInput
}

export type topicsCreateOrConnectWithoutCoursesInput = {
  where: Prisma.topicsWhereUniqueInput
  create: Prisma.XOR<Prisma.topicsCreateWithoutCoursesInput, Prisma.topicsUncheckedCreateWithoutCoursesInput>
}

export type topicsCreateManyCoursesInputEnvelope = {
  data: Prisma.topicsCreateManyCoursesInput | Prisma.topicsCreateManyCoursesInput[]
  skipDuplicates?: boolean
}

export type topicsUpsertWithWhereUniqueWithoutCoursesInput = {
  where: Prisma.topicsWhereUniqueInput
  update: Prisma.XOR<Prisma.topicsUpdateWithoutCoursesInput, Prisma.topicsUncheckedUpdateWithoutCoursesInput>
  create: Prisma.XOR<Prisma.topicsCreateWithoutCoursesInput, Prisma.topicsUncheckedCreateWithoutCoursesInput>
}

export type topicsUpdateWithWhereUniqueWithoutCoursesInput = {
  where: Prisma.topicsWhereUniqueInput
  data: Prisma.XOR<Prisma.topicsUpdateWithoutCoursesInput, Prisma.topicsUncheckedUpdateWithoutCoursesInput>
}

export type topicsUpdateManyWithWhereWithoutCoursesInput = {
  where: Prisma.topicsScalarWhereInput
  data: Prisma.XOR<Prisma.topicsUpdateManyMutationInput, Prisma.topicsUncheckedUpdateManyWithoutCoursesInput>
}

export type topicsScalarWhereInput = {
  AND?: Prisma.topicsScalarWhereInput | Prisma.topicsScalarWhereInput[]
  OR?: Prisma.topicsScalarWhereInput[]
  NOT?: Prisma.topicsScalarWhereInput | Prisma.topicsScalarWhereInput[]
  id?: Prisma.IntFilter<"topics"> | number
  slug?: Prisma.StringFilter<"topics"> | string
  title?: Prisma.StringFilter<"topics"> | string
  course_slug?: Prisma.StringFilter<"topics"> | string
}

export type topicsCreateWithoutLessonsInput = {
  slug: string
  title: string
  courses: Prisma.coursesCreateNestedOneWithoutTopicsInput
}

export type topicsUncheckedCreateWithoutLessonsInput = {
  id?: number
  slug: string
  title: string
  course_slug: string
}

export type topicsCreateOrConnectWithoutLessonsInput = {
  where: Prisma.topicsWhereUniqueInput
  create: Prisma.XOR<Prisma.topicsCreateWithoutLessonsInput, Prisma.topicsUncheckedCreateWithoutLessonsInput>
}

export type topicsUpsertWithoutLessonsInput = {
  update: Prisma.XOR<Prisma.topicsUpdateWithoutLessonsInput, Prisma.topicsUncheckedUpdateWithoutLessonsInput>
  create: Prisma.XOR<Prisma.topicsCreateWithoutLessonsInput, Prisma.topicsUncheckedCreateWithoutLessonsInput>
  where?: Prisma.topicsWhereInput
}

export type topicsUpdateToOneWithWhereWithoutLessonsInput = {
  where?: Prisma.topicsWhereInput
  data: Prisma.XOR<Prisma.topicsUpdateWithoutLessonsInput, Prisma.topicsUncheckedUpdateWithoutLessonsInput>
}

export type topicsUpdateWithoutLessonsInput = {
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  courses?: Prisma.coursesUpdateOneRequiredWithoutTopicsNestedInput
}

export type topicsUncheckedUpdateWithoutLessonsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  course_slug?: Prisma.StringFieldUpdateOperationsInput | string
}

export type topicsCreateManyCoursesInput = {
  id?: number
  slug: string
  title: string
}

export type topicsUpdateWithoutCoursesInput = {
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  lessons?: Prisma.lessonsUpdateManyWithoutTopicsNestedInput
}

export type topicsUncheckedUpdateWithoutCoursesInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
  lessons?: Prisma.lessonsUncheckedUpdateManyWithoutTopicsNestedInput
}

export type topicsUncheckedUpdateManyWithoutCoursesInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  slug?: Prisma.StringFieldUpdateOperationsInput | string
  title?: Prisma.StringFieldUpdateOperationsInput | string
}


/**
 * Count Type TopicsCountOutputType
 */

export type TopicsCountOutputType = {
  lessons: number
}

export type TopicsCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  lessons?: boolean | TopicsCountOutputTypeCountLessonsArgs
}

/**
 * TopicsCountOutputType without action
 */
export type TopicsCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TopicsCountOutputType
   */
  select?: Prisma.TopicsCountOutputTypeSelect<ExtArgs> | null
}

/**
 * TopicsCountOutputType without action
 */
export type TopicsCountOutputTypeCountLessonsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.lessonsWhereInput
}


export type topicsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  slug?: boolean
  title?: boolean
  course_slug?: boolean
  lessons?: boolean | Prisma.topics$lessonsArgs<ExtArgs>
  courses?: boolean | Prisma.coursesDefaultArgs<ExtArgs>
  _count?: boolean | Prisma.TopicsCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["topics"]>

export type topicsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  slug?: boolean
  title?: boolean
  course_slug?: boolean
  courses?: boolean | Prisma.coursesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["topics"]>

export type topicsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  slug?: boolean
  title?: boolean
  course_slug?: boolean
  courses?: boolean | Prisma.coursesDefaultArgs<ExtArgs>
}, ExtArgs["result"]["topics"]>

export type topicsSelectScalar = {
  id?: boolean
  slug?: boolean
  title?: boolean
  course_slug?: boolean
}

export type topicsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "slug" | "title" | "course_slug", ExtArgs["result"]["topics"]>
export type topicsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  lessons?: boolean | Prisma.topics$lessonsArgs<ExtArgs>
  courses?: boolean | Prisma.coursesDefaultArgs<ExtArgs>
  _count?: boolean | Prisma.TopicsCountOutputTypeDefaultArgs<ExtArgs>
}
export type topicsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  courses?: boolean | Prisma.coursesDefaultArgs<ExtArgs>
}
export type topicsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  courses?: boolean | Prisma.coursesDefaultArgs<ExtArgs>
}

export type $topicsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "topics"
  objects: {
    lessons: Prisma.$lessonsPayload<ExtArgs>[]
    courses: Prisma.$coursesPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    slug: string
    title: string
    course_slug: string
  }, ExtArgs["result"]["topics"]>
  composites: {}
}

export type topicsGetPayload<S extends boolean | null | undefined | topicsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$topicsPayload, S>

export type topicsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<topicsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: TopicsCountAggregateInputType | true
  }

export interface topicsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['topics'], meta: { name: 'topics' } }
  /**
   * Find zero or one Topics that matches the filter.
   * @param {topicsFindUniqueArgs} args - Arguments to find a Topics
   * @example
   * // Get one Topics
   * const topics = await prisma.topics.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends topicsFindUniqueArgs>(args: Prisma.SelectSubset<T, topicsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__topicsClient<runtime.Types.Result.GetResult<Prisma.$topicsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Topics that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {topicsFindUniqueOrThrowArgs} args - Arguments to find a Topics
   * @example
   * // Get one Topics
   * const topics = await prisma.topics.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends topicsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, topicsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__topicsClient<runtime.Types.Result.GetResult<Prisma.$topicsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Topics that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {topicsFindFirstArgs} args - Arguments to find a Topics
   * @example
   * // Get one Topics
   * const topics = await prisma.topics.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends topicsFindFirstArgs>(args?: Prisma.SelectSubset<T, topicsFindFirstArgs<ExtArgs>>): Prisma.Prisma__topicsClient<runtime.Types.Result.GetResult<Prisma.$topicsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Topics that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {topicsFindFirstOrThrowArgs} args - Arguments to find a Topics
   * @example
   * // Get one Topics
   * const topics = await prisma.topics.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends topicsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, topicsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__topicsClient<runtime.Types.Result.GetResult<Prisma.$topicsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Topics that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {topicsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Topics
   * const topics = await prisma.topics.findMany()
   * 
   * // Get first 10 Topics
   * const topics = await prisma.topics.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const topicsWithIdOnly = await prisma.topics.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends topicsFindManyArgs>(args?: Prisma.SelectSubset<T, topicsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$topicsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Topics.
   * @param {topicsCreateArgs} args - Arguments to create a Topics.
   * @example
   * // Create one Topics
   * const Topics = await prisma.topics.create({
   *   data: {
   *     // ... data to create a Topics
   *   }
   * })
   * 
   */
  create<T extends topicsCreateArgs>(args: Prisma.SelectSubset<T, topicsCreateArgs<ExtArgs>>): Prisma.Prisma__topicsClient<runtime.Types.Result.GetResult<Prisma.$topicsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Topics.
   * @param {topicsCreateManyArgs} args - Arguments to create many Topics.
   * @example
   * // Create many Topics
   * const topics = await prisma.topics.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends topicsCreateManyArgs>(args?: Prisma.SelectSubset<T, topicsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Topics and returns the data saved in the database.
   * @param {topicsCreateManyAndReturnArgs} args - Arguments to create many Topics.
   * @example
   * // Create many Topics
   * const topics = await prisma.topics.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Topics and only return the `id`
   * const topicsWithIdOnly = await prisma.topics.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends topicsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, topicsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$topicsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Topics.
   * @param {topicsDeleteArgs} args - Arguments to delete one Topics.
   * @example
   * // Delete one Topics
   * const Topics = await prisma.topics.delete({
   *   where: {
   *     // ... filter to delete one Topics
   *   }
   * })
   * 
   */
  delete<T extends topicsDeleteArgs>(args: Prisma.SelectSubset<T, topicsDeleteArgs<ExtArgs>>): Prisma.Prisma__topicsClient<runtime.Types.Result.GetResult<Prisma.$topicsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Topics.
   * @param {topicsUpdateArgs} args - Arguments to update one Topics.
   * @example
   * // Update one Topics
   * const topics = await prisma.topics.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends topicsUpdateArgs>(args: Prisma.SelectSubset<T, topicsUpdateArgs<ExtArgs>>): Prisma.Prisma__topicsClient<runtime.Types.Result.GetResult<Prisma.$topicsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Topics.
   * @param {topicsDeleteManyArgs} args - Arguments to filter Topics to delete.
   * @example
   * // Delete a few Topics
   * const { count } = await prisma.topics.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends topicsDeleteManyArgs>(args?: Prisma.SelectSubset<T, topicsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Topics.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {topicsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Topics
   * const topics = await prisma.topics.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends topicsUpdateManyArgs>(args: Prisma.SelectSubset<T, topicsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Topics and returns the data updated in the database.
   * @param {topicsUpdateManyAndReturnArgs} args - Arguments to update many Topics.
   * @example
   * // Update many Topics
   * const topics = await prisma.topics.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Topics and only return the `id`
   * const topicsWithIdOnly = await prisma.topics.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends topicsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, topicsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$topicsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Topics.
   * @param {topicsUpsertArgs} args - Arguments to update or create a Topics.
   * @example
   * // Update or create a Topics
   * const topics = await prisma.topics.upsert({
   *   create: {
   *     // ... data to create a Topics
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Topics we want to update
   *   }
   * })
   */
  upsert<T extends topicsUpsertArgs>(args: Prisma.SelectSubset<T, topicsUpsertArgs<ExtArgs>>): Prisma.Prisma__topicsClient<runtime.Types.Result.GetResult<Prisma.$topicsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Topics.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {topicsCountArgs} args - Arguments to filter Topics to count.
   * @example
   * // Count the number of Topics
   * const count = await prisma.topics.count({
   *   where: {
   *     // ... the filter for the Topics we want to count
   *   }
   * })
  **/
  count<T extends topicsCountArgs>(
    args?: Prisma.Subset<T, topicsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], TopicsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Topics.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {TopicsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends TopicsAggregateArgs>(args: Prisma.Subset<T, TopicsAggregateArgs>): Prisma.PrismaPromise<GetTopicsAggregateType<T>>

  /**
   * Group by Topics.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {topicsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends topicsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: topicsGroupByArgs['orderBy'] }
      : { orderBy?: topicsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, topicsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetTopicsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the topics model
 */
readonly fields: topicsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for topics.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__topicsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  lessons<T extends Prisma.topics$lessonsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.topics$lessonsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$lessonsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  courses<T extends Prisma.coursesDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.coursesDefaultArgs<ExtArgs>>): Prisma.Prisma__coursesClient<runtime.Types.Result.GetResult<Prisma.$coursesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the topics model
 */
export interface topicsFieldRefs {
  readonly id: Prisma.FieldRef<"topics", 'Int'>
  readonly slug: Prisma.FieldRef<"topics", 'String'>
  readonly title: Prisma.FieldRef<"topics", 'String'>
  readonly course_slug: Prisma.FieldRef<"topics", 'String'>
}
    

// Custom InputTypes
/**
 * topics findUnique
 */
export type topicsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the topics
   */
  select?: Prisma.topicsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the topics
   */
  omit?: Prisma.topicsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.topicsInclude<ExtArgs> | null
  /**
   * Filter, which topics to fetch.
   */
  where: Prisma.topicsWhereUniqueInput
}

/**
 * topics findUniqueOrThrow
 */
export type topicsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the topics
   */
  select?: Prisma.topicsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the topics
   */
  omit?: Prisma.topicsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.topicsInclude<ExtArgs> | null
  /**
   * Filter, which topics to fetch.
   */
  where: Prisma.topicsWhereUniqueInput
}

/**
 * topics findFirst
 */
export type topicsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the topics
   */
  select?: Prisma.topicsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the topics
   */
  omit?: Prisma.topicsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.topicsInclude<ExtArgs> | null
  /**
   * Filter, which topics to fetch.
   */
  where?: Prisma.topicsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of topics to fetch.
   */
  orderBy?: Prisma.topicsOrderByWithRelationInput | Prisma.topicsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for topics.
   */
  cursor?: Prisma.topicsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` topics from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` topics.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of topics.
   */
  distinct?: Prisma.TopicsScalarFieldEnum | Prisma.TopicsScalarFieldEnum[]
}

/**
 * topics findFirstOrThrow
 */
export type topicsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the topics
   */
  select?: Prisma.topicsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the topics
   */
  omit?: Prisma.topicsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.topicsInclude<ExtArgs> | null
  /**
   * Filter, which topics to fetch.
   */
  where?: Prisma.topicsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of topics to fetch.
   */
  orderBy?: Prisma.topicsOrderByWithRelationInput | Prisma.topicsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for topics.
   */
  cursor?: Prisma.topicsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` topics from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` topics.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of topics.
   */
  distinct?: Prisma.TopicsScalarFieldEnum | Prisma.TopicsScalarFieldEnum[]
}

/**
 * topics findMany
 */
export type topicsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the topics
   */
  select?: Prisma.topicsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the topics
   */
  omit?: Prisma.topicsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.topicsInclude<ExtArgs> | null
  /**
   * Filter, which topics to fetch.
   */
  where?: Prisma.topicsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of topics to fetch.
   */
  orderBy?: Prisma.topicsOrderByWithRelationInput | Prisma.topicsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing topics.
   */
  cursor?: Prisma.topicsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` topics from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` topics.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of topics.
   */
  distinct?: Prisma.TopicsScalarFieldEnum | Prisma.TopicsScalarFieldEnum[]
}

/**
 * topics create
 */
export type topicsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the topics
   */
  select?: Prisma.topicsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the topics
   */
  omit?: Prisma.topicsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.topicsInclude<ExtArgs> | null
  /**
   * The data needed to create a topics.
   */
  data: Prisma.XOR<Prisma.topicsCreateInput, Prisma.topicsUncheckedCreateInput>
}

/**
 * topics createMany
 */
export type topicsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many topics.
   */
  data: Prisma.topicsCreateManyInput | Prisma.topicsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * topics createManyAndReturn
 */
export type topicsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the topics
   */
  select?: Prisma.topicsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the topics
   */
  omit?: Prisma.topicsOmit<ExtArgs> | null
  /**
   * The data used to create many topics.
   */
  data: Prisma.topicsCreateManyInput | Prisma.topicsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.topicsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * topics update
 */
export type topicsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the topics
   */
  select?: Prisma.topicsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the topics
   */
  omit?: Prisma.topicsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.topicsInclude<ExtArgs> | null
  /**
   * The data needed to update a topics.
   */
  data: Prisma.XOR<Prisma.topicsUpdateInput, Prisma.topicsUncheckedUpdateInput>
  /**
   * Choose, which topics to update.
   */
  where: Prisma.topicsWhereUniqueInput
}

/**
 * topics updateMany
 */
export type topicsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update topics.
   */
  data: Prisma.XOR<Prisma.topicsUpdateManyMutationInput, Prisma.topicsUncheckedUpdateManyInput>
  /**
   * Filter which topics to update
   */
  where?: Prisma.topicsWhereInput
  /**
   * Limit how many topics to update.
   */
  limit?: number
}

/**
 * topics updateManyAndReturn
 */
export type topicsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the topics
   */
  select?: Prisma.topicsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the topics
   */
  omit?: Prisma.topicsOmit<ExtArgs> | null
  /**
   * The data used to update topics.
   */
  data: Prisma.XOR<Prisma.topicsUpdateManyMutationInput, Prisma.topicsUncheckedUpdateManyInput>
  /**
   * Filter which topics to update
   */
  where?: Prisma.topicsWhereInput
  /**
   * Limit how many topics to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.topicsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * topics upsert
 */
export type topicsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the topics
   */
  select?: Prisma.topicsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the topics
   */
  omit?: Prisma.topicsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.topicsInclude<ExtArgs> | null
  /**
   * The filter to search for the topics to update in case it exists.
   */
  where: Prisma.topicsWhereUniqueInput
  /**
   * In case the topics found by the `where` argument doesn't exist, create a new topics with this data.
   */
  create: Prisma.XOR<Prisma.topicsCreateInput, Prisma.topicsUncheckedCreateInput>
  /**
   * In case the topics was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.topicsUpdateInput, Prisma.topicsUncheckedUpdateInput>
}

/**
 * topics delete
 */
export type topicsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the topics
   */
  select?: Prisma.topicsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the topics
   */
  omit?: Prisma.topicsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.topicsInclude<ExtArgs> | null
  /**
   * Filter which topics to delete.
   */
  where: Prisma.topicsWhereUniqueInput
}

/**
 * topics deleteMany
 */
export type topicsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which topics to delete
   */
  where?: Prisma.topicsWhereInput
  /**
   * Limit how many topics to delete.
   */
  limit?: number
}

/**
 * topics.lessons
 */
export type topics$lessonsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the lessons
   */
  select?: Prisma.lessonsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the lessons
   */
  omit?: Prisma.lessonsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.lessonsInclude<ExtArgs> | null
  where?: Prisma.lessonsWhereInput
  orderBy?: Prisma.lessonsOrderByWithRelationInput | Prisma.lessonsOrderByWithRelationInput[]
  cursor?: Prisma.lessonsWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.LessonsScalarFieldEnum | Prisma.LessonsScalarFieldEnum[]
}

/**
 * topics without action
 */
export type topicsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the topics
   */
  select?: Prisma.topicsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the topics
   */
  omit?: Prisma.topicsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.topicsInclude<ExtArgs> | null
}
