
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `video_contents` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model video_contents
 * Stores video lesson content with metadata.
 * Duration is tracked in seconds with a default of 600s (10 minutes).
 */
export type video_contentsModel = runtime.Types.Result.DefaultSelection<Prisma.$video_contentsPayload>

export type AggregateVideo_contents = {
  _count: Video_contentsCountAggregateOutputType | null
  _avg: Video_contentsAvgAggregateOutputType | null
  _sum: Video_contentsSumAggregateOutputType | null
  _min: Video_contentsMinAggregateOutputType | null
  _max: Video_contentsMaxAggregateOutputType | null
}

export type Video_contentsAvgAggregateOutputType = {
  id: number | null
  lesson_id: number | null
  duration: number | null
}

export type Video_contentsSumAggregateOutputType = {
  id: number | null
  lesson_id: number | null
  duration: number | null
}

export type Video_contentsMinAggregateOutputType = {
  id: number | null
  lesson_id: number | null
  url: string | null
  description: string | null
  duration: number | null
}

export type Video_contentsMaxAggregateOutputType = {
  id: number | null
  lesson_id: number | null
  url: string | null
  description: string | null
  duration: number | null
}

export type Video_contentsCountAggregateOutputType = {
  id: number
  lesson_id: number
  url: number
  description: number
  duration: number
  _all: number
}


export type Video_contentsAvgAggregateInputType = {
  id?: true
  lesson_id?: true
  duration?: true
}

export type Video_contentsSumAggregateInputType = {
  id?: true
  lesson_id?: true
  duration?: true
}

export type Video_contentsMinAggregateInputType = {
  id?: true
  lesson_id?: true
  url?: true
  description?: true
  duration?: true
}

export type Video_contentsMaxAggregateInputType = {
  id?: true
  lesson_id?: true
  url?: true
  description?: true
  duration?: true
}

export type Video_contentsCountAggregateInputType = {
  id?: true
  lesson_id?: true
  url?: true
  description?: true
  duration?: true
  _all?: true
}

export type Video_contentsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which video_contents to aggregate.
   */
  where?: Prisma.video_contentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of video_contents to fetch.
   */
  orderBy?: Prisma.video_contentsOrderByWithRelationInput | Prisma.video_contentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.video_contentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` video_contents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` video_contents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned video_contents
  **/
  _count?: true | Video_contentsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Video_contentsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Video_contentsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Video_contentsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Video_contentsMaxAggregateInputType
}

export type GetVideo_contentsAggregateType<T extends Video_contentsAggregateArgs> = {
      [P in keyof T & keyof AggregateVideo_contents]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateVideo_contents[P]>
    : Prisma.GetScalarType<T[P], AggregateVideo_contents[P]>
}




export type video_contentsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.video_contentsWhereInput
  orderBy?: Prisma.video_contentsOrderByWithAggregationInput | Prisma.video_contentsOrderByWithAggregationInput[]
  by: Prisma.Video_contentsScalarFieldEnum[] | Prisma.Video_contentsScalarFieldEnum
  having?: Prisma.video_contentsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Video_contentsCountAggregateInputType | true
  _avg?: Video_contentsAvgAggregateInputType
  _sum?: Video_contentsSumAggregateInputType
  _min?: Video_contentsMinAggregateInputType
  _max?: Video_contentsMaxAggregateInputType
}

export type Video_contentsGroupByOutputType = {
  id: number
  lesson_id: number
  url: string
  description: string | null
  duration: number | null
  _count: Video_contentsCountAggregateOutputType | null
  _avg: Video_contentsAvgAggregateOutputType | null
  _sum: Video_contentsSumAggregateOutputType | null
  _min: Video_contentsMinAggregateOutputType | null
  _max: Video_contentsMaxAggregateOutputType | null
}

export type GetVideo_contentsGroupByPayload<T extends video_contentsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Video_contentsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Video_contentsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Video_contentsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Video_contentsGroupByOutputType[P]>
      }
    >
  >



export type video_contentsWhereInput = {
  AND?: Prisma.video_contentsWhereInput | Prisma.video_contentsWhereInput[]
  OR?: Prisma.video_contentsWhereInput[]
  NOT?: Prisma.video_contentsWhereInput | Prisma.video_contentsWhereInput[]
  id?: Prisma.IntFilter<"video_contents"> | number
  lesson_id?: Prisma.IntFilter<"video_contents"> | number
  url?: Prisma.StringFilter<"video_contents"> | string
  description?: Prisma.StringNullableFilter<"video_contents"> | string | null
  duration?: Prisma.IntNullableFilter<"video_contents"> | number | null
  lessons?: Prisma.XOR<Prisma.LessonsScalarRelationFilter, Prisma.lessonsWhereInput>
}

export type video_contentsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  lesson_id?: Prisma.SortOrder
  url?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  duration?: Prisma.SortOrderInput | Prisma.SortOrder
  lessons?: Prisma.lessonsOrderByWithRelationInput
}

export type video_contentsWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.video_contentsWhereInput | Prisma.video_contentsWhereInput[]
  OR?: Prisma.video_contentsWhereInput[]
  NOT?: Prisma.video_contentsWhereInput | Prisma.video_contentsWhereInput[]
  lesson_id?: Prisma.IntFilter<"video_contents"> | number
  url?: Prisma.StringFilter<"video_contents"> | string
  description?: Prisma.StringNullableFilter<"video_contents"> | string | null
  duration?: Prisma.IntNullableFilter<"video_contents"> | number | null
  lessons?: Prisma.XOR<Prisma.LessonsScalarRelationFilter, Prisma.lessonsWhereInput>
}, "id">

export type video_contentsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  lesson_id?: Prisma.SortOrder
  url?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  duration?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.video_contentsCountOrderByAggregateInput
  _avg?: Prisma.video_contentsAvgOrderByAggregateInput
  _max?: Prisma.video_contentsMaxOrderByAggregateInput
  _min?: Prisma.video_contentsMinOrderByAggregateInput
  _sum?: Prisma.video_contentsSumOrderByAggregateInput
}

export type video_contentsScalarWhereWithAggregatesInput = {
  AND?: Prisma.video_contentsScalarWhereWithAggregatesInput | Prisma.video_contentsScalarWhereWithAggregatesInput[]
  OR?: Prisma.video_contentsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.video_contentsScalarWhereWithAggregatesInput | Prisma.video_contentsScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"video_contents"> | number
  lesson_id?: Prisma.IntWithAggregatesFilter<"video_contents"> | number
  url?: Prisma.StringWithAggregatesFilter<"video_contents"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"video_contents"> | string | null
  duration?: Prisma.IntNullableWithAggregatesFilter<"video_contents"> | number | null
}

export type video_contentsCreateInput = {
  url: string
  description?: string | null
  duration?: number | null
  lessons: Prisma.lessonsCreateNestedOneWithoutVideo_contentsInput
}

export type video_contentsUncheckedCreateInput = {
  id?: number
  lesson_id: number
  url: string
  description?: string | null
  duration?: number | null
}

export type video_contentsUpdateInput = {
  url?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  duration?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  lessons?: Prisma.lessonsUpdateOneRequiredWithoutVideo_contentsNestedInput
}

export type video_contentsUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  lesson_id?: Prisma.IntFieldUpdateOperationsInput | number
  url?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  duration?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type video_contentsCreateManyInput = {
  id?: number
  lesson_id: number
  url: string
  description?: string | null
  duration?: number | null
}

export type video_contentsUpdateManyMutationInput = {
  url?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  duration?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type video_contentsUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  lesson_id?: Prisma.IntFieldUpdateOperationsInput | number
  url?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  duration?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type Video_contentsListRelationFilter = {
  every?: Prisma.video_contentsWhereInput
  some?: Prisma.video_contentsWhereInput
  none?: Prisma.video_contentsWhereInput
}

export type video_contentsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type video_contentsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  lesson_id?: Prisma.SortOrder
  url?: Prisma.SortOrder
  description?: Prisma.SortOrder
  duration?: Prisma.SortOrder
}

export type video_contentsAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  lesson_id?: Prisma.SortOrder
  duration?: Prisma.SortOrder
}

export type video_contentsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  lesson_id?: Prisma.SortOrder
  url?: Prisma.SortOrder
  description?: Prisma.SortOrder
  duration?: Prisma.SortOrder
}

export type video_contentsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  lesson_id?: Prisma.SortOrder
  url?: Prisma.SortOrder
  description?: Prisma.SortOrder
  duration?: Prisma.SortOrder
}

export type video_contentsSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  lesson_id?: Prisma.SortOrder
  duration?: Prisma.SortOrder
}

export type video_contentsCreateNestedManyWithoutLessonsInput = {
  create?: Prisma.XOR<Prisma.video_contentsCreateWithoutLessonsInput, Prisma.video_contentsUncheckedCreateWithoutLessonsInput> | Prisma.video_contentsCreateWithoutLessonsInput[] | Prisma.video_contentsUncheckedCreateWithoutLessonsInput[]
  connectOrCreate?: Prisma.video_contentsCreateOrConnectWithoutLessonsInput | Prisma.video_contentsCreateOrConnectWithoutLessonsInput[]
  createMany?: Prisma.video_contentsCreateManyLessonsInputEnvelope
  connect?: Prisma.video_contentsWhereUniqueInput | Prisma.video_contentsWhereUniqueInput[]
}

export type video_contentsUncheckedCreateNestedManyWithoutLessonsInput = {
  create?: Prisma.XOR<Prisma.video_contentsCreateWithoutLessonsInput, Prisma.video_contentsUncheckedCreateWithoutLessonsInput> | Prisma.video_contentsCreateWithoutLessonsInput[] | Prisma.video_contentsUncheckedCreateWithoutLessonsInput[]
  connectOrCreate?: Prisma.video_contentsCreateOrConnectWithoutLessonsInput | Prisma.video_contentsCreateOrConnectWithoutLessonsInput[]
  createMany?: Prisma.video_contentsCreateManyLessonsInputEnvelope
  connect?: Prisma.video_contentsWhereUniqueInput | Prisma.video_contentsWhereUniqueInput[]
}

export type video_contentsUpdateManyWithoutLessonsNestedInput = {
  create?: Prisma.XOR<Prisma.video_contentsCreateWithoutLessonsInput, Prisma.video_contentsUncheckedCreateWithoutLessonsInput> | Prisma.video_contentsCreateWithoutLessonsInput[] | Prisma.video_contentsUncheckedCreateWithoutLessonsInput[]
  connectOrCreate?: Prisma.video_contentsCreateOrConnectWithoutLessonsInput | Prisma.video_contentsCreateOrConnectWithoutLessonsInput[]
  upsert?: Prisma.video_contentsUpsertWithWhereUniqueWithoutLessonsInput | Prisma.video_contentsUpsertWithWhereUniqueWithoutLessonsInput[]
  createMany?: Prisma.video_contentsCreateManyLessonsInputEnvelope
  set?: Prisma.video_contentsWhereUniqueInput | Prisma.video_contentsWhereUniqueInput[]
  disconnect?: Prisma.video_contentsWhereUniqueInput | Prisma.video_contentsWhereUniqueInput[]
  delete?: Prisma.video_contentsWhereUniqueInput | Prisma.video_contentsWhereUniqueInput[]
  connect?: Prisma.video_contentsWhereUniqueInput | Prisma.video_contentsWhereUniqueInput[]
  update?: Prisma.video_contentsUpdateWithWhereUniqueWithoutLessonsInput | Prisma.video_contentsUpdateWithWhereUniqueWithoutLessonsInput[]
  updateMany?: Prisma.video_contentsUpdateManyWithWhereWithoutLessonsInput | Prisma.video_contentsUpdateManyWithWhereWithoutLessonsInput[]
  deleteMany?: Prisma.video_contentsScalarWhereInput | Prisma.video_contentsScalarWhereInput[]
}

export type video_contentsUncheckedUpdateManyWithoutLessonsNestedInput = {
  create?: Prisma.XOR<Prisma.video_contentsCreateWithoutLessonsInput, Prisma.video_contentsUncheckedCreateWithoutLessonsInput> | Prisma.video_contentsCreateWithoutLessonsInput[] | Prisma.video_contentsUncheckedCreateWithoutLessonsInput[]
  connectOrCreate?: Prisma.video_contentsCreateOrConnectWithoutLessonsInput | Prisma.video_contentsCreateOrConnectWithoutLessonsInput[]
  upsert?: Prisma.video_contentsUpsertWithWhereUniqueWithoutLessonsInput | Prisma.video_contentsUpsertWithWhereUniqueWithoutLessonsInput[]
  createMany?: Prisma.video_contentsCreateManyLessonsInputEnvelope
  set?: Prisma.video_contentsWhereUniqueInput | Prisma.video_contentsWhereUniqueInput[]
  disconnect?: Prisma.video_contentsWhereUniqueInput | Prisma.video_contentsWhereUniqueInput[]
  delete?: Prisma.video_contentsWhereUniqueInput | Prisma.video_contentsWhereUniqueInput[]
  connect?: Prisma.video_contentsWhereUniqueInput | Prisma.video_contentsWhereUniqueInput[]
  update?: Prisma.video_contentsUpdateWithWhereUniqueWithoutLessonsInput | Prisma.video_contentsUpdateWithWhereUniqueWithoutLessonsInput[]
  updateMany?: Prisma.video_contentsUpdateManyWithWhereWithoutLessonsInput | Prisma.video_contentsUpdateManyWithWhereWithoutLessonsInput[]
  deleteMany?: Prisma.video_contentsScalarWhereInput | Prisma.video_contentsScalarWhereInput[]
}

export type NullableIntFieldUpdateOperationsInput = {
  set?: number | null
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type video_contentsCreateWithoutLessonsInput = {
  url: string
  description?: string | null
  duration?: number | null
}

export type video_contentsUncheckedCreateWithoutLessonsInput = {
  id?: number
  url: string
  description?: string | null
  duration?: number | null
}

export type video_contentsCreateOrConnectWithoutLessonsInput = {
  where: Prisma.video_contentsWhereUniqueInput
  create: Prisma.XOR<Prisma.video_contentsCreateWithoutLessonsInput, Prisma.video_contentsUncheckedCreateWithoutLessonsInput>
}

export type video_contentsCreateManyLessonsInputEnvelope = {
  data: Prisma.video_contentsCreateManyLessonsInput | Prisma.video_contentsCreateManyLessonsInput[]
  skipDuplicates?: boolean
}

export type video_contentsUpsertWithWhereUniqueWithoutLessonsInput = {
  where: Prisma.video_contentsWhereUniqueInput
  update: Prisma.XOR<Prisma.video_contentsUpdateWithoutLessonsInput, Prisma.video_contentsUncheckedUpdateWithoutLessonsInput>
  create: Prisma.XOR<Prisma.video_contentsCreateWithoutLessonsInput, Prisma.video_contentsUncheckedCreateWithoutLessonsInput>
}

export type video_contentsUpdateWithWhereUniqueWithoutLessonsInput = {
  where: Prisma.video_contentsWhereUniqueInput
  data: Prisma.XOR<Prisma.video_contentsUpdateWithoutLessonsInput, Prisma.video_contentsUncheckedUpdateWithoutLessonsInput>
}

export type video_contentsUpdateManyWithWhereWithoutLessonsInput = {
  where: Prisma.video_contentsScalarWhereInput
  data: Prisma.XOR<Prisma.video_contentsUpdateManyMutationInput, Prisma.video_contentsUncheckedUpdateManyWithoutLessonsInput>
}

export type video_contentsScalarWhereInput = {
  AND?: Prisma.video_contentsScalarWhereInput | Prisma.video_contentsScalarWhereInput[]
  OR?: Prisma.video_contentsScalarWhereInput[]
  NOT?: Prisma.video_contentsScalarWhereInput | Prisma.video_contentsScalarWhereInput[]
  id?: Prisma.IntFilter<"video_contents"> | number
  lesson_id?: Prisma.IntFilter<"video_contents"> | number
  url?: Prisma.StringFilter<"video_contents"> | string
  description?: Prisma.StringNullableFilter<"video_contents"> | string | null
  duration?: Prisma.IntNullableFilter<"video_contents"> | number | null
}

export type video_contentsCreateManyLessonsInput = {
  id?: number
  url: string
  description?: string | null
  duration?: number | null
}

export type video_contentsUpdateWithoutLessonsInput = {
  url?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  duration?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type video_contentsUncheckedUpdateWithoutLessonsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  url?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  duration?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type video_contentsUncheckedUpdateManyWithoutLessonsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  url?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  duration?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}



export type video_contentsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  lesson_id?: boolean
  url?: boolean
  description?: boolean
  duration?: boolean
  lessons?: boolean | Prisma.lessonsDefaultArgs<ExtArgs>
}, ExtArgs["result"]["video_contents"]>

export type video_contentsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  lesson_id?: boolean
  url?: boolean
  description?: boolean
  duration?: boolean
  lessons?: boolean | Prisma.lessonsDefaultArgs<ExtArgs>
}, ExtArgs["result"]["video_contents"]>

export type video_contentsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  lesson_id?: boolean
  url?: boolean
  description?: boolean
  duration?: boolean
  lessons?: boolean | Prisma.lessonsDefaultArgs<ExtArgs>
}, ExtArgs["result"]["video_contents"]>

export type video_contentsSelectScalar = {
  id?: boolean
  lesson_id?: boolean
  url?: boolean
  description?: boolean
  duration?: boolean
}

export type video_contentsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "lesson_id" | "url" | "description" | "duration", ExtArgs["result"]["video_contents"]>
export type video_contentsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  lessons?: boolean | Prisma.lessonsDefaultArgs<ExtArgs>
}
export type video_contentsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  lessons?: boolean | Prisma.lessonsDefaultArgs<ExtArgs>
}
export type video_contentsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  lessons?: boolean | Prisma.lessonsDefaultArgs<ExtArgs>
}

export type $video_contentsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "video_contents"
  objects: {
    lessons: Prisma.$lessonsPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    lesson_id: number
    url: string
    description: string | null
    duration: number | null
  }, ExtArgs["result"]["video_contents"]>
  composites: {}
}

export type video_contentsGetPayload<S extends boolean | null | undefined | video_contentsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$video_contentsPayload, S>

export type video_contentsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<video_contentsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Video_contentsCountAggregateInputType | true
  }

export interface video_contentsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['video_contents'], meta: { name: 'video_contents' } }
  /**
   * Find zero or one Video_contents that matches the filter.
   * @param {video_contentsFindUniqueArgs} args - Arguments to find a Video_contents
   * @example
   * // Get one Video_contents
   * const video_contents = await prisma.video_contents.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends video_contentsFindUniqueArgs>(args: Prisma.SelectSubset<T, video_contentsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__video_contentsClient<runtime.Types.Result.GetResult<Prisma.$video_contentsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Video_contents that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {video_contentsFindUniqueOrThrowArgs} args - Arguments to find a Video_contents
   * @example
   * // Get one Video_contents
   * const video_contents = await prisma.video_contents.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends video_contentsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, video_contentsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__video_contentsClient<runtime.Types.Result.GetResult<Prisma.$video_contentsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Video_contents that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {video_contentsFindFirstArgs} args - Arguments to find a Video_contents
   * @example
   * // Get one Video_contents
   * const video_contents = await prisma.video_contents.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends video_contentsFindFirstArgs>(args?: Prisma.SelectSubset<T, video_contentsFindFirstArgs<ExtArgs>>): Prisma.Prisma__video_contentsClient<runtime.Types.Result.GetResult<Prisma.$video_contentsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Video_contents that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {video_contentsFindFirstOrThrowArgs} args - Arguments to find a Video_contents
   * @example
   * // Get one Video_contents
   * const video_contents = await prisma.video_contents.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends video_contentsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, video_contentsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__video_contentsClient<runtime.Types.Result.GetResult<Prisma.$video_contentsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Video_contents that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {video_contentsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Video_contents
   * const video_contents = await prisma.video_contents.findMany()
   * 
   * // Get first 10 Video_contents
   * const video_contents = await prisma.video_contents.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const video_contentsWithIdOnly = await prisma.video_contents.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends video_contentsFindManyArgs>(args?: Prisma.SelectSubset<T, video_contentsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$video_contentsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Video_contents.
   * @param {video_contentsCreateArgs} args - Arguments to create a Video_contents.
   * @example
   * // Create one Video_contents
   * const Video_contents = await prisma.video_contents.create({
   *   data: {
   *     // ... data to create a Video_contents
   *   }
   * })
   * 
   */
  create<T extends video_contentsCreateArgs>(args: Prisma.SelectSubset<T, video_contentsCreateArgs<ExtArgs>>): Prisma.Prisma__video_contentsClient<runtime.Types.Result.GetResult<Prisma.$video_contentsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Video_contents.
   * @param {video_contentsCreateManyArgs} args - Arguments to create many Video_contents.
   * @example
   * // Create many Video_contents
   * const video_contents = await prisma.video_contents.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends video_contentsCreateManyArgs>(args?: Prisma.SelectSubset<T, video_contentsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Video_contents and returns the data saved in the database.
   * @param {video_contentsCreateManyAndReturnArgs} args - Arguments to create many Video_contents.
   * @example
   * // Create many Video_contents
   * const video_contents = await prisma.video_contents.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Video_contents and only return the `id`
   * const video_contentsWithIdOnly = await prisma.video_contents.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends video_contentsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, video_contentsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$video_contentsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Video_contents.
   * @param {video_contentsDeleteArgs} args - Arguments to delete one Video_contents.
   * @example
   * // Delete one Video_contents
   * const Video_contents = await prisma.video_contents.delete({
   *   where: {
   *     // ... filter to delete one Video_contents
   *   }
   * })
   * 
   */
  delete<T extends video_contentsDeleteArgs>(args: Prisma.SelectSubset<T, video_contentsDeleteArgs<ExtArgs>>): Prisma.Prisma__video_contentsClient<runtime.Types.Result.GetResult<Prisma.$video_contentsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Video_contents.
   * @param {video_contentsUpdateArgs} args - Arguments to update one Video_contents.
   * @example
   * // Update one Video_contents
   * const video_contents = await prisma.video_contents.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends video_contentsUpdateArgs>(args: Prisma.SelectSubset<T, video_contentsUpdateArgs<ExtArgs>>): Prisma.Prisma__video_contentsClient<runtime.Types.Result.GetResult<Prisma.$video_contentsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Video_contents.
   * @param {video_contentsDeleteManyArgs} args - Arguments to filter Video_contents to delete.
   * @example
   * // Delete a few Video_contents
   * const { count } = await prisma.video_contents.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends video_contentsDeleteManyArgs>(args?: Prisma.SelectSubset<T, video_contentsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Video_contents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {video_contentsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Video_contents
   * const video_contents = await prisma.video_contents.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends video_contentsUpdateManyArgs>(args: Prisma.SelectSubset<T, video_contentsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Video_contents and returns the data updated in the database.
   * @param {video_contentsUpdateManyAndReturnArgs} args - Arguments to update many Video_contents.
   * @example
   * // Update many Video_contents
   * const video_contents = await prisma.video_contents.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Video_contents and only return the `id`
   * const video_contentsWithIdOnly = await prisma.video_contents.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends video_contentsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, video_contentsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$video_contentsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Video_contents.
   * @param {video_contentsUpsertArgs} args - Arguments to update or create a Video_contents.
   * @example
   * // Update or create a Video_contents
   * const video_contents = await prisma.video_contents.upsert({
   *   create: {
   *     // ... data to create a Video_contents
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Video_contents we want to update
   *   }
   * })
   */
  upsert<T extends video_contentsUpsertArgs>(args: Prisma.SelectSubset<T, video_contentsUpsertArgs<ExtArgs>>): Prisma.Prisma__video_contentsClient<runtime.Types.Result.GetResult<Prisma.$video_contentsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Video_contents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {video_contentsCountArgs} args - Arguments to filter Video_contents to count.
   * @example
   * // Count the number of Video_contents
   * const count = await prisma.video_contents.count({
   *   where: {
   *     // ... the filter for the Video_contents we want to count
   *   }
   * })
  **/
  count<T extends video_contentsCountArgs>(
    args?: Prisma.Subset<T, video_contentsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Video_contentsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Video_contents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Video_contentsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Video_contentsAggregateArgs>(args: Prisma.Subset<T, Video_contentsAggregateArgs>): Prisma.PrismaPromise<GetVideo_contentsAggregateType<T>>

  /**
   * Group by Video_contents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {video_contentsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends video_contentsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: video_contentsGroupByArgs['orderBy'] }
      : { orderBy?: video_contentsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, video_contentsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetVideo_contentsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the video_contents model
 */
readonly fields: video_contentsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for video_contents.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__video_contentsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  lessons<T extends Prisma.lessonsDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.lessonsDefaultArgs<ExtArgs>>): Prisma.Prisma__lessonsClient<runtime.Types.Result.GetResult<Prisma.$lessonsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the video_contents model
 */
export interface video_contentsFieldRefs {
  readonly id: Prisma.FieldRef<"video_contents", 'Int'>
  readonly lesson_id: Prisma.FieldRef<"video_contents", 'Int'>
  readonly url: Prisma.FieldRef<"video_contents", 'String'>
  readonly description: Prisma.FieldRef<"video_contents", 'String'>
  readonly duration: Prisma.FieldRef<"video_contents", 'Int'>
}
    

// Custom InputTypes
/**
 * video_contents findUnique
 */
export type video_contentsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the video_contents
   */
  select?: Prisma.video_contentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the video_contents
   */
  omit?: Prisma.video_contentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.video_contentsInclude<ExtArgs> | null
  /**
   * Filter, which video_contents to fetch.
   */
  where: Prisma.video_contentsWhereUniqueInput
}

/**
 * video_contents findUniqueOrThrow
 */
export type video_contentsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the video_contents
   */
  select?: Prisma.video_contentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the video_contents
   */
  omit?: Prisma.video_contentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.video_contentsInclude<ExtArgs> | null
  /**
   * Filter, which video_contents to fetch.
   */
  where: Prisma.video_contentsWhereUniqueInput
}

/**
 * video_contents findFirst
 */
export type video_contentsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the video_contents
   */
  select?: Prisma.video_contentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the video_contents
   */
  omit?: Prisma.video_contentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.video_contentsInclude<ExtArgs> | null
  /**
   * Filter, which video_contents to fetch.
   */
  where?: Prisma.video_contentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of video_contents to fetch.
   */
  orderBy?: Prisma.video_contentsOrderByWithRelationInput | Prisma.video_contentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for video_contents.
   */
  cursor?: Prisma.video_contentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` video_contents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` video_contents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of video_contents.
   */
  distinct?: Prisma.Video_contentsScalarFieldEnum | Prisma.Video_contentsScalarFieldEnum[]
}

/**
 * video_contents findFirstOrThrow
 */
export type video_contentsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the video_contents
   */
  select?: Prisma.video_contentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the video_contents
   */
  omit?: Prisma.video_contentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.video_contentsInclude<ExtArgs> | null
  /**
   * Filter, which video_contents to fetch.
   */
  where?: Prisma.video_contentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of video_contents to fetch.
   */
  orderBy?: Prisma.video_contentsOrderByWithRelationInput | Prisma.video_contentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for video_contents.
   */
  cursor?: Prisma.video_contentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` video_contents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` video_contents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of video_contents.
   */
  distinct?: Prisma.Video_contentsScalarFieldEnum | Prisma.Video_contentsScalarFieldEnum[]
}

/**
 * video_contents findMany
 */
export type video_contentsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the video_contents
   */
  select?: Prisma.video_contentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the video_contents
   */
  omit?: Prisma.video_contentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.video_contentsInclude<ExtArgs> | null
  /**
   * Filter, which video_contents to fetch.
   */
  where?: Prisma.video_contentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of video_contents to fetch.
   */
  orderBy?: Prisma.video_contentsOrderByWithRelationInput | Prisma.video_contentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing video_contents.
   */
  cursor?: Prisma.video_contentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` video_contents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` video_contents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of video_contents.
   */
  distinct?: Prisma.Video_contentsScalarFieldEnum | Prisma.Video_contentsScalarFieldEnum[]
}

/**
 * video_contents create
 */
export type video_contentsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the video_contents
   */
  select?: Prisma.video_contentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the video_contents
   */
  omit?: Prisma.video_contentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.video_contentsInclude<ExtArgs> | null
  /**
   * The data needed to create a video_contents.
   */
  data: Prisma.XOR<Prisma.video_contentsCreateInput, Prisma.video_contentsUncheckedCreateInput>
}

/**
 * video_contents createMany
 */
export type video_contentsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many video_contents.
   */
  data: Prisma.video_contentsCreateManyInput | Prisma.video_contentsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * video_contents createManyAndReturn
 */
export type video_contentsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the video_contents
   */
  select?: Prisma.video_contentsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the video_contents
   */
  omit?: Prisma.video_contentsOmit<ExtArgs> | null
  /**
   * The data used to create many video_contents.
   */
  data: Prisma.video_contentsCreateManyInput | Prisma.video_contentsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.video_contentsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * video_contents update
 */
export type video_contentsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the video_contents
   */
  select?: Prisma.video_contentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the video_contents
   */
  omit?: Prisma.video_contentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.video_contentsInclude<ExtArgs> | null
  /**
   * The data needed to update a video_contents.
   */
  data: Prisma.XOR<Prisma.video_contentsUpdateInput, Prisma.video_contentsUncheckedUpdateInput>
  /**
   * Choose, which video_contents to update.
   */
  where: Prisma.video_contentsWhereUniqueInput
}

/**
 * video_contents updateMany
 */
export type video_contentsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update video_contents.
   */
  data: Prisma.XOR<Prisma.video_contentsUpdateManyMutationInput, Prisma.video_contentsUncheckedUpdateManyInput>
  /**
   * Filter which video_contents to update
   */
  where?: Prisma.video_contentsWhereInput
  /**
   * Limit how many video_contents to update.
   */
  limit?: number
}

/**
 * video_contents updateManyAndReturn
 */
export type video_contentsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the video_contents
   */
  select?: Prisma.video_contentsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the video_contents
   */
  omit?: Prisma.video_contentsOmit<ExtArgs> | null
  /**
   * The data used to update video_contents.
   */
  data: Prisma.XOR<Prisma.video_contentsUpdateManyMutationInput, Prisma.video_contentsUncheckedUpdateManyInput>
  /**
   * Filter which video_contents to update
   */
  where?: Prisma.video_contentsWhereInput
  /**
   * Limit how many video_contents to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.video_contentsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * video_contents upsert
 */
export type video_contentsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the video_contents
   */
  select?: Prisma.video_contentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the video_contents
   */
  omit?: Prisma.video_contentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.video_contentsInclude<ExtArgs> | null
  /**
   * The filter to search for the video_contents to update in case it exists.
   */
  where: Prisma.video_contentsWhereUniqueInput
  /**
   * In case the video_contents found by the `where` argument doesn't exist, create a new video_contents with this data.
   */
  create: Prisma.XOR<Prisma.video_contentsCreateInput, Prisma.video_contentsUncheckedCreateInput>
  /**
   * In case the video_contents was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.video_contentsUpdateInput, Prisma.video_contentsUncheckedUpdateInput>
}

/**
 * video_contents delete
 */
export type video_contentsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the video_contents
   */
  select?: Prisma.video_contentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the video_contents
   */
  omit?: Prisma.video_contentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.video_contentsInclude<ExtArgs> | null
  /**
   * Filter which video_contents to delete.
   */
  where: Prisma.video_contentsWhereUniqueInput
}

/**
 * video_contents deleteMany
 */
export type video_contentsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which video_contents to delete
   */
  where?: Prisma.video_contentsWhereInput
  /**
   * Limit how many video_contents to delete.
   */
  limit?: number
}

/**
 * video_contents without action
 */
export type video_contentsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the video_contents
   */
  select?: Prisma.video_contentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the video_contents
   */
  omit?: Prisma.video_contentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.video_contentsInclude<ExtArgs> | null
}
