
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `visio_acoustic_contents` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model visio_acoustic_contents
 * Implements visio-acoustic diagnostic quiz system for associating sounds
 * with visual elements (gestures, images). Questions test comprehension by
 * matching audio cues with visual representations.
 */
export type visio_acoustic_contentsModel = runtime.Types.Result.DefaultSelection<Prisma.$visio_acoustic_contentsPayload>

export type AggregateVisio_acoustic_contents = {
  _count: Visio_acoustic_contentsCountAggregateOutputType | null
  _avg: Visio_acoustic_contentsAvgAggregateOutputType | null
  _sum: Visio_acoustic_contentsSumAggregateOutputType | null
  _min: Visio_acoustic_contentsMinAggregateOutputType | null
  _max: Visio_acoustic_contentsMaxAggregateOutputType | null
}

export type Visio_acoustic_contentsAvgAggregateOutputType = {
  id: number | null
  lesson_id: number | null
  question_order: number | null
}

export type Visio_acoustic_contentsSumAggregateOutputType = {
  id: number | null
  lesson_id: number | null
  question_order: number | null
}

export type Visio_acoustic_contentsMinAggregateOutputType = {
  id: number | null
  lesson_id: number | null
  question_text: string | null
  sound_url: string | null
  image_url: string | null
  correct_answer: string | null
  option_b: string | null
  option_c: string | null
  option_d: string | null
  feedback_correct: string | null
  feedback_incorrect: string | null
  question_order: number | null
  difficulty_level: string | null
}

export type Visio_acoustic_contentsMaxAggregateOutputType = {
  id: number | null
  lesson_id: number | null
  question_text: string | null
  sound_url: string | null
  image_url: string | null
  correct_answer: string | null
  option_b: string | null
  option_c: string | null
  option_d: string | null
  feedback_correct: string | null
  feedback_incorrect: string | null
  question_order: number | null
  difficulty_level: string | null
}

export type Visio_acoustic_contentsCountAggregateOutputType = {
  id: number
  lesson_id: number
  question_text: number
  sound_url: number
  image_url: number
  correct_answer: number
  option_b: number
  option_c: number
  option_d: number
  feedback_correct: number
  feedback_incorrect: number
  question_order: number
  difficulty_level: number
  _all: number
}


export type Visio_acoustic_contentsAvgAggregateInputType = {
  id?: true
  lesson_id?: true
  question_order?: true
}

export type Visio_acoustic_contentsSumAggregateInputType = {
  id?: true
  lesson_id?: true
  question_order?: true
}

export type Visio_acoustic_contentsMinAggregateInputType = {
  id?: true
  lesson_id?: true
  question_text?: true
  sound_url?: true
  image_url?: true
  correct_answer?: true
  option_b?: true
  option_c?: true
  option_d?: true
  feedback_correct?: true
  feedback_incorrect?: true
  question_order?: true
  difficulty_level?: true
}

export type Visio_acoustic_contentsMaxAggregateInputType = {
  id?: true
  lesson_id?: true
  question_text?: true
  sound_url?: true
  image_url?: true
  correct_answer?: true
  option_b?: true
  option_c?: true
  option_d?: true
  feedback_correct?: true
  feedback_incorrect?: true
  question_order?: true
  difficulty_level?: true
}

export type Visio_acoustic_contentsCountAggregateInputType = {
  id?: true
  lesson_id?: true
  question_text?: true
  sound_url?: true
  image_url?: true
  correct_answer?: true
  option_b?: true
  option_c?: true
  option_d?: true
  feedback_correct?: true
  feedback_incorrect?: true
  question_order?: true
  difficulty_level?: true
  _all?: true
}

export type Visio_acoustic_contentsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which visio_acoustic_contents to aggregate.
   */
  where?: Prisma.visio_acoustic_contentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of visio_acoustic_contents to fetch.
   */
  orderBy?: Prisma.visio_acoustic_contentsOrderByWithRelationInput | Prisma.visio_acoustic_contentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.visio_acoustic_contentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` visio_acoustic_contents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` visio_acoustic_contents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned visio_acoustic_contents
  **/
  _count?: true | Visio_acoustic_contentsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: Visio_acoustic_contentsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: Visio_acoustic_contentsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: Visio_acoustic_contentsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: Visio_acoustic_contentsMaxAggregateInputType
}

export type GetVisio_acoustic_contentsAggregateType<T extends Visio_acoustic_contentsAggregateArgs> = {
      [P in keyof T & keyof AggregateVisio_acoustic_contents]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateVisio_acoustic_contents[P]>
    : Prisma.GetScalarType<T[P], AggregateVisio_acoustic_contents[P]>
}




export type visio_acoustic_contentsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.visio_acoustic_contentsWhereInput
  orderBy?: Prisma.visio_acoustic_contentsOrderByWithAggregationInput | Prisma.visio_acoustic_contentsOrderByWithAggregationInput[]
  by: Prisma.Visio_acoustic_contentsScalarFieldEnum[] | Prisma.Visio_acoustic_contentsScalarFieldEnum
  having?: Prisma.visio_acoustic_contentsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: Visio_acoustic_contentsCountAggregateInputType | true
  _avg?: Visio_acoustic_contentsAvgAggregateInputType
  _sum?: Visio_acoustic_contentsSumAggregateInputType
  _min?: Visio_acoustic_contentsMinAggregateInputType
  _max?: Visio_acoustic_contentsMaxAggregateInputType
}

export type Visio_acoustic_contentsGroupByOutputType = {
  id: number
  lesson_id: number
  question_text: string
  sound_url: string
  image_url: string
  correct_answer: string
  option_b: string
  option_c: string
  option_d: string | null
  feedback_correct: string | null
  feedback_incorrect: string | null
  question_order: number
  difficulty_level: string
  _count: Visio_acoustic_contentsCountAggregateOutputType | null
  _avg: Visio_acoustic_contentsAvgAggregateOutputType | null
  _sum: Visio_acoustic_contentsSumAggregateOutputType | null
  _min: Visio_acoustic_contentsMinAggregateOutputType | null
  _max: Visio_acoustic_contentsMaxAggregateOutputType | null
}

export type GetVisio_acoustic_contentsGroupByPayload<T extends visio_acoustic_contentsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<Visio_acoustic_contentsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof Visio_acoustic_contentsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], Visio_acoustic_contentsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], Visio_acoustic_contentsGroupByOutputType[P]>
      }
    >
  >



export type visio_acoustic_contentsWhereInput = {
  AND?: Prisma.visio_acoustic_contentsWhereInput | Prisma.visio_acoustic_contentsWhereInput[]
  OR?: Prisma.visio_acoustic_contentsWhereInput[]
  NOT?: Prisma.visio_acoustic_contentsWhereInput | Prisma.visio_acoustic_contentsWhereInput[]
  id?: Prisma.IntFilter<"visio_acoustic_contents"> | number
  lesson_id?: Prisma.IntFilter<"visio_acoustic_contents"> | number
  question_text?: Prisma.StringFilter<"visio_acoustic_contents"> | string
  sound_url?: Prisma.StringFilter<"visio_acoustic_contents"> | string
  image_url?: Prisma.StringFilter<"visio_acoustic_contents"> | string
  correct_answer?: Prisma.StringFilter<"visio_acoustic_contents"> | string
  option_b?: Prisma.StringFilter<"visio_acoustic_contents"> | string
  option_c?: Prisma.StringFilter<"visio_acoustic_contents"> | string
  option_d?: Prisma.StringNullableFilter<"visio_acoustic_contents"> | string | null
  feedback_correct?: Prisma.StringNullableFilter<"visio_acoustic_contents"> | string | null
  feedback_incorrect?: Prisma.StringNullableFilter<"visio_acoustic_contents"> | string | null
  question_order?: Prisma.IntFilter<"visio_acoustic_contents"> | number
  difficulty_level?: Prisma.StringFilter<"visio_acoustic_contents"> | string
  lessons?: Prisma.XOR<Prisma.LessonsScalarRelationFilter, Prisma.lessonsWhereInput>
}

export type visio_acoustic_contentsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  lesson_id?: Prisma.SortOrder
  question_text?: Prisma.SortOrder
  sound_url?: Prisma.SortOrder
  image_url?: Prisma.SortOrder
  correct_answer?: Prisma.SortOrder
  option_b?: Prisma.SortOrder
  option_c?: Prisma.SortOrder
  option_d?: Prisma.SortOrderInput | Prisma.SortOrder
  feedback_correct?: Prisma.SortOrderInput | Prisma.SortOrder
  feedback_incorrect?: Prisma.SortOrderInput | Prisma.SortOrder
  question_order?: Prisma.SortOrder
  difficulty_level?: Prisma.SortOrder
  lessons?: Prisma.lessonsOrderByWithRelationInput
}

export type visio_acoustic_contentsWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.visio_acoustic_contentsWhereInput | Prisma.visio_acoustic_contentsWhereInput[]
  OR?: Prisma.visio_acoustic_contentsWhereInput[]
  NOT?: Prisma.visio_acoustic_contentsWhereInput | Prisma.visio_acoustic_contentsWhereInput[]
  lesson_id?: Prisma.IntFilter<"visio_acoustic_contents"> | number
  question_text?: Prisma.StringFilter<"visio_acoustic_contents"> | string
  sound_url?: Prisma.StringFilter<"visio_acoustic_contents"> | string
  image_url?: Prisma.StringFilter<"visio_acoustic_contents"> | string
  correct_answer?: Prisma.StringFilter<"visio_acoustic_contents"> | string
  option_b?: Prisma.StringFilter<"visio_acoustic_contents"> | string
  option_c?: Prisma.StringFilter<"visio_acoustic_contents"> | string
  option_d?: Prisma.StringNullableFilter<"visio_acoustic_contents"> | string | null
  feedback_correct?: Prisma.StringNullableFilter<"visio_acoustic_contents"> | string | null
  feedback_incorrect?: Prisma.StringNullableFilter<"visio_acoustic_contents"> | string | null
  question_order?: Prisma.IntFilter<"visio_acoustic_contents"> | number
  difficulty_level?: Prisma.StringFilter<"visio_acoustic_contents"> | string
  lessons?: Prisma.XOR<Prisma.LessonsScalarRelationFilter, Prisma.lessonsWhereInput>
}, "id">

export type visio_acoustic_contentsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  lesson_id?: Prisma.SortOrder
  question_text?: Prisma.SortOrder
  sound_url?: Prisma.SortOrder
  image_url?: Prisma.SortOrder
  correct_answer?: Prisma.SortOrder
  option_b?: Prisma.SortOrder
  option_c?: Prisma.SortOrder
  option_d?: Prisma.SortOrderInput | Prisma.SortOrder
  feedback_correct?: Prisma.SortOrderInput | Prisma.SortOrder
  feedback_incorrect?: Prisma.SortOrderInput | Prisma.SortOrder
  question_order?: Prisma.SortOrder
  difficulty_level?: Prisma.SortOrder
  _count?: Prisma.visio_acoustic_contentsCountOrderByAggregateInput
  _avg?: Prisma.visio_acoustic_contentsAvgOrderByAggregateInput
  _max?: Prisma.visio_acoustic_contentsMaxOrderByAggregateInput
  _min?: Prisma.visio_acoustic_contentsMinOrderByAggregateInput
  _sum?: Prisma.visio_acoustic_contentsSumOrderByAggregateInput
}

export type visio_acoustic_contentsScalarWhereWithAggregatesInput = {
  AND?: Prisma.visio_acoustic_contentsScalarWhereWithAggregatesInput | Prisma.visio_acoustic_contentsScalarWhereWithAggregatesInput[]
  OR?: Prisma.visio_acoustic_contentsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.visio_acoustic_contentsScalarWhereWithAggregatesInput | Prisma.visio_acoustic_contentsScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"visio_acoustic_contents"> | number
  lesson_id?: Prisma.IntWithAggregatesFilter<"visio_acoustic_contents"> | number
  question_text?: Prisma.StringWithAggregatesFilter<"visio_acoustic_contents"> | string
  sound_url?: Prisma.StringWithAggregatesFilter<"visio_acoustic_contents"> | string
  image_url?: Prisma.StringWithAggregatesFilter<"visio_acoustic_contents"> | string
  correct_answer?: Prisma.StringWithAggregatesFilter<"visio_acoustic_contents"> | string
  option_b?: Prisma.StringWithAggregatesFilter<"visio_acoustic_contents"> | string
  option_c?: Prisma.StringWithAggregatesFilter<"visio_acoustic_contents"> | string
  option_d?: Prisma.StringNullableWithAggregatesFilter<"visio_acoustic_contents"> | string | null
  feedback_correct?: Prisma.StringNullableWithAggregatesFilter<"visio_acoustic_contents"> | string | null
  feedback_incorrect?: Prisma.StringNullableWithAggregatesFilter<"visio_acoustic_contents"> | string | null
  question_order?: Prisma.IntWithAggregatesFilter<"visio_acoustic_contents"> | number
  difficulty_level?: Prisma.StringWithAggregatesFilter<"visio_acoustic_contents"> | string
}

export type visio_acoustic_contentsCreateInput = {
  question_text: string
  sound_url: string
  image_url: string
  correct_answer: string
  option_b: string
  option_c: string
  option_d?: string | null
  feedback_correct?: string | null
  feedback_incorrect?: string | null
  question_order?: number
  difficulty_level?: string
  lessons: Prisma.lessonsCreateNestedOneWithoutVisio_acoustic_contentsInput
}

export type visio_acoustic_contentsUncheckedCreateInput = {
  id?: number
  lesson_id: number
  question_text: string
  sound_url: string
  image_url: string
  correct_answer: string
  option_b: string
  option_c: string
  option_d?: string | null
  feedback_correct?: string | null
  feedback_incorrect?: string | null
  question_order?: number
  difficulty_level?: string
}

export type visio_acoustic_contentsUpdateInput = {
  question_text?: Prisma.StringFieldUpdateOperationsInput | string
  sound_url?: Prisma.StringFieldUpdateOperationsInput | string
  image_url?: Prisma.StringFieldUpdateOperationsInput | string
  correct_answer?: Prisma.StringFieldUpdateOperationsInput | string
  option_b?: Prisma.StringFieldUpdateOperationsInput | string
  option_c?: Prisma.StringFieldUpdateOperationsInput | string
  option_d?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  feedback_correct?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  feedback_incorrect?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  question_order?: Prisma.IntFieldUpdateOperationsInput | number
  difficulty_level?: Prisma.StringFieldUpdateOperationsInput | string
  lessons?: Prisma.lessonsUpdateOneRequiredWithoutVisio_acoustic_contentsNestedInput
}

export type visio_acoustic_contentsUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  lesson_id?: Prisma.IntFieldUpdateOperationsInput | number
  question_text?: Prisma.StringFieldUpdateOperationsInput | string
  sound_url?: Prisma.StringFieldUpdateOperationsInput | string
  image_url?: Prisma.StringFieldUpdateOperationsInput | string
  correct_answer?: Prisma.StringFieldUpdateOperationsInput | string
  option_b?: Prisma.StringFieldUpdateOperationsInput | string
  option_c?: Prisma.StringFieldUpdateOperationsInput | string
  option_d?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  feedback_correct?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  feedback_incorrect?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  question_order?: Prisma.IntFieldUpdateOperationsInput | number
  difficulty_level?: Prisma.StringFieldUpdateOperationsInput | string
}

export type visio_acoustic_contentsCreateManyInput = {
  id?: number
  lesson_id: number
  question_text: string
  sound_url: string
  image_url: string
  correct_answer: string
  option_b: string
  option_c: string
  option_d?: string | null
  feedback_correct?: string | null
  feedback_incorrect?: string | null
  question_order?: number
  difficulty_level?: string
}

export type visio_acoustic_contentsUpdateManyMutationInput = {
  question_text?: Prisma.StringFieldUpdateOperationsInput | string
  sound_url?: Prisma.StringFieldUpdateOperationsInput | string
  image_url?: Prisma.StringFieldUpdateOperationsInput | string
  correct_answer?: Prisma.StringFieldUpdateOperationsInput | string
  option_b?: Prisma.StringFieldUpdateOperationsInput | string
  option_c?: Prisma.StringFieldUpdateOperationsInput | string
  option_d?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  feedback_correct?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  feedback_incorrect?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  question_order?: Prisma.IntFieldUpdateOperationsInput | number
  difficulty_level?: Prisma.StringFieldUpdateOperationsInput | string
}

export type visio_acoustic_contentsUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  lesson_id?: Prisma.IntFieldUpdateOperationsInput | number
  question_text?: Prisma.StringFieldUpdateOperationsInput | string
  sound_url?: Prisma.StringFieldUpdateOperationsInput | string
  image_url?: Prisma.StringFieldUpdateOperationsInput | string
  correct_answer?: Prisma.StringFieldUpdateOperationsInput | string
  option_b?: Prisma.StringFieldUpdateOperationsInput | string
  option_c?: Prisma.StringFieldUpdateOperationsInput | string
  option_d?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  feedback_correct?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  feedback_incorrect?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  question_order?: Prisma.IntFieldUpdateOperationsInput | number
  difficulty_level?: Prisma.StringFieldUpdateOperationsInput | string
}

export type Visio_acoustic_contentsListRelationFilter = {
  every?: Prisma.visio_acoustic_contentsWhereInput
  some?: Prisma.visio_acoustic_contentsWhereInput
  none?: Prisma.visio_acoustic_contentsWhereInput
}

export type visio_acoustic_contentsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type visio_acoustic_contentsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  lesson_id?: Prisma.SortOrder
  question_text?: Prisma.SortOrder
  sound_url?: Prisma.SortOrder
  image_url?: Prisma.SortOrder
  correct_answer?: Prisma.SortOrder
  option_b?: Prisma.SortOrder
  option_c?: Prisma.SortOrder
  option_d?: Prisma.SortOrder
  feedback_correct?: Prisma.SortOrder
  feedback_incorrect?: Prisma.SortOrder
  question_order?: Prisma.SortOrder
  difficulty_level?: Prisma.SortOrder
}

export type visio_acoustic_contentsAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  lesson_id?: Prisma.SortOrder
  question_order?: Prisma.SortOrder
}

export type visio_acoustic_contentsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  lesson_id?: Prisma.SortOrder
  question_text?: Prisma.SortOrder
  sound_url?: Prisma.SortOrder
  image_url?: Prisma.SortOrder
  correct_answer?: Prisma.SortOrder
  option_b?: Prisma.SortOrder
  option_c?: Prisma.SortOrder
  option_d?: Prisma.SortOrder
  feedback_correct?: Prisma.SortOrder
  feedback_incorrect?: Prisma.SortOrder
  question_order?: Prisma.SortOrder
  difficulty_level?: Prisma.SortOrder
}

export type visio_acoustic_contentsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  lesson_id?: Prisma.SortOrder
  question_text?: Prisma.SortOrder
  sound_url?: Prisma.SortOrder
  image_url?: Prisma.SortOrder
  correct_answer?: Prisma.SortOrder
  option_b?: Prisma.SortOrder
  option_c?: Prisma.SortOrder
  option_d?: Prisma.SortOrder
  feedback_correct?: Prisma.SortOrder
  feedback_incorrect?: Prisma.SortOrder
  question_order?: Prisma.SortOrder
  difficulty_level?: Prisma.SortOrder
}

export type visio_acoustic_contentsSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  lesson_id?: Prisma.SortOrder
  question_order?: Prisma.SortOrder
}

export type visio_acoustic_contentsCreateNestedManyWithoutLessonsInput = {
  create?: Prisma.XOR<Prisma.visio_acoustic_contentsCreateWithoutLessonsInput, Prisma.visio_acoustic_contentsUncheckedCreateWithoutLessonsInput> | Prisma.visio_acoustic_contentsCreateWithoutLessonsInput[] | Prisma.visio_acoustic_contentsUncheckedCreateWithoutLessonsInput[]
  connectOrCreate?: Prisma.visio_acoustic_contentsCreateOrConnectWithoutLessonsInput | Prisma.visio_acoustic_contentsCreateOrConnectWithoutLessonsInput[]
  createMany?: Prisma.visio_acoustic_contentsCreateManyLessonsInputEnvelope
  connect?: Prisma.visio_acoustic_contentsWhereUniqueInput | Prisma.visio_acoustic_contentsWhereUniqueInput[]
}

export type visio_acoustic_contentsUncheckedCreateNestedManyWithoutLessonsInput = {
  create?: Prisma.XOR<Prisma.visio_acoustic_contentsCreateWithoutLessonsInput, Prisma.visio_acoustic_contentsUncheckedCreateWithoutLessonsInput> | Prisma.visio_acoustic_contentsCreateWithoutLessonsInput[] | Prisma.visio_acoustic_contentsUncheckedCreateWithoutLessonsInput[]
  connectOrCreate?: Prisma.visio_acoustic_contentsCreateOrConnectWithoutLessonsInput | Prisma.visio_acoustic_contentsCreateOrConnectWithoutLessonsInput[]
  createMany?: Prisma.visio_acoustic_contentsCreateManyLessonsInputEnvelope
  connect?: Prisma.visio_acoustic_contentsWhereUniqueInput | Prisma.visio_acoustic_contentsWhereUniqueInput[]
}

export type visio_acoustic_contentsUpdateManyWithoutLessonsNestedInput = {
  create?: Prisma.XOR<Prisma.visio_acoustic_contentsCreateWithoutLessonsInput, Prisma.visio_acoustic_contentsUncheckedCreateWithoutLessonsInput> | Prisma.visio_acoustic_contentsCreateWithoutLessonsInput[] | Prisma.visio_acoustic_contentsUncheckedCreateWithoutLessonsInput[]
  connectOrCreate?: Prisma.visio_acoustic_contentsCreateOrConnectWithoutLessonsInput | Prisma.visio_acoustic_contentsCreateOrConnectWithoutLessonsInput[]
  upsert?: Prisma.visio_acoustic_contentsUpsertWithWhereUniqueWithoutLessonsInput | Prisma.visio_acoustic_contentsUpsertWithWhereUniqueWithoutLessonsInput[]
  createMany?: Prisma.visio_acoustic_contentsCreateManyLessonsInputEnvelope
  set?: Prisma.visio_acoustic_contentsWhereUniqueInput | Prisma.visio_acoustic_contentsWhereUniqueInput[]
  disconnect?: Prisma.visio_acoustic_contentsWhereUniqueInput | Prisma.visio_acoustic_contentsWhereUniqueInput[]
  delete?: Prisma.visio_acoustic_contentsWhereUniqueInput | Prisma.visio_acoustic_contentsWhereUniqueInput[]
  connect?: Prisma.visio_acoustic_contentsWhereUniqueInput | Prisma.visio_acoustic_contentsWhereUniqueInput[]
  update?: Prisma.visio_acoustic_contentsUpdateWithWhereUniqueWithoutLessonsInput | Prisma.visio_acoustic_contentsUpdateWithWhereUniqueWithoutLessonsInput[]
  updateMany?: Prisma.visio_acoustic_contentsUpdateManyWithWhereWithoutLessonsInput | Prisma.visio_acoustic_contentsUpdateManyWithWhereWithoutLessonsInput[]
  deleteMany?: Prisma.visio_acoustic_contentsScalarWhereInput | Prisma.visio_acoustic_contentsScalarWhereInput[]
}

export type visio_acoustic_contentsUncheckedUpdateManyWithoutLessonsNestedInput = {
  create?: Prisma.XOR<Prisma.visio_acoustic_contentsCreateWithoutLessonsInput, Prisma.visio_acoustic_contentsUncheckedCreateWithoutLessonsInput> | Prisma.visio_acoustic_contentsCreateWithoutLessonsInput[] | Prisma.visio_acoustic_contentsUncheckedCreateWithoutLessonsInput[]
  connectOrCreate?: Prisma.visio_acoustic_contentsCreateOrConnectWithoutLessonsInput | Prisma.visio_acoustic_contentsCreateOrConnectWithoutLessonsInput[]
  upsert?: Prisma.visio_acoustic_contentsUpsertWithWhereUniqueWithoutLessonsInput | Prisma.visio_acoustic_contentsUpsertWithWhereUniqueWithoutLessonsInput[]
  createMany?: Prisma.visio_acoustic_contentsCreateManyLessonsInputEnvelope
  set?: Prisma.visio_acoustic_contentsWhereUniqueInput | Prisma.visio_acoustic_contentsWhereUniqueInput[]
  disconnect?: Prisma.visio_acoustic_contentsWhereUniqueInput | Prisma.visio_acoustic_contentsWhereUniqueInput[]
  delete?: Prisma.visio_acoustic_contentsWhereUniqueInput | Prisma.visio_acoustic_contentsWhereUniqueInput[]
  connect?: Prisma.visio_acoustic_contentsWhereUniqueInput | Prisma.visio_acoustic_contentsWhereUniqueInput[]
  update?: Prisma.visio_acoustic_contentsUpdateWithWhereUniqueWithoutLessonsInput | Prisma.visio_acoustic_contentsUpdateWithWhereUniqueWithoutLessonsInput[]
  updateMany?: Prisma.visio_acoustic_contentsUpdateManyWithWhereWithoutLessonsInput | Prisma.visio_acoustic_contentsUpdateManyWithWhereWithoutLessonsInput[]
  deleteMany?: Prisma.visio_acoustic_contentsScalarWhereInput | Prisma.visio_acoustic_contentsScalarWhereInput[]
}

export type visio_acoustic_contentsCreateWithoutLessonsInput = {
  question_text: string
  sound_url: string
  image_url: string
  correct_answer: string
  option_b: string
  option_c: string
  option_d?: string | null
  feedback_correct?: string | null
  feedback_incorrect?: string | null
  question_order?: number
  difficulty_level?: string
}

export type visio_acoustic_contentsUncheckedCreateWithoutLessonsInput = {
  id?: number
  question_text: string
  sound_url: string
  image_url: string
  correct_answer: string
  option_b: string
  option_c: string
  option_d?: string | null
  feedback_correct?: string | null
  feedback_incorrect?: string | null
  question_order?: number
  difficulty_level?: string
}

export type visio_acoustic_contentsCreateOrConnectWithoutLessonsInput = {
  where: Prisma.visio_acoustic_contentsWhereUniqueInput
  create: Prisma.XOR<Prisma.visio_acoustic_contentsCreateWithoutLessonsInput, Prisma.visio_acoustic_contentsUncheckedCreateWithoutLessonsInput>
}

export type visio_acoustic_contentsCreateManyLessonsInputEnvelope = {
  data: Prisma.visio_acoustic_contentsCreateManyLessonsInput | Prisma.visio_acoustic_contentsCreateManyLessonsInput[]
  skipDuplicates?: boolean
}

export type visio_acoustic_contentsUpsertWithWhereUniqueWithoutLessonsInput = {
  where: Prisma.visio_acoustic_contentsWhereUniqueInput
  update: Prisma.XOR<Prisma.visio_acoustic_contentsUpdateWithoutLessonsInput, Prisma.visio_acoustic_contentsUncheckedUpdateWithoutLessonsInput>
  create: Prisma.XOR<Prisma.visio_acoustic_contentsCreateWithoutLessonsInput, Prisma.visio_acoustic_contentsUncheckedCreateWithoutLessonsInput>
}

export type visio_acoustic_contentsUpdateWithWhereUniqueWithoutLessonsInput = {
  where: Prisma.visio_acoustic_contentsWhereUniqueInput
  data: Prisma.XOR<Prisma.visio_acoustic_contentsUpdateWithoutLessonsInput, Prisma.visio_acoustic_contentsUncheckedUpdateWithoutLessonsInput>
}

export type visio_acoustic_contentsUpdateManyWithWhereWithoutLessonsInput = {
  where: Prisma.visio_acoustic_contentsScalarWhereInput
  data: Prisma.XOR<Prisma.visio_acoustic_contentsUpdateManyMutationInput, Prisma.visio_acoustic_contentsUncheckedUpdateManyWithoutLessonsInput>
}

export type visio_acoustic_contentsScalarWhereInput = {
  AND?: Prisma.visio_acoustic_contentsScalarWhereInput | Prisma.visio_acoustic_contentsScalarWhereInput[]
  OR?: Prisma.visio_acoustic_contentsScalarWhereInput[]
  NOT?: Prisma.visio_acoustic_contentsScalarWhereInput | Prisma.visio_acoustic_contentsScalarWhereInput[]
  id?: Prisma.IntFilter<"visio_acoustic_contents"> | number
  lesson_id?: Prisma.IntFilter<"visio_acoustic_contents"> | number
  question_text?: Prisma.StringFilter<"visio_acoustic_contents"> | string
  sound_url?: Prisma.StringFilter<"visio_acoustic_contents"> | string
  image_url?: Prisma.StringFilter<"visio_acoustic_contents"> | string
  correct_answer?: Prisma.StringFilter<"visio_acoustic_contents"> | string
  option_b?: Prisma.StringFilter<"visio_acoustic_contents"> | string
  option_c?: Prisma.StringFilter<"visio_acoustic_contents"> | string
  option_d?: Prisma.StringNullableFilter<"visio_acoustic_contents"> | string | null
  feedback_correct?: Prisma.StringNullableFilter<"visio_acoustic_contents"> | string | null
  feedback_incorrect?: Prisma.StringNullableFilter<"visio_acoustic_contents"> | string | null
  question_order?: Prisma.IntFilter<"visio_acoustic_contents"> | number
  difficulty_level?: Prisma.StringFilter<"visio_acoustic_contents"> | string
}

export type visio_acoustic_contentsCreateManyLessonsInput = {
  id?: number
  question_text: string
  sound_url: string
  image_url: string
  correct_answer: string
  option_b: string
  option_c: string
  option_d?: string | null
  feedback_correct?: string | null
  feedback_incorrect?: string | null
  question_order?: number
  difficulty_level?: string
}

export type visio_acoustic_contentsUpdateWithoutLessonsInput = {
  question_text?: Prisma.StringFieldUpdateOperationsInput | string
  sound_url?: Prisma.StringFieldUpdateOperationsInput | string
  image_url?: Prisma.StringFieldUpdateOperationsInput | string
  correct_answer?: Prisma.StringFieldUpdateOperationsInput | string
  option_b?: Prisma.StringFieldUpdateOperationsInput | string
  option_c?: Prisma.StringFieldUpdateOperationsInput | string
  option_d?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  feedback_correct?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  feedback_incorrect?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  question_order?: Prisma.IntFieldUpdateOperationsInput | number
  difficulty_level?: Prisma.StringFieldUpdateOperationsInput | string
}

export type visio_acoustic_contentsUncheckedUpdateWithoutLessonsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  question_text?: Prisma.StringFieldUpdateOperationsInput | string
  sound_url?: Prisma.StringFieldUpdateOperationsInput | string
  image_url?: Prisma.StringFieldUpdateOperationsInput | string
  correct_answer?: Prisma.StringFieldUpdateOperationsInput | string
  option_b?: Prisma.StringFieldUpdateOperationsInput | string
  option_c?: Prisma.StringFieldUpdateOperationsInput | string
  option_d?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  feedback_correct?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  feedback_incorrect?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  question_order?: Prisma.IntFieldUpdateOperationsInput | number
  difficulty_level?: Prisma.StringFieldUpdateOperationsInput | string
}

export type visio_acoustic_contentsUncheckedUpdateManyWithoutLessonsInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  question_text?: Prisma.StringFieldUpdateOperationsInput | string
  sound_url?: Prisma.StringFieldUpdateOperationsInput | string
  image_url?: Prisma.StringFieldUpdateOperationsInput | string
  correct_answer?: Prisma.StringFieldUpdateOperationsInput | string
  option_b?: Prisma.StringFieldUpdateOperationsInput | string
  option_c?: Prisma.StringFieldUpdateOperationsInput | string
  option_d?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  feedback_correct?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  feedback_incorrect?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  question_order?: Prisma.IntFieldUpdateOperationsInput | number
  difficulty_level?: Prisma.StringFieldUpdateOperationsInput | string
}



export type visio_acoustic_contentsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  lesson_id?: boolean
  question_text?: boolean
  sound_url?: boolean
  image_url?: boolean
  correct_answer?: boolean
  option_b?: boolean
  option_c?: boolean
  option_d?: boolean
  feedback_correct?: boolean
  feedback_incorrect?: boolean
  question_order?: boolean
  difficulty_level?: boolean
  lessons?: boolean | Prisma.lessonsDefaultArgs<ExtArgs>
}, ExtArgs["result"]["visio_acoustic_contents"]>

export type visio_acoustic_contentsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  lesson_id?: boolean
  question_text?: boolean
  sound_url?: boolean
  image_url?: boolean
  correct_answer?: boolean
  option_b?: boolean
  option_c?: boolean
  option_d?: boolean
  feedback_correct?: boolean
  feedback_incorrect?: boolean
  question_order?: boolean
  difficulty_level?: boolean
  lessons?: boolean | Prisma.lessonsDefaultArgs<ExtArgs>
}, ExtArgs["result"]["visio_acoustic_contents"]>

export type visio_acoustic_contentsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  lesson_id?: boolean
  question_text?: boolean
  sound_url?: boolean
  image_url?: boolean
  correct_answer?: boolean
  option_b?: boolean
  option_c?: boolean
  option_d?: boolean
  feedback_correct?: boolean
  feedback_incorrect?: boolean
  question_order?: boolean
  difficulty_level?: boolean
  lessons?: boolean | Prisma.lessonsDefaultArgs<ExtArgs>
}, ExtArgs["result"]["visio_acoustic_contents"]>

export type visio_acoustic_contentsSelectScalar = {
  id?: boolean
  lesson_id?: boolean
  question_text?: boolean
  sound_url?: boolean
  image_url?: boolean
  correct_answer?: boolean
  option_b?: boolean
  option_c?: boolean
  option_d?: boolean
  feedback_correct?: boolean
  feedback_incorrect?: boolean
  question_order?: boolean
  difficulty_level?: boolean
}

export type visio_acoustic_contentsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "lesson_id" | "question_text" | "sound_url" | "image_url" | "correct_answer" | "option_b" | "option_c" | "option_d" | "feedback_correct" | "feedback_incorrect" | "question_order" | "difficulty_level", ExtArgs["result"]["visio_acoustic_contents"]>
export type visio_acoustic_contentsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  lessons?: boolean | Prisma.lessonsDefaultArgs<ExtArgs>
}
export type visio_acoustic_contentsIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  lessons?: boolean | Prisma.lessonsDefaultArgs<ExtArgs>
}
export type visio_acoustic_contentsIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  lessons?: boolean | Prisma.lessonsDefaultArgs<ExtArgs>
}

export type $visio_acoustic_contentsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "visio_acoustic_contents"
  objects: {
    lessons: Prisma.$lessonsPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    lesson_id: number
    question_text: string
    sound_url: string
    image_url: string
    correct_answer: string
    option_b: string
    option_c: string
    option_d: string | null
    feedback_correct: string | null
    feedback_incorrect: string | null
    question_order: number
    difficulty_level: string
  }, ExtArgs["result"]["visio_acoustic_contents"]>
  composites: {}
}

export type visio_acoustic_contentsGetPayload<S extends boolean | null | undefined | visio_acoustic_contentsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$visio_acoustic_contentsPayload, S>

export type visio_acoustic_contentsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<visio_acoustic_contentsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: Visio_acoustic_contentsCountAggregateInputType | true
  }

export interface visio_acoustic_contentsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['visio_acoustic_contents'], meta: { name: 'visio_acoustic_contents' } }
  /**
   * Find zero or one Visio_acoustic_contents that matches the filter.
   * @param {visio_acoustic_contentsFindUniqueArgs} args - Arguments to find a Visio_acoustic_contents
   * @example
   * // Get one Visio_acoustic_contents
   * const visio_acoustic_contents = await prisma.visio_acoustic_contents.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends visio_acoustic_contentsFindUniqueArgs>(args: Prisma.SelectSubset<T, visio_acoustic_contentsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__visio_acoustic_contentsClient<runtime.Types.Result.GetResult<Prisma.$visio_acoustic_contentsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Visio_acoustic_contents that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {visio_acoustic_contentsFindUniqueOrThrowArgs} args - Arguments to find a Visio_acoustic_contents
   * @example
   * // Get one Visio_acoustic_contents
   * const visio_acoustic_contents = await prisma.visio_acoustic_contents.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends visio_acoustic_contentsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, visio_acoustic_contentsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__visio_acoustic_contentsClient<runtime.Types.Result.GetResult<Prisma.$visio_acoustic_contentsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Visio_acoustic_contents that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {visio_acoustic_contentsFindFirstArgs} args - Arguments to find a Visio_acoustic_contents
   * @example
   * // Get one Visio_acoustic_contents
   * const visio_acoustic_contents = await prisma.visio_acoustic_contents.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends visio_acoustic_contentsFindFirstArgs>(args?: Prisma.SelectSubset<T, visio_acoustic_contentsFindFirstArgs<ExtArgs>>): Prisma.Prisma__visio_acoustic_contentsClient<runtime.Types.Result.GetResult<Prisma.$visio_acoustic_contentsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Visio_acoustic_contents that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {visio_acoustic_contentsFindFirstOrThrowArgs} args - Arguments to find a Visio_acoustic_contents
   * @example
   * // Get one Visio_acoustic_contents
   * const visio_acoustic_contents = await prisma.visio_acoustic_contents.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends visio_acoustic_contentsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, visio_acoustic_contentsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__visio_acoustic_contentsClient<runtime.Types.Result.GetResult<Prisma.$visio_acoustic_contentsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Visio_acoustic_contents that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {visio_acoustic_contentsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Visio_acoustic_contents
   * const visio_acoustic_contents = await prisma.visio_acoustic_contents.findMany()
   * 
   * // Get first 10 Visio_acoustic_contents
   * const visio_acoustic_contents = await prisma.visio_acoustic_contents.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const visio_acoustic_contentsWithIdOnly = await prisma.visio_acoustic_contents.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends visio_acoustic_contentsFindManyArgs>(args?: Prisma.SelectSubset<T, visio_acoustic_contentsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$visio_acoustic_contentsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Visio_acoustic_contents.
   * @param {visio_acoustic_contentsCreateArgs} args - Arguments to create a Visio_acoustic_contents.
   * @example
   * // Create one Visio_acoustic_contents
   * const Visio_acoustic_contents = await prisma.visio_acoustic_contents.create({
   *   data: {
   *     // ... data to create a Visio_acoustic_contents
   *   }
   * })
   * 
   */
  create<T extends visio_acoustic_contentsCreateArgs>(args: Prisma.SelectSubset<T, visio_acoustic_contentsCreateArgs<ExtArgs>>): Prisma.Prisma__visio_acoustic_contentsClient<runtime.Types.Result.GetResult<Prisma.$visio_acoustic_contentsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Visio_acoustic_contents.
   * @param {visio_acoustic_contentsCreateManyArgs} args - Arguments to create many Visio_acoustic_contents.
   * @example
   * // Create many Visio_acoustic_contents
   * const visio_acoustic_contents = await prisma.visio_acoustic_contents.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends visio_acoustic_contentsCreateManyArgs>(args?: Prisma.SelectSubset<T, visio_acoustic_contentsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Visio_acoustic_contents and returns the data saved in the database.
   * @param {visio_acoustic_contentsCreateManyAndReturnArgs} args - Arguments to create many Visio_acoustic_contents.
   * @example
   * // Create many Visio_acoustic_contents
   * const visio_acoustic_contents = await prisma.visio_acoustic_contents.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Visio_acoustic_contents and only return the `id`
   * const visio_acoustic_contentsWithIdOnly = await prisma.visio_acoustic_contents.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends visio_acoustic_contentsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, visio_acoustic_contentsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$visio_acoustic_contentsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Visio_acoustic_contents.
   * @param {visio_acoustic_contentsDeleteArgs} args - Arguments to delete one Visio_acoustic_contents.
   * @example
   * // Delete one Visio_acoustic_contents
   * const Visio_acoustic_contents = await prisma.visio_acoustic_contents.delete({
   *   where: {
   *     // ... filter to delete one Visio_acoustic_contents
   *   }
   * })
   * 
   */
  delete<T extends visio_acoustic_contentsDeleteArgs>(args: Prisma.SelectSubset<T, visio_acoustic_contentsDeleteArgs<ExtArgs>>): Prisma.Prisma__visio_acoustic_contentsClient<runtime.Types.Result.GetResult<Prisma.$visio_acoustic_contentsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Visio_acoustic_contents.
   * @param {visio_acoustic_contentsUpdateArgs} args - Arguments to update one Visio_acoustic_contents.
   * @example
   * // Update one Visio_acoustic_contents
   * const visio_acoustic_contents = await prisma.visio_acoustic_contents.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends visio_acoustic_contentsUpdateArgs>(args: Prisma.SelectSubset<T, visio_acoustic_contentsUpdateArgs<ExtArgs>>): Prisma.Prisma__visio_acoustic_contentsClient<runtime.Types.Result.GetResult<Prisma.$visio_acoustic_contentsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Visio_acoustic_contents.
   * @param {visio_acoustic_contentsDeleteManyArgs} args - Arguments to filter Visio_acoustic_contents to delete.
   * @example
   * // Delete a few Visio_acoustic_contents
   * const { count } = await prisma.visio_acoustic_contents.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends visio_acoustic_contentsDeleteManyArgs>(args?: Prisma.SelectSubset<T, visio_acoustic_contentsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Visio_acoustic_contents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {visio_acoustic_contentsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Visio_acoustic_contents
   * const visio_acoustic_contents = await prisma.visio_acoustic_contents.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends visio_acoustic_contentsUpdateManyArgs>(args: Prisma.SelectSubset<T, visio_acoustic_contentsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Visio_acoustic_contents and returns the data updated in the database.
   * @param {visio_acoustic_contentsUpdateManyAndReturnArgs} args - Arguments to update many Visio_acoustic_contents.
   * @example
   * // Update many Visio_acoustic_contents
   * const visio_acoustic_contents = await prisma.visio_acoustic_contents.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Visio_acoustic_contents and only return the `id`
   * const visio_acoustic_contentsWithIdOnly = await prisma.visio_acoustic_contents.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends visio_acoustic_contentsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, visio_acoustic_contentsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$visio_acoustic_contentsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Visio_acoustic_contents.
   * @param {visio_acoustic_contentsUpsertArgs} args - Arguments to update or create a Visio_acoustic_contents.
   * @example
   * // Update or create a Visio_acoustic_contents
   * const visio_acoustic_contents = await prisma.visio_acoustic_contents.upsert({
   *   create: {
   *     // ... data to create a Visio_acoustic_contents
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Visio_acoustic_contents we want to update
   *   }
   * })
   */
  upsert<T extends visio_acoustic_contentsUpsertArgs>(args: Prisma.SelectSubset<T, visio_acoustic_contentsUpsertArgs<ExtArgs>>): Prisma.Prisma__visio_acoustic_contentsClient<runtime.Types.Result.GetResult<Prisma.$visio_acoustic_contentsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Visio_acoustic_contents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {visio_acoustic_contentsCountArgs} args - Arguments to filter Visio_acoustic_contents to count.
   * @example
   * // Count the number of Visio_acoustic_contents
   * const count = await prisma.visio_acoustic_contents.count({
   *   where: {
   *     // ... the filter for the Visio_acoustic_contents we want to count
   *   }
   * })
  **/
  count<T extends visio_acoustic_contentsCountArgs>(
    args?: Prisma.Subset<T, visio_acoustic_contentsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], Visio_acoustic_contentsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Visio_acoustic_contents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {Visio_acoustic_contentsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends Visio_acoustic_contentsAggregateArgs>(args: Prisma.Subset<T, Visio_acoustic_contentsAggregateArgs>): Prisma.PrismaPromise<GetVisio_acoustic_contentsAggregateType<T>>

  /**
   * Group by Visio_acoustic_contents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {visio_acoustic_contentsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends visio_acoustic_contentsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: visio_acoustic_contentsGroupByArgs['orderBy'] }
      : { orderBy?: visio_acoustic_contentsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, visio_acoustic_contentsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetVisio_acoustic_contentsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the visio_acoustic_contents model
 */
readonly fields: visio_acoustic_contentsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for visio_acoustic_contents.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__visio_acoustic_contentsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  lessons<T extends Prisma.lessonsDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.lessonsDefaultArgs<ExtArgs>>): Prisma.Prisma__lessonsClient<runtime.Types.Result.GetResult<Prisma.$lessonsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the visio_acoustic_contents model
 */
export interface visio_acoustic_contentsFieldRefs {
  readonly id: Prisma.FieldRef<"visio_acoustic_contents", 'Int'>
  readonly lesson_id: Prisma.FieldRef<"visio_acoustic_contents", 'Int'>
  readonly question_text: Prisma.FieldRef<"visio_acoustic_contents", 'String'>
  readonly sound_url: Prisma.FieldRef<"visio_acoustic_contents", 'String'>
  readonly image_url: Prisma.FieldRef<"visio_acoustic_contents", 'String'>
  readonly correct_answer: Prisma.FieldRef<"visio_acoustic_contents", 'String'>
  readonly option_b: Prisma.FieldRef<"visio_acoustic_contents", 'String'>
  readonly option_c: Prisma.FieldRef<"visio_acoustic_contents", 'String'>
  readonly option_d: Prisma.FieldRef<"visio_acoustic_contents", 'String'>
  readonly feedback_correct: Prisma.FieldRef<"visio_acoustic_contents", 'String'>
  readonly feedback_incorrect: Prisma.FieldRef<"visio_acoustic_contents", 'String'>
  readonly question_order: Prisma.FieldRef<"visio_acoustic_contents", 'Int'>
  readonly difficulty_level: Prisma.FieldRef<"visio_acoustic_contents", 'String'>
}
    

// Custom InputTypes
/**
 * visio_acoustic_contents findUnique
 */
export type visio_acoustic_contentsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the visio_acoustic_contents
   */
  select?: Prisma.visio_acoustic_contentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the visio_acoustic_contents
   */
  omit?: Prisma.visio_acoustic_contentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.visio_acoustic_contentsInclude<ExtArgs> | null
  /**
   * Filter, which visio_acoustic_contents to fetch.
   */
  where: Prisma.visio_acoustic_contentsWhereUniqueInput
}

/**
 * visio_acoustic_contents findUniqueOrThrow
 */
export type visio_acoustic_contentsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the visio_acoustic_contents
   */
  select?: Prisma.visio_acoustic_contentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the visio_acoustic_contents
   */
  omit?: Prisma.visio_acoustic_contentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.visio_acoustic_contentsInclude<ExtArgs> | null
  /**
   * Filter, which visio_acoustic_contents to fetch.
   */
  where: Prisma.visio_acoustic_contentsWhereUniqueInput
}

/**
 * visio_acoustic_contents findFirst
 */
export type visio_acoustic_contentsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the visio_acoustic_contents
   */
  select?: Prisma.visio_acoustic_contentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the visio_acoustic_contents
   */
  omit?: Prisma.visio_acoustic_contentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.visio_acoustic_contentsInclude<ExtArgs> | null
  /**
   * Filter, which visio_acoustic_contents to fetch.
   */
  where?: Prisma.visio_acoustic_contentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of visio_acoustic_contents to fetch.
   */
  orderBy?: Prisma.visio_acoustic_contentsOrderByWithRelationInput | Prisma.visio_acoustic_contentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for visio_acoustic_contents.
   */
  cursor?: Prisma.visio_acoustic_contentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` visio_acoustic_contents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` visio_acoustic_contents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of visio_acoustic_contents.
   */
  distinct?: Prisma.Visio_acoustic_contentsScalarFieldEnum | Prisma.Visio_acoustic_contentsScalarFieldEnum[]
}

/**
 * visio_acoustic_contents findFirstOrThrow
 */
export type visio_acoustic_contentsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the visio_acoustic_contents
   */
  select?: Prisma.visio_acoustic_contentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the visio_acoustic_contents
   */
  omit?: Prisma.visio_acoustic_contentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.visio_acoustic_contentsInclude<ExtArgs> | null
  /**
   * Filter, which visio_acoustic_contents to fetch.
   */
  where?: Prisma.visio_acoustic_contentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of visio_acoustic_contents to fetch.
   */
  orderBy?: Prisma.visio_acoustic_contentsOrderByWithRelationInput | Prisma.visio_acoustic_contentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for visio_acoustic_contents.
   */
  cursor?: Prisma.visio_acoustic_contentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` visio_acoustic_contents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` visio_acoustic_contents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of visio_acoustic_contents.
   */
  distinct?: Prisma.Visio_acoustic_contentsScalarFieldEnum | Prisma.Visio_acoustic_contentsScalarFieldEnum[]
}

/**
 * visio_acoustic_contents findMany
 */
export type visio_acoustic_contentsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the visio_acoustic_contents
   */
  select?: Prisma.visio_acoustic_contentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the visio_acoustic_contents
   */
  omit?: Prisma.visio_acoustic_contentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.visio_acoustic_contentsInclude<ExtArgs> | null
  /**
   * Filter, which visio_acoustic_contents to fetch.
   */
  where?: Prisma.visio_acoustic_contentsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of visio_acoustic_contents to fetch.
   */
  orderBy?: Prisma.visio_acoustic_contentsOrderByWithRelationInput | Prisma.visio_acoustic_contentsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing visio_acoustic_contents.
   */
  cursor?: Prisma.visio_acoustic_contentsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` visio_acoustic_contents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` visio_acoustic_contents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of visio_acoustic_contents.
   */
  distinct?: Prisma.Visio_acoustic_contentsScalarFieldEnum | Prisma.Visio_acoustic_contentsScalarFieldEnum[]
}

/**
 * visio_acoustic_contents create
 */
export type visio_acoustic_contentsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the visio_acoustic_contents
   */
  select?: Prisma.visio_acoustic_contentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the visio_acoustic_contents
   */
  omit?: Prisma.visio_acoustic_contentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.visio_acoustic_contentsInclude<ExtArgs> | null
  /**
   * The data needed to create a visio_acoustic_contents.
   */
  data: Prisma.XOR<Prisma.visio_acoustic_contentsCreateInput, Prisma.visio_acoustic_contentsUncheckedCreateInput>
}

/**
 * visio_acoustic_contents createMany
 */
export type visio_acoustic_contentsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many visio_acoustic_contents.
   */
  data: Prisma.visio_acoustic_contentsCreateManyInput | Prisma.visio_acoustic_contentsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * visio_acoustic_contents createManyAndReturn
 */
export type visio_acoustic_contentsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the visio_acoustic_contents
   */
  select?: Prisma.visio_acoustic_contentsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the visio_acoustic_contents
   */
  omit?: Prisma.visio_acoustic_contentsOmit<ExtArgs> | null
  /**
   * The data used to create many visio_acoustic_contents.
   */
  data: Prisma.visio_acoustic_contentsCreateManyInput | Prisma.visio_acoustic_contentsCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.visio_acoustic_contentsIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * visio_acoustic_contents update
 */
export type visio_acoustic_contentsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the visio_acoustic_contents
   */
  select?: Prisma.visio_acoustic_contentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the visio_acoustic_contents
   */
  omit?: Prisma.visio_acoustic_contentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.visio_acoustic_contentsInclude<ExtArgs> | null
  /**
   * The data needed to update a visio_acoustic_contents.
   */
  data: Prisma.XOR<Prisma.visio_acoustic_contentsUpdateInput, Prisma.visio_acoustic_contentsUncheckedUpdateInput>
  /**
   * Choose, which visio_acoustic_contents to update.
   */
  where: Prisma.visio_acoustic_contentsWhereUniqueInput
}

/**
 * visio_acoustic_contents updateMany
 */
export type visio_acoustic_contentsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update visio_acoustic_contents.
   */
  data: Prisma.XOR<Prisma.visio_acoustic_contentsUpdateManyMutationInput, Prisma.visio_acoustic_contentsUncheckedUpdateManyInput>
  /**
   * Filter which visio_acoustic_contents to update
   */
  where?: Prisma.visio_acoustic_contentsWhereInput
  /**
   * Limit how many visio_acoustic_contents to update.
   */
  limit?: number
}

/**
 * visio_acoustic_contents updateManyAndReturn
 */
export type visio_acoustic_contentsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the visio_acoustic_contents
   */
  select?: Prisma.visio_acoustic_contentsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the visio_acoustic_contents
   */
  omit?: Prisma.visio_acoustic_contentsOmit<ExtArgs> | null
  /**
   * The data used to update visio_acoustic_contents.
   */
  data: Prisma.XOR<Prisma.visio_acoustic_contentsUpdateManyMutationInput, Prisma.visio_acoustic_contentsUncheckedUpdateManyInput>
  /**
   * Filter which visio_acoustic_contents to update
   */
  where?: Prisma.visio_acoustic_contentsWhereInput
  /**
   * Limit how many visio_acoustic_contents to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.visio_acoustic_contentsIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * visio_acoustic_contents upsert
 */
export type visio_acoustic_contentsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the visio_acoustic_contents
   */
  select?: Prisma.visio_acoustic_contentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the visio_acoustic_contents
   */
  omit?: Prisma.visio_acoustic_contentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.visio_acoustic_contentsInclude<ExtArgs> | null
  /**
   * The filter to search for the visio_acoustic_contents to update in case it exists.
   */
  where: Prisma.visio_acoustic_contentsWhereUniqueInput
  /**
   * In case the visio_acoustic_contents found by the `where` argument doesn't exist, create a new visio_acoustic_contents with this data.
   */
  create: Prisma.XOR<Prisma.visio_acoustic_contentsCreateInput, Prisma.visio_acoustic_contentsUncheckedCreateInput>
  /**
   * In case the visio_acoustic_contents was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.visio_acoustic_contentsUpdateInput, Prisma.visio_acoustic_contentsUncheckedUpdateInput>
}

/**
 * visio_acoustic_contents delete
 */
export type visio_acoustic_contentsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the visio_acoustic_contents
   */
  select?: Prisma.visio_acoustic_contentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the visio_acoustic_contents
   */
  omit?: Prisma.visio_acoustic_contentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.visio_acoustic_contentsInclude<ExtArgs> | null
  /**
   * Filter which visio_acoustic_contents to delete.
   */
  where: Prisma.visio_acoustic_contentsWhereUniqueInput
}

/**
 * visio_acoustic_contents deleteMany
 */
export type visio_acoustic_contentsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which visio_acoustic_contents to delete
   */
  where?: Prisma.visio_acoustic_contentsWhereInput
  /**
   * Limit how many visio_acoustic_contents to delete.
   */
  limit?: number
}

/**
 * visio_acoustic_contents without action
 */
export type visio_acoustic_contentsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the visio_acoustic_contents
   */
  select?: Prisma.visio_acoustic_contentsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the visio_acoustic_contents
   */
  omit?: Prisma.visio_acoustic_contentsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.visio_acoustic_contentsInclude<ExtArgs> | null
}
